local weapon_unlock_settings = {
	psyker_2 = {
		{},
		{},
		{
			"content/items/weapons/player/ranged/autogun_p3_m1",
			"content/items/weapons/player/ranged/lasgun_p1_m2"
		},
		{
			"content/items/weapons/player/melee/forcesword_p1_m1",
			"content/items/weapons/player/ranged/autogun_p1_m2"
		},
		{
			"content/items/weapons/player/melee/combataxe_p1_m2"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p1_m3"
		},
		{
			"content/items/weapons/player/ranged/stubrevolver_p1_m1",
			"content/items/weapons/player/melee/combatsword_p1_m2"
		},
		{
			"content/items/weapons/player/ranged/forcestaff_p1_m1",
			"content/items/weapons/player/ranged/autogun_p1_m3"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p3_m1",
			"content/items/weapons/player/melee/combataxe_p1_m3"
		},
		{},
		{},
		{},
		{
			"content/items/weapons/player/ranged/lasgun_p3_m2",
			"content/items/weapons/player/ranged/autogun_p3_m2"
		},
		{},
		{
			"content/items/weapons/player/ranged/autogun_p3_m3",
			"content/items/weapons/player/ranged/lasgun_p3_m3"
		},
		{},
		{
			"content/items/weapons/player/melee/chainsword_p1_m1"
		},
		{
			"content/items/weapons/player/melee/combatsword_p1_m3"
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	},
	zealot_2 = {
		{},
		{
			"content/items/weapons/player/ranged/autogun_p2_m1"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p1_m2"
		},
		{
			"content/items/weapons/player/melee/combatsword_p1_m1"
		},
		{
			"content/items/weapons/player/ranged/autogun_p3_m1",
			"content/items/weapons/player/melee/combataxe_p1_m3"
		},
		{
			"content/items/weapons/player/ranged/shotgun_p1_m1"
		},
		{
			"content/items/weapons/player/melee/combatsword_p1_m2"
		},
		{
			"content/items/weapons/player/ranged/flamer_p1_m1"
		},
		{
			"content/items/weapons/player/ranged/autogun_p2_m2"
		},
		{
			"content/items/weapons/player/melee/chainsword_p1_m1"
		},
		{
			"content/items/weapons/player/melee/chainsword_2h_p1_m1",
			"content/items/weapons/player/ranged/autogun_p3_m2"
		},
		{
			"content/items/weapons/player/ranged/stubrevolver_p1_m1",
			"content/items/weapons/player/melee/combatsword_p1_m3"
		},
		{
			"content/items/weapons/player/melee/chainaxe_p1_m1",
			"content/items/weapons/player/ranged/autogun_p1_m2"
		},
		{
			"content/items/weapons/player/ranged/bolter_p1_m1"
		},
		{
			"content/items/weapons/player/ranged/autogun_p1_m3"
		},
		{
			"content/items/weapons/player/melee/thunderhammer_2h_p1_m1"
		},
		{},
		{
			"content/items/weapons/player/ranged/autogun_p2_m3"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p1_m3"
		},
		{},
		{},
		{
			"content/items/weapons/player/ranged/autogun_p3_m3"
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	},
	ogryn_2 = {
		{},
		{
			"content/items/weapons/player/melee/ogryn_combatblade_p1_m3"
		},
		{},
		{
			"content/items/weapons/player/ranged/ogryn_rippergun_p1_m1"
		},
		{},
		{
			"content/items/weapons/player/melee/ogryn_club_p1_m1"
		},
		{},
		{},
		{
			"content/items/weapons/player/melee/ogryn_combatblade_p1_m2"
		},
		{},
		{},
		{},
		{
			"content/items/weapons/player/ranged/ogryn_thumper_p1_m2"
		},
		{
			"content/items/weapons/player/ranged/ogryn_rippergun_p1_m3"
		},
		{},
		{
			"content/items/weapons/player/ranged/ogryn_gauntlet_p1_m1"
		},
		{
			"content/items/weapons/player/ranged/ogryn_rippergun_p1_m2"
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	},
	veteran_2 = {
		{},
		{
			"content/items/weapons/player/ranged/autogun_p3_m1"
		},
		{
			"content/items/weapons/player/melee/combatsword_p1_m1"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p1_m3"
		},
		{
			"content/items/weapons/player/ranged/autogun_p3_m2"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p3_m1"
		},
		{
			"content/items/weapons/player/ranged/autogun_p2_m1"
		},
		{
			"content/items/weapons/player/ranged/autogun_p3_m3",
			"content/items/weapons/player/melee/combataxe_p1_m2"
		},
		{
			"content/items/weapons/player/ranged/shotgun_p1_m1",
			"content/items/weapons/player/ranged/lasgun_p3_m3"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p2_m1"
		},
		{
			"content/items/weapons/player/ranged/stubrevolver_p1_m1",
			"content/items/weapons/player/ranged/autogun_p1_m2"
		},
		{
			"content/items/weapons/player/melee/chainsword_p1_m1",
			"content/items/weapons/player/ranged/lasgun_p2_m2"
		},
		{
			"content/items/weapons/player/ranged/bolter_p1_m1",
			"content/items/weapons/player/ranged/autogun_p2_m2"
		},
		{
			"content/items/weapons/player/melee/powersword_p1_m1"
		},
		{
			"content/items/weapons/player/ranged/lasgun_p3_m2",
			"content/items/weapons/player/ranged/autogun_p1_m3"
		},
		{},
		{
			"content/items/weapons/player/ranged/plasmagun_p1_m1",
			"content/items/weapons/player/ranged/lasgun_p2_m3"
		},
		{},
		{
			"content/items/weapons/player/melee/chainaxe_p1_m1",
			"content/items/weapons/player/melee/combataxe_p1_m3"
		},
		{
			"content/items/weapons/player/melee/combatsword_p1_m3"
		},
		{
			"content/items/weapons/player/melee/combatsword_p1_m2",
			"content/items/weapons/player/ranged/autogun_p2_m3"
		},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{}
	}
}

return settings("weapon_unlock_settings", weapon_unlock_settings)
