-- chunkname: @scripts/settings/buff/weapon_traits_buff_templates/weapon_traits_bespoke_galvanic_rifle_p1_buff_templates.lua

local BaseWeaponTraitBuffTemplates = require("scripts/settings/buff/weapon_traits_buff_templates/base_weapon_trait_buff_templates")
local BuffSettings = require("scripts/settings/buff/buff_settings")
local ConditionalFunctions = require("scripts/settings/buff/helper_functions/conditional_functions")
local stat_buffs = BuffSettings.stat_buffs
local templates = {}

table.make_unique(templates)

templates.weapon_trait_bespoke_galvanic_rifle_p1_suppression_negation_on_weakspot = table.clone(BaseWeaponTraitBuffTemplates.suppression_negation_on_weakspot)
templates.weapon_trait_bespoke_galvanic_rifle_p1_crit_weakspot_finesse = table.clone(BaseWeaponTraitBuffTemplates.crit_weakspot_finesse)
templates.weapon_trait_bespoke_galvanic_rifle_p1_count_as_dodge_vs_ranged_on_weakspot = table.clone(BaseWeaponTraitBuffTemplates.count_as_dodge_vs_ranged_on_weakspot)
templates.weapon_trait_bespoke_galvanic_rifle_p1_stacking_crit_chance_on_weakspot_parent = table.clone(BaseWeaponTraitBuffTemplates.stacking_crit_chance_on_weakspot_parent)
templates.weapon_trait_bespoke_galvanic_rifle_p1_stacking_crit_chance_on_weakspot_parent.child_buff_template = "weapon_trait_bespoke_galvanic_rifle_p1_stacking_crit_chance_on_weakspot_child"
templates.weapon_trait_bespoke_galvanic_rifle_p1_stacking_crit_chance_on_weakspot_child = table.clone(BaseWeaponTraitBuffTemplates.stacking_crit_chance_on_weakspot_child)
templates.weapon_trait_bespoke_galvanic_rifle_p1_target_hit_mass_reduction_on_weakspot_hits = {
	class_name = "buff",
	predicted = false,
	conditional_stat_buffs = {
		[stat_buffs.consumed_hit_mass_modifier_on_weakspot_hit] = 0.5,
	},
	conditional_stat_buffs_func = ConditionalFunctions.is_item_slot_wielded,
}
templates.weapon_trait_bespoke_galvanic_rifle_p1_cleave_on_crit = table.clone(BaseWeaponTraitBuffTemplates.infinite_cleave_on_crit)
templates.weapon_trait_bespoke_galvanic_rifle_p1_power_bonus_on_first_shot = table.clone(BaseWeaponTraitBuffTemplates.power_bonus_on_first_shot)
templates.weapon_trait_bespoke_galvanic_rifle_p1_increases_power_while_aiming = table.clone(BaseWeaponTraitBuffTemplates.power_level_on_aim_time)
templates.weapon_trait_bespoke_galvanic_rifle_p1_chained_weakspot_hits_increases_power_parent = table.clone(BaseWeaponTraitBuffTemplates.chained_weakspot_hits_increases_power_ranged_parent)
templates.weapon_trait_bespoke_galvanic_rifle_p1_chained_weakspot_hits_increases_power_parent.child_buff_template = "weapon_trait_bespoke_galvanic_rifle_p1_chained_weakspot_hits_increases_power_child"
templates.weapon_trait_bespoke_galvanic_rifle_p1_chained_weakspot_hits_increases_power_child = table.clone(BaseWeaponTraitBuffTemplates.chained_weakspot_hits_increases_power_child)
templates.weapon_trait_bespoke_galvanic_rifle_p1_chained_weakspot_hits_increases_power_child.conditional_stat_buffs = {
	[stat_buffs.ranged_power_level_modifier] = 0.05,
}
templates.weapon_trait_bespoke_galvanic_rifle_p1_toughness_on_elite_kills = table.clone(BaseWeaponTraitBuffTemplates.toughness_on_elite_kills)

return templates
