-- chunkname: @scripts/settings/buff/weapon_traits_buff_templates/weapon_traits_bespoke_combatsword_p3_buff_templates.lua

local BaseWeaponTraitBuffTemplates = require("scripts/settings/buff/weapon_traits_buff_templates/base_weapon_trait_buff_templates")
local templates = {}

table.make_unique(templates)

templates.weapon_trait_bespoke_combatsword_p3_increased_melee_damage_on_multiple_hits = table.clone(BaseWeaponTraitBuffTemplates.increased_melee_damage_on_multiple_hits)
templates.weapon_trait_bespoke_combatsword_p3_stacking_rending_on_weakspot_parent = table.clone(BaseWeaponTraitBuffTemplates.stacking_rending_on_weakspot_parent)
templates.weapon_trait_bespoke_combatsword_p3_stacking_rending_on_weakspot_parent.child_buff_template = "weapon_trait_bespoke_combatsword_p3_stacking_rending_on_weakspot_child"
templates.weapon_trait_bespoke_combatsword_p3_stacking_rending_on_weakspot_child = table.clone(BaseWeaponTraitBuffTemplates.stacking_rending_on_weakspot_child)
templates.weapon_trait_bespoke_combatsword_p3_chained_hits_increases_crit_chance_parent = table.clone(BaseWeaponTraitBuffTemplates.chained_hits_increases_crit_chance_parent)
templates.weapon_trait_bespoke_combatsword_p3_chained_hits_increases_crit_chance_parent.child_buff_template = "weapon_trait_bespoke_combatsword_p3_chained_hits_increases_crit_chance_child"
templates.weapon_trait_bespoke_combatsword_p3_chained_hits_increases_crit_chance_child = table.clone(BaseWeaponTraitBuffTemplates.chained_hits_increases_crit_chance_child)
templates.weapon_trait_bespoke_combatsword_p3_dodge_grants_finesse_bonus = table.clone(BaseWeaponTraitBuffTemplates.dodge_grants_finesse_bonus)
templates.weapon_trait_bespoke_combatsword_p3_dodge_grants_critical_strike_chance = table.clone(BaseWeaponTraitBuffTemplates.dodge_grants_critical_strike_chance)
templates.weapon_trait_bespoke_combatsword_p3_windup_increases_power_parent = table.clone(BaseWeaponTraitBuffTemplates.windup_increases_power_parent)
templates.weapon_trait_bespoke_combatsword_p3_windup_increases_power_parent.child_buff_template = "weapon_trait_bespoke_combatsword_p3_windup_increases_power_child"
templates.weapon_trait_bespoke_combatsword_p3_windup_increases_power_child = table.clone(BaseWeaponTraitBuffTemplates.windup_increases_power_child)
templates.weapon_trait_bespoke_combatsword_p3_consecutive_melee_hits_same_target_increases_melee_power_parent = table.clone(BaseWeaponTraitBuffTemplates.consecutive_melee_hits_same_target_increases_melee_power_parent)
templates.weapon_trait_bespoke_combatsword_p3_consecutive_melee_hits_same_target_increases_melee_power_child = table.clone(BaseWeaponTraitBuffTemplates.consecutive_melee_hits_same_target_increases_melee_power_child)
templates.weapon_trait_bespoke_combatsword_p3_consecutive_melee_hits_same_target_increases_melee_power_parent.child_buff_template = "weapon_trait_bespoke_combatsword_p3_consecutive_melee_hits_same_target_increases_melee_power_child"
templates.weapon_trait_bespoke_combatsword_p3_weakspot_hit_resets_dodge_count = table.clone(BaseWeaponTraitBuffTemplates.weakspot_hit_resets_dodge_count)

return templates
