-- chunkname: @scripts/settings/buff/weapon_traits_buff_templates/weapon_traits_bespoke_stubrevolver_p1_buff_templates.lua

local BaseWeaponTraitBuffTemplates = require("scripts/settings/buff/weapon_traits_buff_templates/base_weapon_trait_buff_templates")
local BuffSettings = require("scripts/settings/buff/buff_settings")
local stat_buffs = BuffSettings.stat_buffs
local templates = {}

table.make_unique(templates)

templates.weapon_trait_bespoke_stubrevolver_p1_hipfire_while_sprinting = table.clone(BaseWeaponTraitBuffTemplates.hipfire_while_sprinting)
templates.weapon_trait_bespoke_stubrevolver_p1_reload_speed_on_slide_parent = table.clone(BaseWeaponTraitBuffTemplates.reload_speed_on_close_kill_parent)
templates.weapon_trait_bespoke_stubrevolver_p1_reload_speed_on_slide_child = table.clone(BaseWeaponTraitBuffTemplates.reload_speed_on_close_kill_child)
templates.weapon_trait_bespoke_stubrevolver_p1_reload_speed_on_slide_parent.child_buff_template = "weapon_trait_bespoke_stubrevolver_p1_reload_speed_on_slide_child"
templates.weapon_trait_bespoke_stubrevolver_p1_suppression_on_close_kill = table.clone(BaseWeaponTraitBuffTemplates.suppression_on_close_kill)
templates.weapon_trait_bespoke_stubrevolver_p1_crit_chance_based_on_aim_time = table.clone(BaseWeaponTraitBuffTemplates.chance_based_on_aim_time)
templates.weapon_trait_bespoke_stubrevolver_p1_chained_weakspot_hits_increases_power_parent = table.clone(BaseWeaponTraitBuffTemplates.chained_weakspot_hits_increases_power_ranged_parent)
templates.weapon_trait_bespoke_stubrevolver_p1_chained_weakspot_hits_increases_power_parent.child_buff_template = "weapon_trait_bespoke_stubrevolver_p1_chained_weakspot_hits_increases_power_child"
templates.weapon_trait_bespoke_stubrevolver_p1_chained_weakspot_hits_increases_power_child = table.clone(BaseWeaponTraitBuffTemplates.chained_weakspot_hits_increases_power_child)
templates.weapon_trait_bespoke_stubrevolver_p1_chained_weakspot_hits_increases_power_child.conditional_stat_buffs = {
	[stat_buffs.ranged_power_level_modifier] = 0.05,
}
templates.weapon_trait_bespoke_stubrevolver_p1_crit_chance_based_on_ammo_left = table.clone(BaseWeaponTraitBuffTemplates.crit_chance_based_on_ammo_left)
templates.weapon_trait_bespoke_stubrevolver_p1_crit_chance_bonus_on_melee_kills = table.clone(BaseWeaponTraitBuffTemplates.crit_chance_bonus_on_melee_kills)
templates.weapon_trait_bespoke_stubrevolver_p1_toughness_on_elite_kills = table.clone(BaseWeaponTraitBuffTemplates.toughness_on_elite_kills)
templates.weapon_trait_bespoke_stubrevolver_p1_followup_shots_ranged_damage = table.clone(BaseWeaponTraitBuffTemplates.followup_shots_ranged_damage)
templates.weapon_trait_bespoke_stubrevolver_p1_rending_on_crit = table.clone(BaseWeaponTraitBuffTemplates.rending_on_crit)

return templates
