local BaseWeaponTraitBuffTemplates = require("scripts/settings/buff/weapon_traits_buff_templates/base_weapon_trait_buff_templates")
local BuffSettings = require("scripts/settings/buff/buff_settings")
local CheckProcFunctions = require("scripts/settings/buff/validation_functions/check_proc_functions")
local ConditionalFunctions = require("scripts/settings/buff/validation_functions/conditional_functions")
local Suppression = require("scripts/utilities/attack/suppression")
local keywords = BuffSettings.keywords
local stat_buffs = BuffSettings.stat_buffs
local proc_events = BuffSettings.proc_events
local templates = {
	weapon_trait_bespoke_lasgun_p3_increase_power_on_close_kill_parent = table.clone(BaseWeaponTraitBuffTemplates.increase_power_on_close_kill_parent),
	weapon_trait_bespoke_lasgun_p3_increase_power_on_close_kill_child = table.clone(BaseWeaponTraitBuffTemplates.increase_power_on_close_kill_child)
}
templates.weapon_trait_bespoke_lasgun_p3_increase_power_on_close_kill_parent.child_buff_template = "weapon_trait_bespoke_lasgun_p3_increase_power_on_close_kill_child"
templates.weapon_trait_bespoke_lasgun_p3_count_as_dodge_vs_ranged_on_close_kill = table.clone(BaseWeaponTraitBuffTemplates.count_as_dodge_vs_ranged_on_close_kill)
templates.weapon_trait_bespoke_lasgun_p3_reload_speed_on_slide_parent = table.clone(BaseWeaponTraitBuffTemplates.reload_speed_on_close_kill_parent)
templates.weapon_trait_bespoke_lasgun_p3_reload_speed_on_slide_child = table.clone(BaseWeaponTraitBuffTemplates.reload_speed_on_close_kill_child)
templates.weapon_trait_bespoke_lasgun_p3_reload_speed_on_slide_parent.child_buff_template = "weapon_trait_bespoke_lasgun_p3_reload_speed_on_slide_child"
templates.weapon_trait_bespoke_lasgun_p3_increased_sprint_speed = table.clone(BaseWeaponTraitBuffTemplates.count_as_dodge_vs_ranged_while_sprinting)
templates.weapon_trait_bespoke_lasgun_p3_followup_shots_ranged_damage = table.clone(BaseWeaponTraitBuffTemplates.followup_shots_ranged_damage)
templates.weapon_trait_bespoke_lasgun_p3_followup_shots_ranged_weakspot_damage = table.clone(BaseWeaponTraitBuffTemplates.followup_shots_ranged_weakspot_damage)
templates.weapon_trait_bespoke_lasgun_p3_consecutive_hits_increases_close_damage_parent = table.clone(BaseWeaponTraitBuffTemplates.consecutive_hits_increases_close_damage_parent)
templates.weapon_trait_bespoke_lasgun_p3_consecutive_hits_increases_close_damage_child = table.clone(BaseWeaponTraitBuffTemplates.consecutive_hits_increases_close_damage_child)
templates.weapon_trait_bespoke_lasgun_p3_consecutive_hits_increases_close_damage_parent.child_buff_template = "weapon_trait_bespoke_lasgun_p3_consecutive_hits_increases_close_damage_child"
templates.weapon_trait_bespoke_lasgun_p3_stacking_crit_chance_on_weakspot_parent = table.clone(BaseWeaponTraitBuffTemplates.stacking_crit_chance_on_weakspot_parent)
templates.weapon_trait_bespoke_lasgun_p3_stacking_crit_chance_on_weakspot_parent.child_buff_template = "weapon_trait_bespoke_lasgun_p3_stacking_crit_chance_on_weakspot_child"
templates.weapon_trait_bespoke_lasgun_p3_stacking_crit_chance_on_weakspot_child = table.clone(BaseWeaponTraitBuffTemplates.stacking_crit_chance_on_weakspot_child)
templates.weapon_trait_bespoke_lasgun_p3_burninating_on_crit = table.clone(BaseWeaponTraitBuffTemplates.burninating_on_crit_ranged)

return templates
