-- chunkname: @scripts/settings/buff/weapon_traits_buff_templates/weapon_traits_bespoke_ogryn_club_p2_buff_templates.lua

local BaseWeaponTraitBuffTemplates = require("scripts/settings/buff/weapon_traits_buff_templates/base_weapon_trait_buff_templates")
local BuffSettings = require("scripts/settings/buff/buff_settings")
local CheckProcFunctions = require("scripts/settings/buff/validation_functions/check_proc_functions")
local ConditionalFunctions = require("scripts/settings/buff/validation_functions/conditional_functions")
local keywords = BuffSettings.keywords
local stat_buffs = BuffSettings.stat_buffs
local proc_events = BuffSettings.proc_events
local templates = {}

templates.weapon_trait_bespoke_ogryn_club_p2_pass_past_armor_on_crit = table.clone(BaseWeaponTraitBuffTemplates.pass_past_armor_on_crit)
templates.weapon_trait_bespoke_ogryn_club_p2_windup_increases_power_parent = table.clone(BaseWeaponTraitBuffTemplates.windup_increases_power_parent)
templates.weapon_trait_bespoke_ogryn_club_p2_windup_increases_power_parent.child_buff_template = "weapon_trait_bespoke_ogryn_club_p2_windup_increases_power_child"
templates.weapon_trait_bespoke_ogryn_club_p2_windup_increases_power_child = table.clone(BaseWeaponTraitBuffTemplates.windup_increases_power_child)
templates.weapon_trait_bespoke_ogryn_club_p2_targets_receive_rending_debuff = table.clone(BaseWeaponTraitBuffTemplates.targets_receive_rending_debuff)
templates.weapon_trait_bespoke_ogryn_club_p2_toughness_recovery_on_multiple_hits = table.clone(BaseWeaponTraitBuffTemplates.toughness_recovery_on_multiple_hits)
templates.weapon_trait_bespoke_ogryn_club_p2_toughness_recovery_on_chained_attacks = table.clone(BaseWeaponTraitBuffTemplates.toughness_recovery_on_chained_attacks)
templates.weapon_trait_bespoke_ogryn_club_p2_staggered_targets_receive_increased_damage_debuff = table.clone(BaseWeaponTraitBuffTemplates.staggered_targets_receive_increased_damage_debuff)
templates.weapon_trait_bespoke_ogryn_club_p2_taunt_target_on_hit = table.clone(BaseWeaponTraitBuffTemplates.taunt_target_on_staggered_hit)
templates.weapon_trait_bespoke_ogryn_club_p2_taunt_target_on_hit_child = table.clone(BaseWeaponTraitBuffTemplates.taunt_target_child)
templates.weapon_trait_bespoke_ogryn_club_p2_taunt_target_on_hit.child_buff_template = "weapon_trait_bespoke_ogryn_club_p2_taunt_target_on_hit_child"
templates.weapon_trait_bespoke_ogryn_club_p2_heavy_chained_hits_increases_killing_blow_chance_parent = table.clone(BaseWeaponTraitBuffTemplates.heavy_chained_hits_increases_killing_blow_chance_parent)
templates.weapon_trait_bespoke_ogryn_club_p2_heavy_chained_hits_increases_killing_blow_chance_parent.child_buff_template = "weapon_trait_bespoke_ogryn_club_p2_heavy_chained_hits_increases_killing_blow_chance_child"
templates.weapon_trait_bespoke_ogryn_club_p2_heavy_chained_hits_increases_killing_blow_chance_child = table.clone(BaseWeaponTraitBuffTemplates.heavy_chained_hits_increases_killing_blow_chance_child)
templates.weapon_trait_bespoke_ogryn_club_p2_increased_crit_chance_on_staggered_weapon_special_hit_parent = table.clone(BaseWeaponTraitBuffTemplates.increased_crit_chance_on_staggered_weapon_special_hit_parent)
templates.weapon_trait_bespoke_ogryn_club_p2_increased_crit_chance_on_staggered_weapon_special_hit_parent.child_buff_template = "weapon_trait_bespoke_ogryn_club_p2_increased_crit_chance_on_staggered_weapon_special_hit_child"
templates.weapon_trait_bespoke_ogryn_club_p2_increased_crit_chance_on_staggered_weapon_special_hit_child = table.clone(BaseWeaponTraitBuffTemplates.increased_crit_chance_on_staggered_weapon_special_hit_child)
templates.weapon_trait_bespoke_ogryn_club_p2_toughness_regen_on_wepon_special_elites = table.clone(BaseWeaponTraitBuffTemplates.toughness_regen_on_wepon_special_elites)

return templates
