-- chunkname: @content/levels/entertainment/black_market/world_item_dep.lua

local item_dependencies = {
	minion_items = {
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_01_b_tattoo_01"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_02_tattoo_01"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_03_tattoo_01"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/hair_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_a"] = 6,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_a_sniper"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/newly_infected_body_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a"] = 4,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a_sniper"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_b"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_01"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_01_b"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_01_c"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/hood_and_goggles_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/longrange_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/melee_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/midrange_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/newly_infected_lowerbody_c"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/newly_infected_upperbody_e"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/special_sniper"] = 1,
	},
	player_items = {
		["content/items/characters/player/eye_colors/eye_color_brown_01"] = 1,
		["content/items/characters/player/human/backpacks/backpack_cadian_a"] = 1,
		["content/items/characters/player/human/backpacks/backpack_cadian_b"] = 1,
		["content/items/characters/player/human/backpacks/backpack_scions_a"] = 1,
		["content/items/characters/player/human/body_tattoo/dirt_tattoo_01_torso"] = 2,
		["content/items/characters/player/human/faces/female_caucasian_face_01"] = 1,
		["content/items/characters/player/human/faces/male_african_face_01"] = 2,
		["content/items/characters/player/human/gear_arms/imperial_guard_upperbody_arms_01"] = 3,
		["content/items/characters/player/human/gear_attachments/atoma_prime_decals_01"] = 1,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_shoulderpad_01_b"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_01"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_f"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_h"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_d"] = 3,
		["content/items/characters/player/human/gear_head/cadian_command_02_a"] = 1,
		["content/items/characters/player/human/gear_head/cadian_command_02_b"] = 1,
		["content/items/characters/player/human/gear_head/catchan_jungd_fighters_01_a"] = 1,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_05"] = 1,
		["content/items/characters/player/human/gear_head/rebreather_01_b"] = 1,
		["content/items/characters/player/human/gear_head/tactical_cap_01_b"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_lowerbody_01"] = 2,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_b"] = 1,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 3,
		["content/items/characters/player/skin_colors/skin_color_african_01"] = 1,
		["content/items/characters/player/skin_colors/skin_color_hispanic_01"] = 1,
	},
	weapon_items = {},
}

return item_dependencies
