-- chunkname: @scripts/settings/equipment/weapon_templates/weapon_categories.lua

local weapon_categories = {
	"grenade",
	"psyker",
	"autogun",
	"ogryn_power_maul",
	"thunder_hammer",
	"shotgun",
	"plasma_rifle",
	"stub_pistol",
	"combat_axe",
	"chain_sword",
	"lasgun",
	"shotgun_grenade",
	"power_sword",
	"ogryn_club",
	"force_sword",
	"force_staff",
	"autopistol",
	"laspistol",
	"rippergun",
	"combat_sword",
	"combat_knife",
	"power_maul",
	"grenadier_gauntlet",
	"combat_blade",
	"ogryn_powermaul_slabshield",
	"bolter",
	"flamer",
	"stub_rifle",
	"ogryn_heavystubbers",
}

return settings("weapon_categories", weapon_categories)
