local item_dependencies = {
	minion_items = {},
	player_items = {
		["content/items/characters/player/human/gear_head/zealot_christmas_headgear_01"] = 1,
		["content/items/characters/player/human/gear_torso/zealot_death_korps_of_krieg_upperbody_a_torso"] = 3,
		["content/items/characters/player/ogryn/face_tattoo/face_tattoo_ogryn_01"] = 3,
		["content/items/characters/player/ogryn/gear_feet/ogryn_death_korps_of_krieg_lowerbody_a_boots"] = 3,
		["content/items/characters/player/ogryn/attachment_base/mannequin_face"] = 1,
		["content/items/characters/player/human/attachment_base/female_arms"] = 3,
		["content/items/characters/player/human/attachment_base/female_mannequin_face"] = 2,
		["content/items/characters/player/human/gear_head/zealot_death_korps_of_krieg_headgear_a"] = 3,
		["content/items/characters/player/human/gear_arms/psyker_death_korps_of_krieg_upperbody_a_arms"] = 1,
		["content/items/characters/player/human/gear_torso/psyker_death_korps_of_krieg_upperbody_a_torso"] = 1,
		["content/items/characters/player/human/gear_hands/zealot_death_korps_of_krieg_upperbody_a_gloves"] = 3,
		["content/items/characters/player/human/gear_arms/zealot_death_korps_of_krieg_upperbody_a_arms"] = 3,
		["content/items/characters/player/human/gear_feet/frateris_militia_shoes_c"] = 3,
		["content/items/characters/player/human/gear_head/imperial_guard_upperbody_a_05_headgear_set_01"] = 1,
		["content/items/characters/player/ogryn/gear_torso/ogryn_death_korps_of_krieg_upperbody_a_torso_01"] = 3,
		["content/items/characters/player/ogryn/gear_head/ogryn_death_korps_of_krieg_headgear_a"] = 3,
		["content/items/characters/player/ogryn/attachment_base/male_face_caucasian"] = 3,
		["content/items/characters/player/ogryn/gear_torso/ogryn_death_korps_of_krieg_upperbody_a_torso_02"] = 3,
		["content/items/characters/player/ogryn/face_hair/ogryn_facial_hair_a_eyebrows"] = 3,
		["content/items/characters/player/ogryn/gear_arms/ogryn_death_korps_of_krieg_upperbody_a_arms"] = 3,
		["content/items/characters/player/human/gear_head/psyker_death_korps_of_krieg_headgear_a"] = 1,
		["content/items/characters/player/human/faces/male_middle_eastern_face_01"] = 1,
		["content/items/characters/player/ogryn/gear_legs/ogryn_death_korps_of_krieg_lowerbody_a_pants"] = 3,
		["content/items/characters/player/human/gear_head/cadian_d_headgear_set_03"] = 1,
		["content/items/characters/player/ogryn/gear_head/ogryn_christmas_headgear_01"] = 1,
		["content/items/characters/player/ogryn/gear_hands/ogryn_death_korps_of_krieg_upperbody_a_gloves"] = 3,
		["content/items/characters/player/human/face_tattoo/face_tattoo_psyker_05"] = 1,
		["content/items/characters/player/human/attachment_base/male_mannequin_face"] = 5,
		["content/items/characters/player/human/gear_head/veteran_christmas_headgear_01"] = 1,
		["content/items/characters/player/human/faces/female_asian_face_02"] = 3,
		["content/items/characters/player/human/gear_head/psyker_christmas_headgear_01"] = 1,
		["content/items/characters/player/human/gear_legs/guardsman_lowerbody_a_pants"] = 3,
		["content/items/characters/player/human/gear_head/imperial_guard_upperbody_a_05_headgear_set_04"] = 2,
		["content/items/characters/player/human/face_hair/female_facial_hair_base"] = 3,
		["content/items/characters/player/human/gear_hands/psyker_death_korps_of_krieg_upperbody_a_gloves"] = 1
	},
	weapon_items = {}
}

return item_dependencies
