-- chunkname: @content/levels/ui/store_presentation_templates/gear_cosmetics_showcase_item_dep.lua

local item_dependencies = {
	minion_items = {},
	player_items = {
		["content/items/characters/player/human/attachment_base/male_mannequin_arms"] = 14,
		["content/items/characters/player/human/attachment_base/male_mannequin_face"] = 20,
		["content/items/characters/player/human/attachment_base/male_mannequin_torso"] = 14,
		["content/items/characters/player/human/backpacks/backpack_greyfax_a_var_03"] = 2,
		["content/items/characters/player/human/backpacks/cadian_c_backpack_set_05"] = 2,
		["content/items/characters/player/human/gear_head/ecclesiarchy_hood_01_necromunda_02_b_var_01"] = 1,
		["content/items/characters/player/human/gear_head/ecclesiarchy_hood_01_necromunda_02_b_var_05"] = 1,
		["content/items/characters/player/human/gear_head/imperial_guard_upperbody_a_05_headgear_set_01"] = 1,
		["content/items/characters/player/human/gear_head/imperial_guard_upperbody_a_05_headgear_set_04"] = 1,
		["content/items/characters/player/human/gear_head/zealot_steel_legion_headgear_a_var_03"] = 2,
		["content/items/characters/player/human/gear_lowerbody/psyker_enforcer_lowerbody_b_var_01"] = 2,
		["content/items/characters/player/human/gear_lowerbody/psyker_tallarn_lowerbody_a_var_03"] = 2,
		["content/items/characters/player/human/gear_lowerbody/veteran_enforcer_lowerbody_a_var_01"] = 2,
		["content/items/characters/player/human/gear_lowerbody/veteran_valhallan_ice_warriors_lowerbody_a_var_03"] = 2,
		["content/items/characters/player/human/gear_lowerbody/zealot_enforcer_lowerbody_a_var_01"] = 2,
		["content/items/characters/player/human/gear_lowerbody/zealot_tallarn_lowerbody_a_var_03"] = 4,
		["content/items/characters/player/human/gear_upperbody/psyker_enforcer_upperbody_a_var_01"] = 2,
		["content/items/characters/player/human/gear_upperbody/psyker_tallarn_desert_rider_upperbody_b_var_03"] = 2,
		["content/items/characters/player/human/gear_upperbody/veteran_enforcer_upperbody_a_var_01"] = 2,
		["content/items/characters/player/human/gear_upperbody/veteran_vallhallan_warriors_upperbody_a_var_03"] = 2,
		["content/items/characters/player/human/gear_upperbody/zealot_enforcer_upperbody_a_var_01"] = 2,
		["content/items/characters/player/human/gear_upperbody/zealot_tallarn_desert_rider_upperbody_a_var_03"] = 4,
		["content/items/characters/player/ogryn/attachment_base/male_face_caucasian"] = 2,
		["content/items/characters/player/ogryn/attachment_base/mannequin_arms"] = 4,
		["content/items/characters/player/ogryn/attachment_base/mannequin_face"] = 10,
		["content/items/characters/player/ogryn/attachment_base/mannequin_torso"] = 4,
		["content/items/characters/player/ogryn/backpacks/ogryn_backpack_02_var_01"] = 2,
		["content/items/characters/player/ogryn/backpacks/ogryn_backpack_06_var_01"] = 2,
		["content/items/characters/player/ogryn/face_hair/ogryn_facial_hair_a_eyebrows"] = 4,
		["content/items/characters/player/ogryn/face_tattoo/face_tattoo_ogryn_01"] = 4,
		["content/items/characters/player/ogryn/gear_head/ogryn_death_korps_of_krieg_headgear_b_var_03"] = 2,
		["content/items/characters/player/ogryn/gear_head/ogryn_j_headgear_set_02"] = 2,
		["content/items/characters/player/ogryn/gear_head/ogryn_j_headgear_set_03"] = 2,
		["content/items/characters/player/ogryn/gear_lowerbody/ogryn_enforcer_lowerbody_a_var_01"] = 2,
		["content/items/characters/player/ogryn/gear_lowerbody/ogryn_imperial_guard_a_lowerbody_set_03"] = 2,
		["content/items/characters/player/ogryn/gear_upperbody/ogryn_enforcer_upperbody_a_var_01"] = 2,
		["content/items/characters/player/ogryn/gear_upperbody/ogryn_steel_legion_upperbody_a_var_03"] = 2,
	},
	weapon_items = {},
}

return item_dependencies
