-- chunkname: @content/levels/tank_foundry/start_cooling/world_item_dep.lua

local item_dependencies = {
	minion_items = {},
	player_items = {
		["content/items/characters/player/human/gear_head/cadian_command_02_b"] = 1,
		["content/items/characters/player/human/attachment_base/male_arms"] = 2,
		["content/items/characters/player/ogryn/attachment_base/male_face_asian_02"] = 1,
		["content/items/characters/player/human/backpacks/backpack_scions_a"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_01"] = 2,
		["content/items/characters/player/human/gear_head/rebreather_01_b"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_f"] = 1,
		["content/items/characters/player/human/gear_arms/imperial_guard_upperbody_arms_01"] = 5,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_shoulderpad_01_b"] = 3,
		["content/items/characters/player/human/faces/male_african_face_01"] = 2,
		["content/items/characters/player/human/gear_feet/frateris_militia_shoes_c"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_d"] = 4,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_05"] = 1,
		["content/items/characters/player/human/gear_torso/npc_upperbody_f"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_b"] = 1,
		["content/items/characters/player/human/gear_head/safety_goggles_a"] = 1,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 5,
		["content/items/characters/player/human/gear_attachments/atoma_prime_decals_01"] = 3,
		["content/items/characters/player/ogryn/gear_feet/ogryn_boots_c"] = 1,
		["content/items/weapons/player/ranged/lasgun_p1_m1"] = 3,
		["content/items/characters/player/human/backpacks/backpack_cadian_a"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_e"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_legs"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_c"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_torso"] = 1,
		["content/items/characters/player/ogryn/face_hair/ogryn_facial_hair_c_mustache"] = 1,
		["content/items/characters/player/human/hair/hair_short_buzzcut_a"] = 1,
		["content/items/characters/player/ogryn/gear_hands/ogryn_gloves_h"] = 1,
		["content/items/characters/player/human/gear_torso/npc_upperbody_f_02"] = 1,
		["content/items/characters/player/ogryn/gear_legs/ogryn_pants_c"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_f"] = 1,
		["content/items/characters/player/human/gear_head/rebreather_01_a"] = 1,
		["content/items/characters/player/ogryn/gear_torso/ogryn_imperial_guard_upperbody_a"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_b"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_05"] = 1,
		["content/items/characters/player/ogryn/gear_torso/ogryn_imperial_guard_upperbody_a_01"] = 1,
		["content/items/characters/player/human/faces/female_asian_face_01"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_arms"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_h"] = 1,
		["content/items/characters/player/human/gear_head/tactical_cap_01_b"] = 1,
		["content/items/characters/player/human/face_hair/facial_hair_a_fullbeard"] = 1,
		["content/items/characters/player/human/gear_head/cadian_command_02_a"] = 1,
		["content/items/weapons/player/ranged/ogryn_rippergun_p1_m1"] = 1,
		["content/items/characters/player/human/gear_head/catchan_jungd_fighters_01_a"] = 1,
		["content/items/characters/player/human/faces/female_caucasian_face_01"] = 1,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_01"] = 1,
		["content/items/characters/player/human/gear_head/genestealer_cults_03_a"] = 1,
		["content/items/characters/player/human/attachment_base/male_torso"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_03"] = 1,
		["content/items/weapons/player/ranged/autogun_p1_m1"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_lowerbody_01"] = 4,
		["content/items/characters/player/human/gear_arms/npc_upperbody_f_arms"] = 1,
		["content/items/characters/player/human/backpacks/backpack_cadian_b"] = 1
	},
	weapon_items = {}
}

return item_dependencies
