local utility_considerations = {}

local function _create_utility_considerations_template_entry(path)
	local utility_considerations_template = require(path)

	for name, utility_consideration in pairs(utility_considerations_template) do
		fassert(not utility_considerations[name], "Trying to add duplicate utility consideration %s!", name)

		utility_considerations[name] = utility_consideration
	end
end

_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/bot_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_deamonhost_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_ogryn_bulwark_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_ogryn_executor_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_ogryn_gunner_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_plague_ogryn_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_poxwalker_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/chaos_poxwalker_bomber_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_captain_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_executor_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_grenadier_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_melee_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_shocktrooper_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_sniper_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/renegade_rifleman_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/cultists_berzerker_utility_considerations")
_create_utility_considerations_template_entry("scripts/extension_systems/behavior/utility_considerations/minion_common_utility_considerations")

return settings("UtilityConsiderations", utility_considerations)
