-- chunkname: @content/levels/cinematics/outro/fail/tank_foundry/generic/world_item_dep.lua

local item_dependencies = {
	minion_items = {
		["content/items/characters/minions/chaos_poxwalker/attachments_base/body"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_01"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_01_b"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_02"] = 3,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_02_b"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_02_b_tattoo_01"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/face_03_b_tattoo_01"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_a"] = 5,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_a_sniper"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_b_elite"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_b_longrange_elite"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_b_melee_elite"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/lowerbody_b_midrange_elite"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a"] = 5,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a_elite"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a_longrange_elite"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a_melee_elite"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_a_sniper"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_base/upperbody_b_midrange_elite"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_decal_01_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_decal_01_b"] = 3,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_decal_01_c"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_helmet_01_decal_d"] = 3,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_longrange_elite_a_decal_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_melee_elite_a_decal_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/chaos_traitor_guard_midrange_elite_a_decal_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/executor_helmet_01_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_01_b"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_01_b_flamer"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_01_d"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_02_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/helmet_02_b"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/hood_and_goggles_a"] = 1,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/longrange_a"] = 3,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/longrange_elite_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/melee_elite_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/midrange_elite_a"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/special_flamethrower"] = 2,
		["content/items/characters/minions/chaos_traitor_guard/attachments_gear/special_sniper"] = 1,
		["content/items/weapons/minions/melee/renegade_executor_weapon"] = 1,
		["content/items/weapons/minions/melee/renegade_melee_weapon_01"] = 1,
		["content/items/weapons/minions/ranged/chaos_traitor_guard_flamer_01"] = 2,
		["content/items/weapons/minions/ranged/chaos_traitor_guard_hellgun_01"] = 1,
		["content/items/weapons/minions/ranged/chaos_traitor_guard_hellgun_backpack"] = 1,
		["content/items/weapons/minions/ranged/chaos_traitor_guard_renegade_lasgun_01"] = 3,
		["content/items/weapons/minions/ranged/renegade_elite_shotgun"] = 1,
		["content/items/weapons/minions/ranged/renegade_sniper_rifle"] = 1,
	},
	player_items = {
		["content/items/characters/player/human/attachment_base/male_arms"] = 4,
		["content/items/characters/player/human/attachment_base/male_legs"] = 4,
		["content/items/characters/player/human/attachment_base/male_torso"] = 4,
		["content/items/characters/player/human/faces/male_caucasian_face_01"] = 4,
		["content/items/characters/player/ogryn/attachment_base/male_arms"] = 4,
		["content/items/characters/player/ogryn/attachment_base/male_face_caucasian"] = 4,
		["content/items/characters/player/ogryn/attachment_base/male_legs"] = 4,
		["content/items/characters/player/ogryn/attachment_base/male_torso"] = 4,
	},
	weapon_items = {},
}

return item_dependencies
