-- chunkname: @scripts/settings/breed/breed_blackboard_component_templates/base_blackboard_component_template.lua

local base_template = {
	spawn = {
		anim_translation_scale_factor = "number",
		game_object_id = "number",
		game_session = "GameSession",
		is_exiting_spawner = "boolean",
		physics_world = "PhysicsWorld",
		spawner_spawn_index = "number",
		spawner_unit = "Unit",
		unit = "Unit",
		world = "World",
	},
	death = {
		attack_direction = "Vector3Box",
		damage_profile_name = "string",
		force_instant_ragdoll = "boolean",
		herding_template_name = "string",
		hit_during_death = "boolean",
		hit_zone_name = "string",
		is_dead = "boolean",
		killing_damage_type = "string",
	},
	stagger = {
		attacker_unit = "Unit",
		controlled_stagger = "boolean",
		controlled_stagger_finished = "boolean",
		count = "number",
		direction = "Vector3Box",
		duration = "number",
		immune_time = "number",
		length = "number",
		num_triggered_staggers = "number",
		stagger_pool_last_modified = "number",
		stagger_strength_multiplier = "number",
		stagger_strength_pool = "number",
		type = "string",
	},
	perception = {
		aggro_state = "string",
		has_good_last_los_position = "boolean",
		has_last_los_position = "boolean",
		has_line_of_sight = "boolean",
		ignore_alerted_los = "boolean",
		last_los_position = "Vector3Box",
		lock_target = "boolean",
		previous_target_unit = "Unit",
		target_changed = "boolean",
		target_changed_t = "number",
		target_distance = "number",
		target_distance_z = "number",
		target_position = "Vector3Box",
		target_speed_away = "number",
		target_unit = "Unit",
	},
	nav_smart_object = {
		entrance_is_at_bot_progress_on_path = "boolean",
		entrance_position = "Vector3Box",
		exit_is_at_the_end_of_path = "boolean",
		exit_position = "Vector3Box",
		id = "number",
		type = "string",
		unit = "Unit",
	},
	disable = {
		attacker_unit = "Unit",
		is_disabled = "boolean",
		type = "string",
	},
}

return base_template
