-- chunkname: @scripts/ui/views/contracts_view/contracts_view_settings.lua

local contracts_view_settings = {
	contract_progress_localization_string_format = "loc_contracts_contract_reward_tasks_completed",
	contract_reward_string_format = "+%d",
	num_tasks_in_list = 8,
	reroll_input_action = "confirm_pressed",
	task_complexity_easy = "loc_contracts_contract_complexity_easy",
	task_complexity_easy_icon = "content/ui/materials/icons/contracts/complexity_easy",
	task_complexity_hard = "loc_contracts_contract_complexity_hard",
	task_complexity_hard_icon = "content/ui/materials/icons/contracts/complexity_hard",
	task_complexity_medium = "loc_contracts_contract_complexity_medium",
	task_complexity_medium_icon = "content/ui/materials/icons/contracts/complexity_medium",
	task_complexity_tutorial = "loc_contracts_contract_complexity_tutorial",
	task_complexity_tutorial_icon = "content/ui/materials/icons/contracts/complexity_tutorial",
	task_description_block_damage = "loc_contracts_task_description_block_damage",
	task_description_collect_pickups = "loc_contracts_task_description_collect_pickups",
	task_description_collect_resources = "loc_contracts_task_description_collect_resources",
	task_description_complete_mission_no_death = "loc_contracts_task_description_complete_mission_no_death",
	task_description_complete_missions = "loc_contracts_task_description_complete_missions",
	task_description_complete_missions_by_name = "loc_contracts_task_description_complete_missions_by_name",
	task_description_kill_bosses = "loc_contracts_task_description_kill_bosses",
	task_description_kill_minions = "loc_contracts_task_description_kill_minions",
	task_fulfilled_check_mark = "",
	task_info_reward_string_format = "+%d",
	task_label_block_damage = "loc_contracts_task_label_block_damage",
	task_label_collect_pickups = "loc_contracts_task_label_collect_pickups",
	task_label_collect_resources = "loc_contracts_task_label_collect_resources",
	task_label_complete_mission_no_death = "loc_contracts_task_label_complete_mission_no_death",
	task_label_complete_missions = "loc_contracts_task_label_complete_missions",
	task_label_complete_missions_by_name = "loc_contracts_task_label_complete_missions_by_name",
	task_label_kill_bosses = "loc_contracts_task_label_kill_bosses",
	task_label_kill_minions = "loc_contracts_task_label_kill_minions",
	task_reward_string_format = "%d",
	wallet_type = "marks",
	task_parameter_strings = {
		cultist = "loc_contract_task_enemy_type_cultist",
		grimoire = "loc_contract_task_pickup_type_grimoire",
		melee = "loc_contract_task_weapon_type_melee",
		ranged = "loc_contract_task_weapon_type_ranged",
		renegade = "loc_contract_task_enemy_type_renegade",
		tome = "loc_contract_task_pickup_type_tome",
		tome_or_grimoire = "loc_contract_task_pickup_type_grimoire_or_tome",
		traitor = "loc_contract_task_enemy_type_traitor",
	},
	vo_event_replacing_task = {
		"contract_vendor_replacing_task",
	},
	vo_event_vendor_greeting = {
		"hub_interact_contract_vendor",
	},
	vo_event_vendor_first_interaction = {
		"npc_first_interaction_contract_vendor_a",
		"npc_first_interaction_contract_vendor_b",
		"npc_first_interaction_contract_vendor_c",
		"npc_first_interaction_contract_vendor_d",
		"npc_first_interaction_contract_vendor_e",
	},
}

return settings("ContractsViewSettings", contracts_view_settings)
