local contracts_view_settings = {
	task_label_kill_bosses = "loc_contracts_task_label_kill_bosses",
	task_description_complete_missions = "loc_contracts_task_description_complete_missions",
	task_label_complete_missions_by_name = "loc_contracts_task_label_complete_missions_by_name",
	task_label_kill_minions = "loc_contracts_task_label_kill_minions",
	reroll_input_action = "secondary_action_pressed",
	contract_reward_string_format = "+%d",
	task_reward_string_format = "+%d",
	task_description_block_damage = "loc_contracts_task_description_block_damage",
	task_description_collect_pickups = "loc_contracts_task_description_collect_pickups",
	task_description_kill_bosses = "loc_contracts_task_description_kill_bosses",
	task_label_collect_pickups = "loc_contracts_task_label_collect_pickups",
	task_complexity_medium = "loc_contracts_contract_complexity_medium",
	task_label_complete_missions = "loc_contracts_task_label_complete_missions",
	task_label_complete_mission_no_death = "loc_contracts_task_label_complete_mission_no_death",
	task_description_complete_missions_by_name = "loc_contracts_task_description_complete_missions_by_name",
	task_label_collect_resources = "loc_contracts_task_label_collect_resources",
	task_complexity_easy = "loc_contracts_contract_complexity_easy",
	task_description_kill_minions = "loc_contracts_task_description_kill_minions",
	task_complexity_tutorial = "loc_contracts_contract_complexity_tutorial",
	task_complexity_easy_icon = "content/ui/materials/icons/contracts/complexity_easy",
	task_info_reward_string_format = "+%d",
	task_complexity_hard_icon = "content/ui/materials/icons/contracts/complexity_hard",
	task_complexity_medium_icon = "content/ui/materials/icons/contracts/complexity_medium",
	task_complexity_tutorial_icon = "content/ui/materials/icons/contracts/complexity_tutorial",
	task_description_collect_resources = "loc_contracts_task_description_collect_resources",
	num_tasks_in_list = 8,
	wallet_type = "marks",
	task_label_block_damage = "loc_contracts_task_label_block_damage",
	task_fulfilled_check_mark = "\ue001",
	task_complexity_hard = "loc_contracts_contract_complexity_hard",
	task_description_complete_mission_no_death = "loc_contracts_task_description_complete_mission_no_death"
}

return settings("ContractsViewSettings", contracts_view_settings)
