-- chunkname: @scripts/settings/havoc/havoc_mutator_local_settings.lua

local havoc_mutator_local_settings = {
	mutator_havoc_enemies_corrupted = {
		breed_chances = {
			chaos_armored_infected = 0.1,
			chaos_beast_of_nurgle = 0,
			chaos_daemonhost = 0.1,
			chaos_hound = 0.1,
			chaos_newly_infected = 0.1,
			chaos_ogryn_bulwark = 0.1,
			chaos_ogryn_executor = 0.1,
			chaos_ogryn_gunner = 0.1,
			chaos_plague_ogryn = 1,
			chaos_poxwalker = 0.1,
			chaos_poxwalker_bomber = 0.1,
			chaos_spawn = 0,
			cultist_assault = 0.1,
			cultist_berzerker = 0.1,
			cultist_flamer = 0.1,
			cultist_grenadier = 0.1,
			cultist_gunner = 0.1,
			cultist_melee = 0.1,
			cultist_mutant = 0.1,
			cultist_shocktrooper = 0.1,
			renegade_assault = 0.1,
			renegade_berzerker = 0.1,
			renegade_captain = 0.2,
			renegade_executor = 0.1,
			renegade_flamer = 0.1,
			renegade_grenadier = 0.1,
			renegade_gunner = 0.1,
			renegade_melee = 0.1,
			renegade_netgunner = 0.1,
			renegade_rifleman = 0.1,
			renegade_shocktrooper = 0.1,
			renegade_sniper = 0.1,
		},
		buff_settings = {
			buff_template_name = "havoc_corrupted_enemies",
			corruption_radius = 3,
			liquid_area_template_name = "havoc_enemy_corruption_liquid",
			node_offset = 0.25,
			rank_multipler = 0.01,
			vfx_name = "content/fx/particles/impacts/flesh/nurgle_corruption_death",
			corruption_color = {
				0.37254901960784315,
				0.6823529411764706,
				0,
			},
		},
	},
	mutator_havoc_enemies_parasite_headshot = {
		breed_chances = {
			chaos_armored_infected = 0.05,
			chaos_beast_of_nurgle = 0,
			chaos_daemonhost = 0,
			chaos_hound = 0,
			chaos_lesser_mutated_poxwalker = 0.1,
			chaos_mutated_poxwalker = 0.1,
			chaos_newly_infected = 0.1,
			chaos_ogryn_bulwark = 0.2,
			chaos_ogryn_executor = 0.2,
			chaos_ogryn_gunner = 1,
			chaos_plague_ogryn = 0,
			chaos_poxwalker = 0.1,
			chaos_poxwalker_bomber = 0,
			chaos_spawn = 0,
			cultist_assault = 0.1,
			cultist_berzerker = 0.1,
			cultist_flamer = 0.1,
			cultist_grenadier = 0.1,
			cultist_gunner = 0.1,
			cultist_melee = 0.1,
			cultist_mutant = 0,
			cultist_shocktrooper = 0.1,
			renegade_assault = 0.1,
			renegade_berzerker = 0.25,
			renegade_captain = 0,
			renegade_executor = 0.05,
			renegade_flamer = 0.05,
			renegade_grenadier = 0.1,
			renegade_gunner = 0.1,
			renegade_melee = 0.1,
			renegade_netgunner = 0,
			renegade_rifleman = 0.1,
			renegade_shocktrooper = 0.1,
			renegade_sniper = 0,
		},
	},
	mutator_encroaching_garden = {
		breed_chances = {
			chaos_armored_infected = 0,
			chaos_beast_of_nurgle = 0,
			chaos_daemonhost = 0.1,
			chaos_hound = 0,
			chaos_newly_infected = 0,
			chaos_ogryn_bulwark = 0.35,
			chaos_ogryn_executor = 0.35,
			chaos_ogryn_gunner = 0.25,
			chaos_plague_ogryn = 0,
			chaos_poxwalker = 0,
			chaos_poxwalker_bomber = 0,
			chaos_spawn = 0,
			cultist_assault = 0,
			cultist_berzerker = 0.25,
			cultist_captain = 1,
			cultist_flamer = 0,
			cultist_grenadier = 0,
			cultist_gunner = 0.25,
			cultist_melee = 0,
			cultist_mutant = 0,
			cultist_shocktrooper = 0.25,
			renegade_assault = 0,
			renegade_berzerker = 0.25,
			renegade_captain = 0.2,
			renegade_executor = 0.25,
			renegade_flamer = 0,
			renegade_grenadier = 0,
			renegade_gunner = 0.25,
			renegade_melee = 0,
			renegade_netgunner = 0,
			renegade_rifleman = 0,
			renegade_shocktrooper = 0.25,
			renegade_sniper = 0,
		},
		buff_settings = {
			healing_frequency = 2,
			healing_radius = 5,
			havoc_encroaching_garden_color = {
				0.5568627450980392,
				0.6313725490196078,
				0.3215686274509804,
			},
			healing_amount_by_armor_type = {
				armored = 950,
				berserker = 950,
				disgustingly_resilient = 1000,
				resistant = 1100,
				super_armor = 800,
				unarmored = 1200,
			},
			stat_buff_settings = {
				impact_modifier = -3,
				max_health_modifier = 100,
				suppressor_decay_multiplier = -3,
			},
		},
	},
	bolstering_minions_01 = {
		breed_chances = {
			chaos_armored_infected = 0.05,
			chaos_beast_of_nurgle = 1,
			chaos_daemonhost = 0.1,
			chaos_hound = 0.35,
			chaos_newly_infected = 0.05,
			chaos_ogryn_bulwark = 0.35,
			chaos_ogryn_executor = 0.35,
			chaos_ogryn_gunner = 0.25,
			chaos_plague_ogryn = 1,
			chaos_poxwalker = 0.05,
			chaos_poxwalker_bomber = 0.35,
			chaos_spawn = 1,
			cultist_assault = 0.1,
			cultist_berzerker = 0.25,
			cultist_captain = 0.2,
			cultist_flamer = 0.35,
			cultist_grenadier = 0.35,
			cultist_gunner = 0.1,
			cultist_melee = 0.1,
			cultist_mutant = 0.35,
			cultist_shocktrooper = 0.25,
			renegade_assault = 0.1,
			renegade_berzerker = 0.25,
			renegade_captain = 0.2,
			renegade_executor = 0.25,
			renegade_flamer = 0.35,
			renegade_grenadier = 0.25,
			renegade_gunner = 0.25,
			renegade_melee = 0.1,
			renegade_netgunner = 0.35,
			renegade_rifleman = 0.1,
			renegade_shocktrooper = 0.25,
			renegade_sniper = 0.35,
		},
		buff_settings = {
			bolstering_multiplier = {
				captain = -0.02,
				default = -0.1,
				elite = -0.05,
				monster = -0.03,
				special = -0.06,
			},
			bolstering_stat_buffs = {
				"unarmored_damage",
				"resistant_damage",
				"disgustingly_resilient_damage",
				"berserker_damage",
				"armored_damage",
				"super_armor_damage",
			},
		},
	},
	mutator_havoc_tougher_skin = {
		breed_chances = {
			chaos_armored_infected = 0,
			chaos_beast_of_nurgle = 0,
			chaos_daemonhost = 0.1,
			chaos_hound = 0.3,
			chaos_newly_infected = 0,
			chaos_ogryn_bulwark = 0.5,
			chaos_ogryn_executor = 0,
			chaos_ogryn_gunner = 0.5,
			chaos_plague_ogryn = 0,
			chaos_poxwalker = 0,
			chaos_poxwalker_bomber = 0.5,
			chaos_spawn = 0,
			cultist_assault = 0.1,
			cultist_berzerker = 0.3,
			cultist_flamer = 0.35,
			cultist_grenadier = 0.35,
			cultist_gunner = 0.5,
			cultist_melee = 0.1,
			cultist_mutant = 0,
			cultist_shocktrooper = 0.25,
			renegade_assault = 0.1,
			renegade_berzerker = 0.25,
			renegade_captain = 0.2,
			renegade_executor = 0.25,
			renegade_flamer = 0.35,
			renegade_grenadier = 0.25,
			renegade_gunner = 0.5,
			renegade_melee = 0.1,
			renegade_netgunner = 0.35,
			renegade_rifleman = 0.1,
			renegade_shocktrooper = 0.25,
			renegade_sniper = 0.35,
		},
	},
	mutator_stimmed_minions = {
		breed_chances = {
			chaos_ogryn_bulwark = 0.3,
			chaos_ogryn_executor = 0.3,
			cultist_assault = 0.5,
			cultist_berzerker = 0.4,
			cultist_captain = 0.2,
			cultist_melee = 0.3,
			cultist_shocktrooper = 0.3,
			renegade_assault = 0.3,
			renegade_berzerker = 0.4,
			renegade_captain = 0.2,
			renegade_executor = 0.3,
			renegade_melee = 0.3,
			renegade_plasma_gunner = 0.3,
			renegade_rifleman = 0.5,
			renegade_shocktrooper = 0.3,
		},
		buff_settings = {
			blue_stimm_settings = {
				hit_mass_multiplier = 2,
				stat_buff_settings = {
					armored_damage = -0.6,
					berserker_damage = -0.6,
					disgustingly_resilient_damage = -0.6,
					resistant_damage = -0.6,
					super_armor_damage = -0.55,
					unarmored_damage = -0.6,
				},
			},
			green_stimm_settings = {
				heal_multipliers = {
					0.5,
					0.6,
					0.7,
					0.8,
					1,
				},
				stat_buff_settings = {
					damage_taken_from_bleeding = -0.5,
					damage_taken_from_burning = -0.5,
					damage_taken_from_electrocution = -0.5,
					impact_modifier = -1,
					warp_damage = -0.5,
				},
			},
			red_stimm_settings = {
				stat_buff_settings = {
					impact_modifier = -2,
					melee_attack_speed = 0.4,
					stagger_duration_multiplier = 0.1,
				},
			},
			yellow_stimm_settings = {
				hit_mass_multiplier = 1.5,
				stat_buff_settings = {
					armored_damage = -0.35,
					berserker_damage = -0.35,
					disgustingly_resilient_damage = -0.35,
					impact_modifier = -0.5,
					melee_attack_speed = 0.3,
					minion_num_shots_modifier = 5,
					ranged_attack_speed = 0.3,
					resistant_damage = -0.35,
					super_armor_damage = -0.35,
					unarmored_damage = -0.35,
					weakspot_damage_taken = 4,
				},
			},
		},
	},
	mutator_havoc_enraged = {
		breed_chances = {
			chaos_armored_infected = 0,
			chaos_beast_of_nurgle = 0,
			chaos_daemonhost = 0.1,
			chaos_hound = 0,
			chaos_newly_infected = 0,
			chaos_ogryn_bulwark = 1,
			chaos_ogryn_executor = 1,
			chaos_ogryn_gunner = 1,
			chaos_plague_ogryn = 0,
			chaos_poxwalker = 0,
			chaos_poxwalker_bomber = 0,
			chaos_spawn = 0,
			cultist_assault = 0,
			cultist_berzerker = 1,
			cultist_captain = 1,
			cultist_flamer = 0,
			cultist_grenadier = 0,
			cultist_gunner = 1,
			cultist_melee = 0,
			cultist_mutant = 0,
			cultist_shocktrooper = 1,
			renegade_assault = 0,
			renegade_berzerker = 1,
			renegade_captain = 1,
			renegade_executor = 1,
			renegade_flamer = 0,
			renegade_grenadier = 0,
			renegade_gunner = 1,
			renegade_melee = 0,
			renegade_netgunner = 0,
			renegade_rifleman = 0,
			renegade_shocktrooper = 1,
			renegade_sniper = 0,
		},
		buff_settings = {
			damage_required_to_trigger = 0.5,
			enraged_buff_template_name = "havoc_enraged_enemies",
			hit_mass_multiplier = 1.5,
			move_variable_override = 1.25,
			sfx_shout = "wwise/events/minions/play_havoc_mutator_enraging_elites_buff_stinger",
			enraged_color = {
				1,
				0,
				0,
			},
			scale = {
				human = 1.1,
				ogryn = 1.2,
			},
			stat_buff_settings = {
				melee_attack_speed = 0.4,
				stagger_duration_multiplier = 0.1,
			},
		},
	},
	mutator_havoc_rotten_armor = {
		breed_chances = {
			chaos_armored_infected = 0,
			chaos_beast_of_nurgle = 0,
			chaos_daemonhost = 0,
			chaos_hound = 0,
			chaos_newly_infected = 0,
			chaos_ogryn_bulwark = 0,
			chaos_ogryn_executor = 1,
			chaos_ogryn_gunner = 0,
			chaos_plague_ogryn = 0,
			chaos_poxwalker = 0,
			chaos_poxwalker_bomber = 0,
			chaos_spawn = 0,
			cultist_assault = 0,
			cultist_berzerker = 0,
			cultist_flamer = 0,
			cultist_grenadier = 0,
			cultist_gunner = 0,
			cultist_melee = 0,
			cultist_mutant = 0,
			cultist_shocktrooper = 0,
			renegade_assault = 0,
			renegade_berzerker = 1,
			renegade_captain = 0,
			renegade_executor = 1,
			renegade_flamer = 0,
			renegade_grenadier = 0,
			renegade_gunner = 0,
			renegade_melee = 0,
			renegade_netgunner = 0,
			renegade_rifleman = 0,
			renegade_shocktrooper = 0,
			renegade_sniper = 0,
		},
		buff_settings = {
			sfx_death_name = "wwise/events/minions/play_nurgle_corpse_explode_rotten",
			vfx_name = "content/fx/particles/enemies/rotten_armor_death",
			damage_thresholds = {
				1,
				0.9,
				0.75,
				0.5,
				0.25,
			},
			damage_reduction_template_names = {
				"havoc_rotten_armor_dr_01",
				"havoc_rotten_armor_dr_02",
				"havoc_rotten_armor_dr_03",
				"havoc_rotten_armor_dr_04",
				"havoc_rotten_armor_dr_05",
			},
		},
	},
	mutator_havoc_chaos_rituals = {
		force_horde_on_spawn = true,
		trigger_distance = 55,
		monster_breed_name = {
			"chaos_mutator_daemonhost",
		},
		num_to_spawn_per_mission = {
			cm_archives = 5,
			cm_habs = 3,
			cm_raid = 5,
			core_research = 4,
			dm_forge = 5,
			dm_propaganda = 5,
			dm_rise = 5,
			dm_stockpile = 5,
			fm_armoury = 5,
			fm_cargo = 5,
			fm_resurgence = 5,
			hm_cartel = 5,
			hm_complex = 5,
			hm_strain = 5,
			km_enforcer = 5,
			km_heresy = 5,
			km_station = 5,
			lm_cooling = 5,
			lm_rails = 5,
			lm_scavenge = 5,
		},
	},
	mutator_havoc_twins_settings = {
		force_horde_on_spawn = true,
		injection_template = "havoc_twins",
		num_to_spawn = 1,
		trigger_distance = 55,
		monster_breed_name = {
			"havoc_twins",
		},
	},
}

return settings("HavocMutatorLocalSettings", havoc_mutator_local_settings)
