-- chunkname: @scripts/settings/player_character/character_creator_presets/character_creator_presets_cryptic.lua

local cryptic_presets = {
	male = {
		preset_1 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_01",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_red_01",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_red_01",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_04",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_steel_01",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_brass_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_01",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_02",
		},
		preset_2 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_02",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_blue_01",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_blue_01",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_01",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_steel_02",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_iron_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_04",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_01",
		},
		preset_3 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_04",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_orange_01",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_orange_01",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_02",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_copper_01",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_copper_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_00",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_03",
		},
		preset_4 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_03",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_orange_01",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_orange_01",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_03",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_copper_01",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_copper_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_03",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_04",
		},
		preset_5 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_02",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_blue_02",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_blue_02",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_03",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_iron_01",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_iron_02",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_02",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_04",
		},
		preset_6 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_03",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_turquoise_01",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_turquoise_01",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_04",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_copper_01",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_primary_color_brass_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_04",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_03",
		},
		preset_7 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_01",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_green_02",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_green_02",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_01",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_steel_02",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_steel_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_01",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_01",
		},
		preset_8 = {
			slot_body_arms = "content/items/characters/player/human/cryptic_base_arms/base_arms_04",
			slot_body_eye_color = "content/items/characters/player/lens_primary_colors/lens_primary_color_blue_01",
			slot_body_eye_color_secondary = "content/items/characters/player/lens_secondary_colors/lens_secondary_color_blue_01",
			slot_body_face = "content/items/characters/player/human/faces/empty_face",
			slot_body_face_hair = "content/items/characters/player/human/face_hair/empty_face_hair",
			slot_body_face_scar = "content/items/characters/player/human/face_scars/empty_face_scar",
			slot_body_face_tattoo = "content/items/characters/player/human/face_tattoo/empty_face_tattoo",
			slot_body_hair = "content/items/characters/player/human/hair/empty_hair",
			slot_body_hair_color = "content/items/characters/player/hair_colors/hair_color_empty",
			slot_body_legs = "content/items/characters/player/human/cryptic_base_legs/base_legs_02",
			slot_body_skin_color = "content/items/characters/player/metal_primary_colors/cryptic_metal_primary_color_iron_01",
			slot_body_skin_color_secondary = "content/items/characters/player/metal_secondary_colors/cryptic_metal_secondary_color_copper_01",
			slot_body_skin_discoloration = "content/items/characters/player/metal_oxidation_level/cryptic_metal_oxidation_level_00",
			slot_body_tattoo = "content/items/characters/player/human/body_tattoo/empty_body_tattoo",
			slot_body_torso = "content/items/characters/player/human/cryptic_base_body/body_02",
		},
	},
}

return cryptic_presets
