local forbidden_words = {
	phrases = {
		[5] = {
			"k k k",
			"s hit"
		},
		[7] = {
			"blow me",
			"bum boy",
			"f u c k",
			"gay sex",
			"girl on",
			"hard on",
			"nig nog",
			"old bag",
			"sod off",
			"suck my",
			"tea bag",
			"tied up",
			"xbl pet"
		},
		[8] = {
			"ass fuck",
			"ass hole",
			"ball gag",
			"big tits",
			"blow job",
			"blow mud",
			"choc ice",
			"cut rope",
			"dick shy",
			"dry hump",
			"dumb ass",
			"fuck off",
			"fuck you",
			"god damn",
			"goo girl",
			"ham flap",
			"hand job",
			"hot carl",
			"huge fat",
			"jack off",
			"jerk off",
			"klu klux",
			"knob end",
			"mr hands",
			"nut sack",
			"piss off",
			"piss pig",
			"red tube",
			"shit ass",
			"strap on",
			"taste my",
			"tit wank",
			"tub girl"
		},
		[9] = {
			"ball sack",
			"batty boy",
			"big black",
			"bin laden",
			"bitch tit",
			"bull shit",
			"bung hole",
			"butt fuck",
			"butt plug",
			"camel toe",
			"cock snot",
			"coon hunt",
			"coon kill",
			"cum freak",
			"cunt hair",
			"date rape",
			"deez nuts",
			"dick head",
			"dick hole",
			"dog style",
			"dp action",
			"fist fuck",
			"fuck hole",
			"gang bang",
			"gassy ass",
			"group sex",
			"hard core",
			"holy shit",
			"hot chick",
			"jail bait",
			"koon hunt",
			"koon kill",
			"muff puff",
			"nob jokey",
			"phone sex",
			"rosy palm",
			"sofa king",
			"wet dream"
		},
		[10] = {
			"baby juice",
			"ball gravy",
			"black cock",
			"booty call",
			"chota bags",
			"corp whore",
			"cotton pic",
			"cotton pik",
			"dio bestia",
			"eat a dick",
			"eat my ass",
			"giant cock",
			"muff diver",
			"nut butter",
			"pissed off",
			"poop chute",
			"pussy fart",
			"strip club"
		},
		[11] = {
			"auto erotic",
			"baby batter",
			"beaver lips",
			"big breasts",
			"bloody hell",
			"blue waffle",
			"bullet vibe",
			"bust a load",
			"chi-chi man",
			"ching chong",
			"clit licker",
			"cock pocket",
			"cock sucker",
			"cum chugger",
			"cum guzzler",
			"deep throat",
			"doggy style",
			"double dong",
			"durka durka",
			"f u c k e r",
			"foot fetish",
			"fuck puppet",
			"fuck trophy",
			"girl on top",
			"how to kill",
			"jelly donut",
			"lemon party",
			"nsfw images",
			"pole smoker",
			"sand nigger",
			"shit fucker",
			"slut bucket",
			"spread legs",
			"style doggy",
			"tea bagging",
			"tight white",
			"tongue in a",
			"two fingers",
			"venus mound",
			"violet wand",
			"white power"
		},
		[12] = {
			"anal impaler",
			"anal leakage",
			"ball kicking",
			"ball licking",
			"ball sucking",
			"barely legal",
			"beef curtain",
			"big knockers",
			"bunny fucker",
			"cum dumpster",
			"doggie style",
			"donkey punch",
			"eat hair pie",
			"flog the log",
			"fuck buttons",
			"fuck yo mama",
			"fudge packer",
			"iberian slap",
			"jungle bunny",
			"ku klux klan",
			"make me come",
			"moon cricket",
			"porch monkey",
			"pussy palace",
			"raging boner",
			"shaved pussy",
			"shirt lifter",
			"sultry women",
			"tainted love",
			"urethra play",
			"wrapping men"
		},
		[13] = {
			"2 girls 1 cup",
			"beef curtains",
			"blonde action",
			"brown showers",
			"clitty litter",
			"clover clamps",
			"coffin dodger",
			"cop some wood",
			"dirty pillows",
			"dirty sanchez",
			"gender bender",
			"golden shower",
			"how to murdep",
			"how to murder",
			"klu klux klan",
			"middle finger",
			"mother fucker",
			"need the dick",
			"piece of shit",
			"porca madonna",
			"sausage queen",
			"shaved beaver",
			"splooge moose",
			"succhia cazzi",
			"suicide girls",
			"window licker"
		},
		[14] = {
			"beaver cleaver",
			"blow your load",
			"carpet muncher",
			"chingada madre",
			"male squirting",
			"menage a trois",
			"mound of venus",
			"pleasure chest",
			"rusty trombone",
			"son of a bitch",
			"son of a whore",
			"testa di cazzo",
			"yellow showers"
		},
		[15] = {
			"brunette action",
			"girls gone wild",
			"madonna puttana",
			"moo moo foo foo",
			"one guy one jar",
			"reverse cowgirl",
			"taking the piss"
		},
		[16] = {
			"alaskan pipeline",
			"bang (one's) box",
			"female squirting"
		},
		[17] = {
			"chick with a dick",
			"cleveland steamer",
			"figlio di puttana",
			"leather restraint",
			"one cup two girls",
			"two girls one cup",
			"wrinkled starfish"
		},
		[18] = {
			"alabama hot pocket",
			"chocolate rosebuds",
			"double penetration"
		},
		[19] = {
			"missionary position"
		},
		[22] = {
			"prince albert piercing"
		},
		[23] = {
			"blonde on blonde action",
			"leather straight jacket",
			"two fingers with tongue"
		},
		[24] = {
			"son of a motherless goat"
		},
		[27] = {
			"rosy palm and her 5 sisters"
		}
	},
	words = {
		[2] = {
			"ho",
			"xx",
			"低能",
			"屠殺",
			"強姦",
			"援交",
			"精薄",
			"輪姦"
		},
		[3] = {
			"8=d",
			"a$$",
			"a2m",
			"a54",
			"a55",
			"ass",
			"azz",
			"bbw",
			"bod",
			"bra",
			"bum",
			"cok",
			"cox",
			"cum",
			"fag",
			"fat",
			"fck",
			"fgt",
			"fku",
			"fuc",
			"fuk",
			"fuq",
			"fux",
			"gae",
			"gai",
			"gey",
			"gfy",
			"git",
			"gyp",
			"hiv",
			"hoe",
			"hun",
			"iap",
			"jap",
			"jiz",
			"kkk",
			"kum",
			"lez",
			"nad",
			"nig",
			"nob",
			"omg",
			"pcp",
			"pee",
			"pms",
			"pot",
			"rum",
			"s&m",
			"s0b",
			"sex",
			"smd",
			"std",
			"t1t",
			"tit",
			"uzi",
			"vag",
			"wad",
			"wog",
			"wop",
			"wtf",
			"xxx",
			"yid",
			"ちんぽ",
			"つんぼ",
			"まんこ",
			"れいぷ",
			"オメコ",
			"チンポ",
			"ツンボ",
			"ニガー",
			"ニグロ",
			"マンコ",
			"レイプ",
			"支那人",
			"精薄者"
		},
		[4] = {
			"1488",
			"2g1c",
			"4r5e",
			"5h1t",
			"5hit",
			"aids",
			"anal",
			"anus",
			"ar5e",
			"arse",
			"b1tc",
			"babe",
			"bamf",
			"bang",
			"barf",
			"bdsm",
			"beer",
			"bint",
			"blad",
			"blow",
			"bomd",
			"bone",
			"bong",
			"boob",
			"btch",
			"bung",
			"butt",
			"c0ck",
			"caca",
			"cawk",
			"chin",
			"cipa",
			"cl1t",
			"cli7",
			"clit",
			"cnut",
			"cock",
			"coon",
			"crap",
			"csam",
			"culo",
			"cums",
			"cun7",
			"cunn",
			"cunt",
			"cvn7",
			"cvnt",
			"cyka",
			"d0ng",
			"d1ck",
			"d1kc",
			"d4go",
			"dago",
			"damn",
			"darn",
			"dick",
			"dikc",
			"dike",
			"dink",
			"dlck",
			"dong",
			"dvda",
			"dyke",
			"f0ck",
			"f0kc",
			"fack",
			"fagg",
			"fags",
			"faig",
			"fart",
			"fckn",
			"fcuk",
			"feck",
			"fick",
			"foad",
			"foah",
			"fock",
			"fokc",
			"fook",
			"fucc",
			"fuck",
			"fuct",
			"fuks",
			"fupa",
			"fvck",
			"fxck",
			"g00k",
			"g0ok",
			"gash",
			"gays",
			"ghay",
			"ghey",
			"go0k",
			"gook",
			"gtfo",
			"guro",
			"h0m0",
			"h0mo",
			"he11",
			"hebe",
			"heeb",
			"hell",
			"hemp",
			"herp",
			"hoar",
			"hoer",
			"hom0",
			"homo",
			"hoor",
			"hor3",
			"hore",
			"hump",
			"hure",
			"japs",
			"jerk",
			"jism",
			"jizm",
			"jizz",
			"jock",
			"joto",
			"k1k3",
			"kawk",
			"kik3",
			"kike",
			"kill",
			"klan",
			"knob",
			"kock",
			"kums",
			"kun7",
			"kunt",
			"kwif",
			"kyke",
			"lech",
			"lmao",
			"loin",
			"lube",
			"lust",
			"m0f0",
			"m0fo",
			"mams",
			"maxi",
			"meth",
			"mick",
			"milf",
			"mof0",
			"mofo",
			"mong",
			"muff",
			"n4z1",
			"nads",
			"naz1",
			"nazi",
			"nazl",
			"nggr",
			"ni6g",
			"nude",
			"oral",
			"orgy",
			"ovum",
			"p0rn",
			"paki",
			"pawn",
			"pedo",
			"phuk",
			"phuq",
			"pimp",
			"piss",
			"poof",
			"poon",
			"poop",
			"porn",
			"prig",
			"prod",
			"pron",
			"pthc",
			"pube",
			"puss",
			"pust",
			"puta",
			"pute",
			"puto",
			"quim",
			"r4p3",
			"racy",
			"raip",
			"rape",
			"rump",
			"scag",
			"scat",
			"scum",
			"seks",
			"sexo",
			"sexy",
			"sh!+",
			"sh!t",
			"sh17",
			"sh1t",
			"shag",
			"shat",
			"shi+",
			"shi7",
			"shit",
			"shiz",
			"shl7",
			"shlt",
			"skag",
			"slag",
			"slut",
			"smeg",
			"smut",
			"spac",
			"spic",
			"spik",
			"stds",
			"stfu",
			"suck",
			"taff",
			"taig",
			"tard",
			"tart",
			"teat",
			"teez",
			"terd",
			"thot",
			"thug",
			"titi",
			"tits",
			"titt",
			"toke",
			"turd",
			"tush",
			"tw47",
			"tw4t",
			"twat",
			"ugly",
			"wang",
			"wank",
			"weed",
			"whiz",
			"womb",
			"yaoi",
			"zubb",
			"сука",
			"あおかん",
			"いんばい",
			"おなにー",
			"きけいじ",
			"きちがい",
			"きんたま",
			"くろんぼ",
			"しなじん",
			"たちんぼ",
			"ちょん公",
			"アオカン",
			"インバイ",
			"オナニー",
			"キケイジ",
			"キチガイ",
			"キンタマ",
			"クロンボ",
			"シナジン",
			"タチンボ",
			"トルコ嬢"
		},
		[5] = {
			"a_s_s",
			"ahole",
			"anuss",
			"aokan",
			"arian",
			"arrse",
			"arsch",
			"arsed",
			"arses",
			"aryan",
			"asses",
			"b!tch",
			"b00bs",
			"b00bz",
			"b17ch",
			"b1tch",
			"babes",
			"baise",
			"balls",
			"bawdy",
			"bi+ch",
			"biach",
			"bimbo",
			"bitch",
			"bladt",
			"blyad",
			"boang",
			"bogan",
			"boink",
			"bon3r",
			"boned",
			"boner",
			"boobs",
			"booby",
			"boong",
			"booty",
			"booze",
			"boozy",
			"bosom",
			"bowel",
			"bunga",
			"busty",
			"cacca",
			"cazzo",
			"ch1nk",
			"chinc",
			"chink",
			"choad",
			"chode",
			"clits",
			"cocks",
			"coons",
			"crabs",
			"crack",
			"cunny",
			"cunts",
			"d1ld0",
			"d1ldo",
			"dagos",
			"deggo",
			"dicks",
			"dildo",
			"dinks",
			"dirsa",
			"dirty",
			"dongs",
			"doosh",
			"dopey",
			"downy",
			"drunk",
			"duche",
			"dummy",
			"dykes",
			"ecchi",
			"erect",
			"f3lch",
			"f4nny",
			"faggs",
			"fagot",
			"faigt",
			"fanny",
			"fanyy",
			"fcuuk",
			"fecal",
			"felch",
			"fisty",
			"flaps",
			"fotze",
			"freex",
			"frigg",
			"fubar",
			"fucka",
			"fucks",
			"fuker",
			"fuuck",
			"fux0r",
			"g000k",
			"ganja",
			"gaydo",
			"gippo",
			"glans",
			"gonad",
			"gooch",
			"gooks",
			"goook",
			"grope",
			"gspot",
			"guido",
			"h1tl3",
			"h1tle",
			"herpy",
			"heshe",
			"hitlr",
			"hoare",
			"hobag",
			"homey",
			"honky",
			"hooch",
			"horny",
			"hussy",
			"hymen",
			"injun",
			"jaggi",
			"joder",
			"juggs",
			"junky",
			"kafir",
			"kikes",
			"kinky",
			"kooch",
			"kraut",
			"kunja",
			"kurva",
			"kurwa",
			"kxkxk",
			"l3sb0",
			"labia",
			"leper",
			"lesbo",
			"lezbo",
			"lezza",
			"lezzy",
			"lmfao",
			"loins",
			"lusty",
			"manko",
			"massa",
			"merda",
			"merde",
			"minge",
			"mo-fo",
			"moron",
			"mutha",
			"n1664",
			"n166a",
			"n1g3r",
			"n1gga",
			"n3gro",
			"n4g3r",
			"nag3r",
			"naked",
			"nappy",
			"natzi",
			"negro",
			"ni666",
			"ni66a",
			"ni66g",
			"ni6g6",
			"ni6gg",
			"nig66",
			"nig6g",
			"nigar",
			"nigg3",
			"nigg6",
			"nigga",
			"niggr",
			"niggy",
			"ninny",
			"niqqa",
			"nonce",
			"nooky",
			"nugga",
			"omeko",
			"opium",
			"organ",
			"ovary",
			"ovums",
			"p3n15",
			"p3n1s",
			"p3ni5",
			"p3nis",
			"p3nl5",
			"p3nls",
			"paddy",
			"pansy",
			"panty",
			"pasty",
			"pen15",
			"pen1s",
			"peni5",
			"penis",
			"penl5",
			"penls",
			"penus",
			"perra",
			"phuck",
			"phuks",
			"pikey",
			"pinko",
			"pizda",
			"polla",
			"porno",
			"porra",
			"potty",
			"pr1ck",
			"prick",
			"prude",
			"pu55y",
			"pub1c",
			"pubes",
			"pubic",
			"pubis",
			"punal",
			"punky",
			"punta",
			"puss1",
			"puss3",
			"puss5",
			"pusse",
			"pussi",
			"pussy",
			"puzzy",
			"pvssy",
			"queaf",
			"queef",
			"queer",
			"raape",
			"raped",
			"raper",
			"rapey",
			"reich",
			"reipu",
			"renob",
			"revue",
			"rtard",
			"ruski",
			"s-o-b",
			"sambo",
			"screw",
			"scrog",
			"scrot",
			"scrud",
			"secks",
			"semen",
			"shite",
			"shits",
			"shitt",
			"shota",
			"sissy",
			"skank",
			"skeet",
			"slave",
			"slope",
			"sluts",
			"snuff",
			"sodom",
			"souse",
			"spade",
			"sperm",
			"spick",
			"spiks",
			"spook",
			"spunk",
			"strip",
			"sucks",
			"taint",
			"teets",
			"teino",
			"teste",
			"tinpo",
			"titty",
			"toots",
			"tramp",
			"tunbo",
			"tushy",
			"twats",
			"twink",
			"twunt",
			"unwed",
			"urine",
			"v1gra",
			"vixen",
			"vodka",
			"vomit",
			"vulva",
			"w00se",
			"wanky",
			"wazoo",
			"wench",
			"wh0r3",
			"wh0re",
			"whoar",
			"whor3",
			"whore",
			"willy",
			"woody",
			"yiffy",
			"yobbo",
			"Блядь",
			"いぬごろし",
			"かわらもの",
			"ちょんこう",
			"ちょんころ",
			"とるこぶろ",
			"にんぴにん",
			"イヌゴロシ",
			"カワラモノ",
			"チョンコウ",
			"チョンコロ",
			"トルコ風呂"
		},
		[6] = {
			"aeolus",
			"anuses",
			"areola",
			"areole",
			"assbag",
			"asshat",
			"assman",
			"asswad",
			"azazel",
			"bampot",
			"banger",
			"beaner",
			"beatch",
			"beater",
			"beaver",
			"beetch",
			"bender",
			"beotch",
			"biatch",
			"bigger",
			"bimbos",
			"biotch",
			"bitchy",
			"bloody",
			"blowme",
			"blyadt",
			"bodily",
			"bohunk",
			"bollok",
			"bollox",
			"boners",
			"booger",
			"bookie",
			"boonga",
			"booobs",
			"bootee",
			"bootie",
			"boozer",
			"bosomy",
			"bowels",
			"breast",
			"buceta",
			"bugger",
			"bummer",
			"cabron",
			"cadela",
			"cagada",
			"cahone",
			"ceemen",
			"cervix",
			"chincs",
			"chinga",
			"chinky",
			"chinpo",
			"choade",
			"chodes",
			"chonga",
			"chonko",
			"climax",
			"clitty",
			"clunge",
			"cocain",
			"coital",
			"coitus",
			"commie",
			"condom",
			"coochy",
			"cooter",
			"crappy",
			"cretin",
			"crikey",
			"crotte",
			"culear",
			"culero",
			"cummer",
			"cummin",
			"cunnie",
			"cunntt",
			"cyalis",
			"d0uch3",
			"d0uche",
			"dammit",
			"damned",
			"damnit",
			"darkie",
			"diddle",
			"dildos",
			"dimwit",
			"dingle",
			"doggin",
			"dommes",
			"doofus",
			"dookie",
			"douch3",
			"douche",
			"downie",
			"dumass",
			"encule",
			"erotic",
			"escort",
			"etambo",
			"etanbo",
			"eunuch",
			"extacy",
			"extasy",
			"facial",
			"fagbag",
			"fagged",
			"faggit",
			"faggot",
			"fagots",
			"fatass",
			"fcuker",
			"fecker",
			"feltch",
			"femdom",
			"fenian",
			"fetish",
			"fisted",
			"flamer",
			"flange",
			"floozy",
			"fondle",
			"foobar",
			"fooker",
			"foutre",
			"frigga",
			"fucked",
			"fucker",
			"fuckin",
			"fuckme",
			"fuckup",
			"fukker",
			"fukkin",
			"fukwit",
			"fuuuck",
			"g-spot",
			"gayass",
			"gaybob",
			"gaysex",
			"gaywad",
			"gigolo",
			"ginger",
			"goatcx",
			"goatse",
			"godamn",
			"goddam",
			"gokkun",
			"gonads",
			"gringo",
			"he-she",
			"hentai",
			"heroin",
			"herpes",
			"hitl3r",
			"hitler",
			"homoey",
			"honkey",
			"hookah",
			"hooker",
			"hootch",
			"hooter",
			"hotsex",
			"humped",
			"inbred",
			"inc3st",
			"incest",
			"j1g4b0",
			"j1g4bo",
			"j1gab0",
			"j1gabo",
			"jagoff",
			"jerked",
			"jig4b0",
			"jig4bo",
			"jigabo",
			"jizzed",
			"junkie",
			"knobed",
			"kondum",
			"kootch",
			"kummer",
			"l3i+ch",
			"l3itch",
			"lesbos",
			"lezbos",
			"lezzie",
			"lolita",
			"looney",
			"menses",
			"midget",
			"mierda",
			"minger",
			"molest",
			"moolie",
			"munter",
			"murder",
			"muther",
			"n1663r",
			"n166er",
			"n1gg3r",
			"n1gger",
			"n4gg3r",
			"nagg3r",
			"nambla",
			"napalm",
			"nazism",
			"ni66er",
			"nigg3r",
			"nigg4h",
			"niggah",
			"niggas",
			"niggaz",
			"nigger",
			"niggle",
			"nigguh",
			"niggur",
			"niglet",
			"nignog",
			"nimrod",
			"nipple",
			"niqqer",
			"nudity",
			"nutted",
			"nutter",
			"nympho",
			"opiate",
			"orally",
			"orgasm",
			"orgies",
			"pantie",
			"pastie",
			"pecker",
			"pedoph",
			"peepee",
			"penial",
			"penile",
			"peyote",
			"phagot",
			"phalli",
			"phuked",
			"pimpis",
			"pinche",
			"pissed",
			"pisser",
			"pisses",
			"pissin",
			"polack",
			"pornos",
			"pricks",
			"psycho",
			"pu555y",
			"pun4ni",
			"pun4nl",
			"punan1",
			"punani",
			"punanl",
			"punany",
			"pusss1",
			"pussse",
			"pusssi",
			"pusssl",
			"pusssy",
			"pussys",
			"putain",
			"queero",
			"queers",
			"quicky",
			"r-tard",
			"r3c7um",
			"r4p15t",
			"r4p1st",
			"r4pi5t",
			"r4pist",
			"raibyo",
			"rap15t",
			"rap1st",
			"rapage",
			"rapi5t",
			"raping",
			"rapist",
			"raunch",
			"rectal",
			"rectum",
			"rectus",
			"reefer",
			"reggin",
			"retard",
			"rimjaw",
			"rimjob",
			"ritard",
			"s.o.b.",
			"sadism",
			"sadist",
			"salaud",
			"salope",
			"sanger",
			"schizo",
			"scroat",
			"scrote",
			"seaman",
			"seamen",
			"seduce",
			"sexual",
			"shited",
			"shitey",
			"shitty",
			"sleaze",
			"sleazy",
			"smegma",
			"smutty",
			"snatch",
			"sniper",
			"sodomy",
			"soused",
			"spooge",
			"steamy",
			"stiffy",
			"stoned",
			"stroke",
			"stupid",
			"sucked",
			"suckmy",
			"tampon",
			"tawdry",
			"teabag",
			"teebag",
			"testee",
			"testes",
			"testis",
			"thrust",
			"tinkle",
			"tities",
			"tosatu",
			"tosser",
			"tranny",
			"trashy",
			"twatty",
			"tyonga",
			"tyonko",
			"undies",
			"urinal",
			"uterus",
			"v14gra",
			"v461n4",
			"v461na",
			"v46in4",
			"v46ina",
			"v4g1n4",
			"v4g1na",
			"v4gin4",
			"v4gina",
			"va-j-j",
			"va61n4",
			"va61na",
			"va6in4",
			"va6ina",
			"vag1n4",
			"vag1na",
			"vagin4",
			"vagina",
			"valium",
			"viagra",
			"virgin",
			"voyeur",
			"vulgar",
			"wanker",
			"wedgie",
			"weenie",
			"weewee",
			"weiner",
			"weirdo",
			"whitey",
			"whored",
			"whores",
			"wigger",
			"x8lp3t",
			"xblpet",
			"xrated",
			"yeasty",
			"かわらこじき",
			"ころしてやる",
			"とるこじょう",
			"はんとうじん",
			"カワラコジキ",
			"コロシテヤル"
		},
		[7] = {
			"a$$hole",
			"a55hole",
			"ainujin",
			"ainuzin",
			"analsex",
			"apeshit",
			"ass-hat",
			"assault",
			"assbang",
			"assbite",
			"asscock",
			"assface",
			"assfuck",
			"assh0le",
			"asshead",
			"assho1e",
			"asshole",
			"asshore",
			"asskiss",
			"asslick",
			"assshit",
			"asswipe",
			"axwound",
			"badfuck",
			"ballbag",
			"banging",
			"barface",
			"bastard",
			"bazooms",
			"beaners",
			"beeatch",
			"beeotch",
			"bellend",
			"bestial",
			"beyitch",
			"beyotch",
			"bigbutt",
			"bigtits",
			"bitched",
			"bitcher",
			"bitches",
			"bitchez",
			"bitchin",
			"blowjob",
			"boiolas",
			"bollick",
			"bollock",
			"bondage",
			"boobies",
			"boooobs",
			"breasts",
			"breeder",
			"buggery",
			"bukakke",
			"bukkake",
			"bumclat",
			"bumfuck",
			"buttman",
			"c-0-c-k",
			"c-o-c-k",
			"c-u-n-t",
			"c.0.c.k",
			"c.u.n.t",
			"camgirl",
			"camslut",
			"caralho",
			"clogwog",
			"cocaine",
			"cockass",
			"cockeye",
			"coituss",
			"cojelon",
			"cojones",
			"coochie",
			"cracker",
			"cripple",
			"cumdump",
			"cumming",
			"cumshot",
			"cumslut",
			"cumtart",
			"cuntass",
			"cuntbag",
			"cuntrag",
			"deeznut",
			"dickbag",
			"dickish",
			"dickwad",
			"dickwod",
			"diligaf",
			"dipship",
			"dipshit",
			"dogging",
			"dolcett",
			"douchey",
			"dumbass",
			"dumshit",
			"erotism",
			"f-u-c-k",
			"f.u.c.k",
			"f_u_c_k",
			"facking",
			"fagging",
			"faggitt",
			"faggots",
			"fagtard",
			"fanculo",
			"fatfuck",
			"fcuking",
			"felcher",
			"fellate",
			"figging",
			"fisting",
			"footjob",
			"fuckass",
			"fuckbag",
			"fuckboy",
			"fuckers",
			"fuckher",
			"fucking",
			"fucknut",
			"fuckoff",
			"fucktoy",
			"fuckwad",
			"fuckwit",
			"fuckyou",
			"fukkers",
			"fukwhit",
			"fuuuuck",
			"fxuxcxk",
			"gayfuck",
			"gaylord",
			"gaytard",
			"gestapo",
			"god-dam",
			"goddamn",
			"hairpie",
			"handjob",
			"hooters",
			"humping",
			"j3rk0ff",
			"jackass",
			"jackoff",
			"jerk0ff",
			"jerkass",
			"jerkoff",
			"jigaboo",
			"kikeiji",
			"kikeizi",
			"kinbaku",
			"kitigai",
			"kluklux",
			"knobead",
			"knobend",
			"kondums",
			"kooches",
			"kumming",
			"kurombo",
			"lameass",
			"lardass",
			"lesbian",
			"lezbian",
			"lezzies",
			"lusting",
			"mafugly",
			"maricon",
			"mulatto",
			"munging",
			"nawashi",
			"neonazi",
			"nig-nog",
			"nigaboo",
			"niggers",
			"nigglet",
			"nipples",
			"nobhead",
			"nutsack",
			"orgasim",
			"orgasms",
			"panooch",
			"panties",
			"pegging",
			"pendejo",
			"phaggot",
			"phallic",
			"phuking",
			"phukked",
			"pissers",
			"pissing",
			"pissoff",
			"pisspig",
			"playboy",
			"pollock",
			"poonani",
			"poonany",
			"preteen",
			"punanny",
			"punkass",
			"pussies",
			"puttana",
			"puttane",
			"raghead",
			"reetard",
			"rimming",
			"rizzape",
			"rompari",
			"rubbish",
			"s-h-1-t",
			"s-h-i-t",
			"s_h_i_t",
			"sandbar",
			"sandler",
			"scheiße",
			"schlong",
			"screwed",
			"scrotum",
			"shagger",
			"shaggin",
			"shemale",
			"shibari",
			"shitass",
			"shitbag",
			"shiting",
			"shitted",
			"shitter",
			"shiznit",
			"sinazin",
			"slutbag",
			"splooge",
			"strapon",
			"suckass",
			"sucking",
			"swinger",
			"t1tt1e5",
			"t1tties",
			"tapatte",
			"tapette",
			"teensex",
			"titfuck",
			"tittie5",
			"titties",
			"titwank",
			"topless",
			"tosatsu",
			"trumped",
			"tubgirl",
			"twinkie",
			"twunter",
			"upskirt",
			"vjayjay",
			"w3tb4ck",
			"w3tback",
			"wankjob",
			"wetb4ck",
			"wetback",
			"whoring",
			"willies",
			"wiseass",
			"x-rated",
			"xl3lpet"
		},
		[8] = {
			"abortion",
			"anushead",
			"anuslick",
			"arsehole",
			"assbangs",
			"assclown",
			"assfaces",
			"assfukka",
			"assholes",
			"assklown",
			"asslover",
			"assmucus",
			"assmunch",
			"assshole",
			"asswhole",
			"asswhore",
			"asswipes",
			"babeland",
			"bakachon",
			"bakatyon",
			"ballsack",
			"bangbros",
			"bareback",
			"barfface",
			"bastardo",
			"bastards",
			"bazongas",
			"beastial",
			"beeyotch",
			"binladen",
			"birdlock",
			"bisexual",
			"bitchass",
			"bitchers",
			"bitching",
			"blowjobs",
			"blumpkin",
			"bollocks",
			"booooobs",
			"buggered",
			"bullcrap",
			"bulldike",
			"bulldyke",
			"bullshit",
			"bunghole",
			"buttbang",
			"buttface",
			"buttfuck",
			"butthead",
			"butthole",
			"buttmuch",
			"buttplug",
			"c.o.c.k.",
			"cameltoe",
			"camwhore",
			"castrate",
			"chankoro",
			"chingado",
			"chingate",
			"chonkoro",
			"clitface",
			"clitfuck",
			"clitoris",
			"clitorus",
			"cockbite",
			"cockface",
			"cockhead",
			"cocklump",
			"cocknose",
			"cockshit",
			"cocksuck",
			"cocksuka",
			"coglione",
			"coglioni",
			"coksucka",
			"coonhunt",
			"coonkill",
			"coonnass",
			"cornhole",
			"creampie",
			"cumshots",
			"cumstain",
			"cuntface",
			"cuntfuck",
			"cunthole",
			"cuntlick",
			"cuntslut",
			"cyberfuc",
			"cybersex",
			"daterape",
			"deeznuts",
			"dick-ish",
			"dickface",
			"dickfuck",
			"dickhead",
			"dickhole",
			"dickmilk",
			"dickslap",
			"dickweed",
			"dillweed",
			"doochbag",
			"dumbcunt",
			"dumbfuck",
			"dumbshit",
			"eatpussy",
			"erection",
			"essohbee",
			"etahinin",
			"fastfuck",
			"felching",
			"fellatio",
			"feltcher",
			"fickdich",
			"fistfuck",
			"footfuck",
			"foreskin",
			"freefuck",
			"frotting",
			"fuck-ass",
			"fuckbutt",
			"fuckedup",
			"fuckface",
			"fuckhead",
			"fuckhole",
			"fuckings",
			"fuckmeat",
			"fucknutt",
			"fucktard",
			"fucktart",
			"fucktwat",
			"fuckwhit",
			"fuckwitt",
			"futanari",
			"fuuuuuck",
			"gangbang",
			"genitals",
			"godamnit",
			"godsdamn",
			"golliwog",
			"gollywog",
			"goodpoop",
			"goregasm",
			"gotohell",
			"hardcore",
			"headfuck",
			"horniest",
			"hotpussy",
			"inculato",
			"jack-off",
			"jackhole",
			"jailbait",
			"jerk-off",
			"jiggaboo",
			"kichigai",
			"kinkster",
			"knobbing",
			"knobhead",
			"koonhunt",
			"koonkill",
			"lesbians",
			"lezbians",
			"ma5terb8",
			"manshaft",
			"masterb8",
			"mcfagget",
			"mitukuti",
			"molester",
			"molestor",
			"n1german",
			"negerman",
			"nggerman",
			"nigerman",
			"nimpinin",
			"ninpinin",
			"nobjocky",
			"nobjokey",
			"numbnuts",
			"omorashi",
			"orgasims",
			"orgasmic",
			"pedobear",
			"phonesex",
			"phukking",
			"piss-off",
			"ponyplay",
			"poontang",
			"retarded",
			"s.h.i.t.",
			"santorum",
			"scantily",
			"schlampe",
			"screwing",
			"shagging",
			"shinajin",
			"shirakko",
			"shitcunt",
			"shitdick",
			"shitface",
			"shitfuck",
			"shitfull",
			"shithead",
			"shithole",
			"shitings",
			"shitters",
			"shittier",
			"shitting",
			"slanteye",
			"slutkiss",
			"smartass",
			"sodomize",
			"sofaking",
			"swastika",
			"tarlouse",
			"testical",
			"testicle",
			"tieokure",
			"torukojo",
			"twathead",
			"twatlips",
			"tyankoro",
			"tyonkoro",
			"tyurenbo",
			"vajayjay",
			"veqtable",
			"vibrator",
			"whorebag",
			"zoophile"
		},
		[9] = {
			"akimekura",
			"analannie",
			"analprobe",
			"anilingus",
			"arschloch",
			"arseholed",
			"arseholes",
			"assbagger",
			"assbandit",
			"assbanged",
			"assbanger",
			"assfucker",
			"assgoblin",
			"asshopper",
			"assjacker",
			"assjockey",
			"asskisser",
			"asslicker",
			"assmaster",
			"assmonkey",
			"assnigger",
			"asspacker",
			"asspirate",
			"assranger",
			"asssucker",
			"auschwitz",
			"barenaked",
			"bastinado",
			"beeeyotch",
			"bi-sexual",
			"bicurious",
			"bitchtits",
			"brassiere",
			"breastjob",
			"breastman",
			"bullshits",
			"bullturds",
			"butchdike",
			"butchdyke",
			"butt-bang",
			"butt-fuck",
			"buttfucka",
			"buttmunch",
			"chesticle",
			"chieokure",
			"chlamydia",
			"chourimbo",
			"chourinbo",
			"chourippo",
			"chuurembo",
			"chuurenbo",
			"cockblock",
			"cocklover",
			"cockmunch",
			"cocksmith",
			"cocksmoke",
			"cocksucer",
			"cocksucks",
			"cocksukka",
			"cottonpic",
			"cottonpik",
			"crackhead",
			"cumbubble",
			"cumjockey",
			"cuntsicle",
			"cyberfuck",
			"dickbrain",
			"dickheads",
			"dickjuice",
			"douchebag",
			"dumbasses",
			"ejaculate",
			"ejakulate",
			"fagfucker",
			"fatfucker",
			"fingering",
			"fistfucks",
			"freakfuck",
			"fuck-tard",
			"fuckbrain",
			"fuckfreak",
			"fuckheads",
			"fuckstick",
			"fucktards",
			"fuckwhore",
			"fuuuuuuck",
			"gang-bang",
			"gangbangs",
			"goddammit",
			"goddamned",
			"goddamnit",
			"golliwogg",
			"hantoujin",
			"hantouzin",
			"holocaust",
			"hurensohn",
			"inugorosi",
			"jackasses",
			"jiggerboo",
			"kilurself",
			"knobjocky",
			"knobjokey",
			"koumoujin",
			"koumouzin",
			"m-fucking",
			"masochist",
			"masterbat",
			"miststück",
			"mothafuck",
			"muffdiver",
			"n1ggerman",
			"n4ggerman",
			"naggerman",
			"niggerman",
			"nyggerman",
			"octopussy",
			"pedophile",
			"penetrate",
			"pigfucker",
			"pissflaps",
			"poopchute",
			"queerbait",
			"queerhole",
			"ricchione",
			"shamedame",
			"shitblimp",
			"shiteater",
			"shitfaced",
			"shitheads",
			"shithouse",
			"shitstain",
			"shittiest",
			"shittings",
			"shrimping",
			"sinheimin",
			"skullfuck",
			"strappado",
			"testicles",
			"threesome",
			"throating",
			"tittyfuck",
			"tittywank",
			"torukozyo",
			"towelhead",
			"tribadism",
			"tyourinbo",
			"tyourippo",
			"urophilia",
			"usigorosi",
			"vaccagare",
			"vatefaire",
			"wh0reface",
			"whoreface",
			"wiseasses",
			"zoophilia"
		},
		[10] = {
			"arseholing",
			"arselicker",
			"ass-fucker",
			"ass-jabber",
			"ass-pirate",
			"assblaster",
			"asscracker",
			"assmuncher",
			"asspuppies",
			"autoerotic",
			"balllicker",
			"bestiality",
			"bigbastard",
			"bloodclaat",
			"booooooobs",
			"bumblefuck",
			"butagorosi",
			"buttcheeks",
			"buttfucker",
			"c0cksucker",
			"chikusatsu",
			"circlejerk",
			"cockburger",
			"cockfucker",
			"cockjockey",
			"cockknoker",
			"cocklicker",
			"cockmaster",
			"cockmonkey",
			"cocknugget",
			"cocksmoker",
			"cocksucked",
			"cocksucker",
			"cockwaffle",
			"cokmuncher",
			"corksucker",
			"crackwhore",
			"cumguzzler",
			"cunilingus",
			"cuntfucker",
			"cunthunter",
			"cuntlicker",
			"cuntsucker",
			"deepthroat",
			"dickdipper",
			"dickfucker",
			"dickmonger",
			"dickripper",
			"dicksipper",
			"dicksucker",
			"dickweasel",
			"dickzipper",
			"dog-fucker",
			"doggystyle",
			"domination",
			"dominatrix",
			"doublelift",
			"douche-fag",
			"douchebags",
			"ejaculated",
			"ejaculates",
			"enjokousai",
			"facefucker",
			"faggotcock",
			"fannyflaps",
			"fingerbang",
			"fingerfuck",
			"fistfucked",
			"fistfucker",
			"fleshflute",
			"footfucker",
			"footlicker",
			"fuck-bitch",
			"fuckbutter",
			"fuckmehard",
			"fuckmonkey",
			"fucknugget",
			"fuuuuuuuck",
			"gangbanged",
			"gayfuckist",
			"god-damned",
			"gonorrehea",
			"hakuroubyo",
			"homoerotic",
			"inugoroshi",
			"kunilingus",
			"lovemaking",
			"m45terbate",
			"ma5terbate",
			"manberries",
			"masterbat3",
			"masterbate",
			"masturbait",
			"masturbare",
			"masturbate",
			"menstruate",
			"mitsukuchi",
			"mothafucka",
			"mothafucks",
			"motherfuck",
			"mthrfucker",
			"muffdiving",
			"nhiggerman",
			"p.u.s.s.y.",
			"paedophile",
			"peckerhead",
			"pedophilia",
			"perversion",
			"polesmoker",
			"poopuncher",
			"prostitute",
			"puttaniere",
			"rumprammer",
			"sandnigger",
			"sangokujin",
			"sangokuzin",
			"schwuchtel",
			"scissoring",
			"seishinijo",
			"seisinizyo",
			"shinheimin",
			"shitbagger",
			"shitbrains",
			"shitbreath",
			"shitcanned",
			"slutdumper",
			"smartasses",
			"spanishick",
			"spanishook",
			"spanishunk",
			"teabagging",
			"torukoburo",
			"twatwaffle",
			"undressing",
			"vaffanculo",
			"whitepower",
			"whorehouse",
			"xblrewards",
			"yabunirami",
			"zipperhead"
		},
		[11] = {
			"beardedclam",
			"beastiality",
			"beefwhistle",
			"breastlover",
			"bullshitted",
			"butt-fucker",
			"butt-pirate",
			"buttmuncher",
			"cameljockey",
			"clusterfuck",
			"cock-sucker",
			"cockholster",
			"cockknocker",
			"cockmongler",
			"cockmuncher",
			"cocksniffer",
			"cocksuckers",
			"cocksucking",
			"coprolagnia",
			"coprophilia",
			"crack-whore",
			"cumdumpster",
			"cunillingus",
			"cunnilingus",
			"cunt-struck",
			"cuntlicking",
			"cyberfucked",
			"cyberfucker",
			"dick-sneeze",
			"dickbeaters",
			"dickflipper",
			"dicksucking",
			"dicktickler",
			"dickwhipper",
			"dingleberry",
			"doggiestyle",
			"doggy-style",
			"donkeypunch",
			"ejaculating",
			"ejaculation",
			"enlargement",
			"enzyokousai",
			"fannybandit",
			"fannyfucker",
			"fartknocker",
			"fingerfucks",
			"fistfuckers",
			"fistfucking",
			"fudgepacker",
			"fujinoyamai",
			"fuuuuuuuuck",
			"fuuuuuuuuuu",
			"hakujakusha",
			"hardcoresex",
			"huzinoyamai",
			"intercourse",
			"junglebunny",
			"m07th3rfukr",
			"m0th3rfvk3r",
			"m0th3rfvker",
			"master-bate",
			"moth3rfucer",
			"moth3rfvk3r",
			"moth3rfvker",
			"mothafuckas",
			"mothafuckaz",
			"mothafucked",
			"mothafucker",
			"mothafuckin",
			"motherfucka",
			"motherfucks",
			"mtherfucker",
			"mthrfucking",
			"muthafecker",
			"muthafuckaz",
			"nimphomania",
			"nymphomania",
			"pedophiliac",
			"penetration",
			"penisbanger",
			"penisfucker",
			"penispuffer",
			"pillowbiter",
			"porchmonkey",
			"pornography",
			"prickteaser",
			"semusiotoko",
			"shitspitter",
			"snowballing",
			"thundercunt",
			"tittyfucker",
			"transsexual",
			"unclefucker",
			"ushigoroshi",
			"vvhitepower",
			"whorehopper"
		},
		[12] = {
			"beatyourmeat",
			"child-fucker",
			"cockmongruel",
			"cyberfuckers",
			"cyberfucking",
			"dawgie-style",
			"dendrophilia",
			"doggie-style",
			"donkeyribber",
			"douchewaffle",
			"ejaculatings",
			"fingerfucked",
			"fingerfucker",
			"fistfuckings",
			"freakyfucker",
			"fuckersucker",
			"fuckingbitch",
			"fudge-packer",
			"fukashokumin",
			"fuuuuuuuuuck",
			"goldenshower",
			"hakuzyakusya",
			"homodumbshit",
			"hukasyokumin",
			"masterbating",
			"masterbation",
			"masturbacion",
			"masturbating",
			"masturbation",
			"menstruation",
			"mothafuckers",
			"mothafucking",
			"motherfucked",
			"motherfucker",
			"motherfuckin",
			"motherfuckka",
			"muthafuckker",
			"mutherfucker",
			"muthrfucking",
			"pussylicking",
			"pussypounder",
			"semushiotoko",
			"sumofabiatch",
			"tittiefucker",
			"vorarephilia",
			"whoralicious"
		},
		[13] = {
			"brotherfucker",
			"carpetmuncher",
			"dingleberries",
			"fingerfuckers",
			"fingerfucking",
			"goldenshowers",
			"koroshiteyaru",
			"masterbations",
			"masturbazione",
			"mothafuckings",
			"motherfuckers",
			"motherfucking",
			"mutherfucking",
			"tokushugakkyu",
			"tokusyugakkyu",
			"whorealicious"
		},
		[14] = {
			"motherfuckings",
			"son-of-a-bitch"
		},
		[15] = {
			"seishinhakujaku",
			"seisinhakuzyaku",
			"syokubutuningen"
		},
		[16] = {
			"shokubutsuningen"
		},
		[18] = {
			"goddamnmuthafucker"
		},
		[23] = {
			"fuckingshitmotherfucker"
		}
	}
}

return forbidden_words
