-- chunkname: @content/levels/entertainment/cellar/world_item_dep.lua

local item_dependencies = {
	minion_items = {
		["content/items/characters/minions/chaos_poxwalker/attachments_base/body"] = 2,
		["content/items/characters/minions/chaos_poxwalker/attachments_base/body_skin_02"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_base/body_skin_03"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_base/hair_b"] = 2,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/fullbody_a"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_arm_left_01"] = 3,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_head_03"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_head_04"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_torso_03"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/lowerbody_a"] = 3,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/upperbody_a"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/upperbody_b"] = 1,
	},
	player_items = {
		["content/items/characters/player/eye_colors/eye_color_blind_both"] = 1,
		["content/items/characters/player/eye_colors/eye_color_brown_01_blind_right"] = 2,
		["content/items/characters/player/hair_colors/hair_color_gray_03"] = 2,
		["content/items/characters/player/human/attachment_base/female_arms"] = 1,
		["content/items/characters/player/human/attachment_base/male_arms"] = 2,
		["content/items/characters/player/human/body_tattoo/dirt_tattoo_01_torso"] = 4,
		["content/items/characters/player/human/faces/female_caucasian_face_02"] = 1,
		["content/items/characters/player/human/faces/male_asian_face_01"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_01"] = 2,
		["content/items/characters/player/human/gear_arms/imperial_guard_upperbody_arms_01"] = 4,
		["content/items/characters/player/human/gear_attachments/atoma_prime_decals_01"] = 3,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_shoulderpad_01_b"] = 3,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_01"] = 3,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_g"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_c"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_e"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_f"] = 2,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_03"] = 1,
		["content/items/characters/player/human/gear_head/rebreather_01_b"] = 4,
		["content/items/characters/player/human/gear_head/tactical_cap_01_a"] = 1,
		["content/items/characters/player/human/gear_head/tactical_cap_01_b"] = 2,
		["content/items/characters/player/human/gear_legs/imperial_guard_lowerbody_01"] = 3,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_c"] = 1,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 4,
		["content/items/characters/player/skin_colors/skin_color_african_01"] = 1,
	},
	weapon_items = {},
}

return item_dependencies
