-- chunkname: @scripts/settings/expeditions/settings_templates/wastes_expedition_template.lua

local BaseExpeditionTemplate = require("scripts/settings/expeditions/settings_templates/base_expedition_template")
local base_settings = table.clone_instance(BaseExpeditionTemplate)
local overrides = {
	name = "wastes",
	events = {},
	theme_tags = {
		"default",
	},
	location_levels = {
		"content/levels/expeditions/locations/wastes/location_256m_chasm_002/missions/mission_location_256m_chasm_002",
		"content/levels/expeditions/locations/wastes/location_256m_colony_001/missions/mission_location_256m_colony_001",
		"content/levels/expeditions/locations/wastes/location_256m_colony_002/missions/mission_location_256m_colony_002",
		"content/levels/expeditions/locations/wastes/location_256m_colony_003/missions/mission_location_256m_colony_003",
		"content/levels/expeditions/locations/wastes/location_256m_ravine_001/missions/mission_location_256m_ravine_001",
		"content/levels/expeditions/locations/wastes/location_256m_underpass_002/missions/mission_location_256m_underpass_002",
	},
	safe_zone_levels = {
		"content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_001/missions/mission_sz_cave_tunnels_001",
		"content/levels/expeditions/safe_zones/wastes/sz_cave_tunnels_002/missions/mission_sz_cave_tunnels_002",
		"content/levels/expeditions/safe_zones/wastes/sz_stronghold_ruin_002/missions/mission_sz_stronghold_ruin_002",
	},
	allowed_dsl_levels = {
		"content/levels/expeditions/opportunities/wastes/op_16m_hack_chest_002/world",
		"content/levels/expeditions/opportunities/wastes/op_16m_simple_puzzle_001/world",
		"content/levels/expeditions/opportunities/wastes/op_16m_simple_puzzle_002/world",
		"content/levels/expeditions/opportunities/wastes/op_16m_stash_001/world",
		"content/levels/expeditions/opportunities/wastes/op_16m_stash_002/world",
		"content/levels/expeditions/opportunities/wastes/op_16m_stash_003/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_arvus_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_camp_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_capture_zone_002/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_capture_zone_003/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_capture_zone_004/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_encampment_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_enclosure_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_lot_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_pit_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_hack_chest_002/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_hack_chest_003/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_jumping_puzzle_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_luggable_building_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_luggable_building_002/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_luggable_building_003/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_mound_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_vault_001/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_vault_003/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_capture_zone_002/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_fort_generator_001/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_fort_generator_002/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_hack_catwalks_001/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_jumping_puzzle_002/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_jumping_puzzle_004/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_luggable_building_002/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_valkyrie_rocks_001/world",
		"content/levels/expeditions/opportunities/wastes/op_64m_mining_001/world",
		"content/levels/expeditions/opportunities/wastes/op_64m_mining_002/world",
		"content/levels/expeditions/opportunities/wastes/op_64m_mining_003/world",
		"content/levels/expeditions/opportunities/wastes/op_64m_spheres_002/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_luggable_building_001_var_hack/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_vault_003_var_cap/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_luggable_building_003_var_cap/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_fort_generator_001_var_cap/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_luggable_building_002_var_cap/world",
		"content/levels/expeditions/opportunities/wastes/op_64m_mining_001_var_hack/world",
		"content/levels/expeditions/opportunities/wastes/op_32m_hack_chest_002_var_cap/world",
		"content/levels/expeditions/opportunities/wastes/op_48m_luggable_building_002_var_hack/world",
		"content/levels/expeditions/opportunities/wastes/op_64m_mining_002_var_cap/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_drop_pod_001/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_flat_001/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_flat_002/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_flat_003/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_flat_004/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_flat_005/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_flat_006/world",
		"content/levels/expeditions/traversal/wastes/tr_16m_sphere_001/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_conceal_001/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_flat_001/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_flat_002/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_flat_003/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_flat_004/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_mining_001/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_plaza_001/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_plaza_002/world",
		"content/levels/expeditions/traversal/wastes/tr_32m_plaza_003/world",
		"content/levels/expeditions/traversal/wastes/tr_48m_encampment_001/world",
		"content/levels/expeditions/traversal/wastes/tr_48m_encampment_002/world",
		"content/levels/expeditions/traversal/wastes/tr_48m_encampment_003/world",
		"content/levels/expeditions/traversal/wastes/tr_48m_mining_001/world",
		"content/levels/expeditions/traversal/wastes/tr_48m_plot_001/world",
		"content/levels/expeditions/traversal/wastes/tr_48m_flat_001/world",
		"content/levels/expeditions/traversal/wastes/tr_64m_mining_001/world",
		"content/levels/expeditions/traversal/wastes/tr_64m_flat_001/world",
		"content/levels/expeditions/traversal/wastes/tr_64m_flat_002/world",
		"content/levels/expeditions/traversal/wastes/tr_64m_flat_003/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_destroyed_001/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_destroyed_002/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_disabled_001/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_disabled_002/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_makeshift_001/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_makeshift_002/world",
		"content/levels/expeditions/zone_transitions/wastes/zt_16m_airlock_makeshift_003/world",
		"content/levels/expeditions/arrivals/wastes/arr_32m_valkyrie_rocks_001/world",
		"content/levels/expeditions/extractions/wastes/ext_32m_valkyrie_rocks_001/world",
		"content/levels/expeditions/extractions/wastes/ext_48m_valkyrie_pad_001/world",
		"content/levels/expeditions/interactables/secondary_pickup_spawner_01/world",
	},
}

return table.merge(base_settings, overrides)
