-- chunkname: @scripts/settings/wwise_game_sync/wwise_game_sync_settings.lua

local wwise_game_sync_settings = {
	ambush_horde_trigger_distance = 80,
	boss_trigger_distance = 80,
	combat_state_horde_high_minimum_aggroed_minions = 10,
	combat_state_horde_low_minimum_aggroed_minions = 5,
	default_group_state = "None",
	music_state_reset_time = 2,
	vector_horde_trigger_distance = 80,
	minion_aggro_intensity_settings = {
		num_threshold_high = 16,
		num_threshold_low = 4,
		num_threshold_medium = 8,
		query_radius = 30,
	},
	state_groups = {
		music_game_state = {
			character_creation = "character_creation",
			cinematic = "cinematic",
			credits = "credits",
			defeat = "defeat",
			game_score = "game_score",
			game_score_lose = "game_score_lose",
			game_score_win = "game_score_win",
			game_start = "game_start",
			loading = "loading",
			loadout = "loadout",
			loadout_ready = "loadout_ready",
			main_menu = "main_menu",
			mission = "mission",
			mission_board = "mission_board",
			mission_briefing = "mission_briefing",
			mission_intro = "mission_intro",
			mission_loading = "mission_loading",
			mission_outro = "mission_outro",
			mission_ready = "mission_ready",
			mission_start = "mission_start",
			none = "None",
			title = "title",
			victory = "victory",
		},
		music_zone = {
			hub = "hub",
			none = "None",
			prologue = "prologue",
			zone_1 = "zone_1",
			zone_2 = "zone_2",
			zone_3 = "zone_3",
			zone_4 = "zone_4",
			zone_5 = "zone_5",
			zone_6 = "zone_6",
			zone_7 = "zone_7",
		},
		music_combat = {
			boss = "boss",
			horde_high = "horde_high",
			horde_low = "horde_low",
			none = "None",
			normal = "normal",
		},
		music_objective = {
			collect_event = "collect_event",
			control_event = "control_event",
			demolition_event = "demolition_event",
			escape_event = "escape_event",
			fortification_event = "fortification_event",
			hacking_event = "hacking_event",
			kill_event = "kill_event",
			last_man_standing = "last_man_standing",
			none = "None",
			prologue_combat = "prologue_combat",
		},
		music_objective_progression = {
			none = "None",
			one = "one",
			three = "three",
			two = "two",
		},
		music_circumstance = {
			none = "None",
		},
		options = {
			appearance_menu = "appearance_menu",
			credit_store_menu = "credit_store_menu",
			credits = "credits",
			ingame_menu = "ingame_menu",
			none = "None",
			story_mission_menu = "story_mission_menu",
			vendor_menu = "vendor_menu",
		},
		minion_aggro_intensity = {
			high = "high",
			low = "low",
			medium = "medium",
			none = "None",
		},
		event_intensity = {
			high = "high",
			low = "low",
			none = "None",
		},
	},
}

return settings("WwiseGameSyncSettings", wwise_game_sync_settings)
