local BOSS_PATROLS = {
	name = "renegade_boss_patrols",
	resistance_templates = {
		{
			{
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper"
			},
			{
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman"
			},
			{
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee"
			}
		},
		{
			{
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper"
			},
			{
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman"
			},
			{
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee"
			}
		},
		{
			{
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper"
			},
			{
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner"
			},
			{
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor"
			}
		},
		{
			{
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper"
			},
			{
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner"
			},
			{
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor"
			}
		},
		{
			{
				"chaos_ogryn_bulwark",
				"renegade_shocktrooper",
				"renegade_shocktrooper",
				"renegade_shocktrooper",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_assault",
				"renegade_shocktrooper",
				"renegade_shocktrooper",
				"renegade_shocktrooper",
				"chaos_ogryn_bulwark"
			},
			{
				"chaos_ogryn_bulwark",
				"renegade_gunner",
				"renegade_gunner",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_rifleman",
				"renegade_rifleman",
				"renegade_gunner",
				"renegade_gunner",
				"renegade_gunner",
				"chaos_ogryn_gunner"
			},
			{
				"chaos_ogryn_executor",
				"renegade_executor",
				"renegade_executor",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_melee",
				"renegade_melee",
				"renegade_executor",
				"renegade_executor",
				"renegade_executor",
				"chaos_ogryn_executor"
			}
		}
	}
}

return BOSS_PATROLS
