-- chunkname: @scripts/settings/dialogue/dialogue_speaker_voice_settings.lua

local dialogue_speaker_voice_settings = {
	veteran_male_a = {
		full_name = "loc_character_class_veteran",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_female_a = {
		full_name = "loc_character_class_veteran",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_male_b = {
		full_name = "loc_character_class_veteran",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_female_b = {
		full_name = "loc_character_class_veteran",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_male_c = {
		full_name = "loc_character_class_veteran",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_female_c = {
		full_name = "loc_character_class_veteran",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	zealot_male_a = {
		full_name = "loc_character_class_zealot",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_female_a = {
		full_name = "loc_character_class_zealot",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_male_b = {
		full_name = "loc_character_class_zealot",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_female_b = {
		full_name = "loc_character_class_zealot",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_male_c = {
		full_name = "loc_character_class_zealot",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_female_c = {
		full_name = "loc_character_class_zealot",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	psyker_male_a = {
		full_name = "loc_character_class_psyker",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_female_a = {
		full_name = "loc_character_class_psyker",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_male_b = {
		full_name = "loc_character_class_psyker",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_female_b = {
		full_name = "loc_character_class_psyker",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_male_c = {
		full_name = "loc_character_class_psyker",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_female_c = {
		full_name = "loc_character_class_psyker",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	ogryn_a = {
		full_name = "loc_character_class_ogryn",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	ogryn_b = {
		full_name = "loc_character_class_ogryn",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	ogryn_c = {
		full_name = "loc_character_class_ogryn",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	ogryn_d = {
		full_name = "loc_character_class_ogryn",
		icon = nil,
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	adamant_male_a = {
		full_name = "loc_class_adamant_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_adamant_name",
		subtitles_enabled = true,
	},
	adamant_male_b = {
		full_name = "loc_class_adamant_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_adamant_name",
		subtitles_enabled = true,
	},
	adamant_male_c = {
		full_name = "loc_class_adamant_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_adamant_name",
		subtitles_enabled = true,
	},
	adamant_female_a = {
		full_name = "loc_class_adamant_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_adamant_name",
		subtitles_enabled = true,
	},
	adamant_female_b = {
		full_name = "loc_class_adamant_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_adamant_name",
		subtitles_enabled = true,
	},
	adamant_female_c = {
		full_name = "loc_class_adamant_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_adamant_name",
		subtitles_enabled = true,
	},
	adamant_officer_a = {
		full_name = "loc_npc_full_name_adamant_officer_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/procter_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/procter_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_adamant_officer_a",
		subtitles_enabled = true,
	},
	broker_male_a = {
		full_name = "loc_class_broker_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_broker_name",
		subtitles_enabled = true,
	},
	broker_male_b = {
		full_name = "loc_class_broker_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_broker_name",
		subtitles_enabled = true,
	},
	broker_male_c = {
		full_name = "loc_class_broker_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_broker_name",
		subtitles_enabled = true,
	},
	broker_female_a = {
		full_name = "loc_class_broker_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_broker_name",
		subtitles_enabled = true,
	},
	broker_female_b = {
		full_name = "loc_class_broker_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_broker_name",
		subtitles_enabled = true,
	},
	broker_female_c = {
		full_name = "loc_class_broker_name",
		icon = nil,
		player_voice = true,
		short_name = "loc_class_broker_name",
		subtitles_enabled = true,
	},
	sergeant_a = {
		full_name = "loc_npc_full_name_sergeant_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sergeant_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sergeant_a_small",
		player_voice = true,
		short_name = "loc_npc_short_name_sergeant_a",
		subtitles_enabled = true,
	},
	sergeant_b = {
		full_name = "loc_npc_full_name_sergeant_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sergeant_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sergeant_a_small",
		player_voice = true,
		short_name = "loc_npc_short_name_sergeant_a",
		subtitles_enabled = true,
	},
	sergeant_c = {
		full_name = "loc_npc_full_name_sergeant_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sergeant_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sergeant_a_small",
		player_voice = true,
		short_name = "loc_npc_short_name_sergeant_a",
		subtitles_enabled = true,
	},
	pilot_a = {
		full_name = "loc_npc_full_name_pilot_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/pilot_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/pilot_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_pilot_a",
		subtitles_enabled = true,
	},
	purser_a = {
		full_name = "loc_npc_full_name_purser_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/alice_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/alice_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_purser_a",
		subtitles_enabled = true,
	},
	explicator_a = {
		full_name = "loc_npc_full_name_explicator_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/explicator_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/explicator_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_explicator_a",
		subtitles_enabled = true,
	},
	tank_commander_a = {
		full_name = "loc_npc_full_name_tank_commander_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/tank_commander_a",
		player_voice = false,
		short_name = "loc_npc_short_name_tank_commander_a",
		subtitles_enabled = true,
	},
	traitor_gunner_a = {
		full_name = "loc_breed_display_name_renegade_gunner",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_breed_display_name_renegade_gunner",
		subtitles_enabled = true,
	},
	tech_priest_a = {
		full_name = "loc_npc_full_name_tech_priest_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/tech_priest_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/tech_priest_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_tech_priest_a",
		subtitles_enabled = true,
	},
	tech_priest_b = {
		full_name = "loc_npc_full_name_tech_priest_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/tech_priest_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/tech_priest_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_tech_priest_a",
		subtitles_enabled = true,
	},
	training_ground_psyker_a = {
		full_name = "loc_npc_full_name_training_ground_psyker_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sefoni_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sefoni_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_training_ground_psyker_a",
		subtitles_enabled = true,
	},
	interrogator_a = {
		full_name = "loc_npc_full_name_interrogator_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/rannick_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/rannick_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_interrogator_a",
		subtitles_enabled = true,
	},
	shipmistress_a = {
		full_name = "loc_npc_full_name_shipmistress_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/brahms_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/brahms_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_shipmistress_a",
		subtitles_enabled = true,
	},
	vocator_a = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	vocator_b = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_confessor_a = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_wing_commander_a = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_a = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_b = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_c = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_d = {
		full_name = "loc_npc_full_name_vocator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	contract_vendor_a = {
		full_name = "loc_npc_full_name_contract_vendor_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/melk_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/melk_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_contract_vendor_a",
		subtitles_enabled = true,
	},
	credit_store_servitor_a = {
		full_name = "loc_npc_full_name_credit_store_servitor_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_credit_store_servitor_b",
		subtitles_enabled = true,
	},
	credit_store_servitor_b = {
		full_name = "loc_npc_full_name_credit_store_servitor_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_credit_store_servitor_a",
		subtitles_enabled = true,
	},
	credit_store_servitor_c = {
		full_name = "loc_npc_full_name_credit_store_servitor_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_credit_store_servitor_c",
		subtitles_enabled = true,
	},
	enemy_cultist_herald_a = {
		full_name = "loc_npc_full_name_enemy_cultist_herald_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_herald_a",
		subtitles_enabled = false,
	},
	enemy_rogue_psyker_a = {
		full_name = "loc_npc_full_name_enemy_rogue_psyker_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_rogue_psyker_a",
		subtitles_enabled = false,
	},
	enemy_traitor_lieutenant_a = {
		full_name = "loc_npc_full_name_enemy_traitor_lieutenant_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_traitor_lieutenant_a",
		subtitles_enabled = false,
	},
	enemy_traitor_enforcer_executor_a = {
		full_name = "loc_npc_full_name_enemy_traitor_enforcer_executor_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_traitor_enforcer_executor_a",
		subtitles_enabled = false,
	},
	prison_guard_a = {
		full_name = "loc_npc_full_name_prison_guard_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_prison_guard_a",
		subtitles_enabled = true,
	},
	enemy_nemesis_wolfer_a = {
		full_name = "loc_npc_full_name_enemy_nemesis_wolfer_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/wolfer_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_nemesis_wolfer_a",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_a = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_01",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_a",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_b = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_b",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_02",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_b",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_c = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_01",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_a",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_d = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_b",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_02",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_b",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_e = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_02",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_a",
		subtitles_enabled = true,
	},
	enemy_cultist_flamer_a = {
		full_name = "loc_npc_full_name_enemy_cultist_flamer",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_flamer",
		subtitles_enabled = false,
	},
	enemy_cultist_melee_fighter_a = {
		full_name = "loc_npc_full_name_enemy_cultist_melee_fighter",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_melee_fighter",
		subtitles_enabled = false,
	},
	enemy_cultist_melee_fighter_b = {
		full_name = "loc_npc_full_name_enemy_cultist_melee_fighter",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_melee_fighter",
		subtitles_enabled = false,
	},
	enemy_cultist_rusher_male_a = {
		full_name = "loc_npc_full_name_enemy_cultist_rusher",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_rusher",
		subtitles_enabled = false,
	},
	enemy_cultist_rusher_male_b = {
		full_name = "loc_npc_full_name_enemy_cultist_rusher",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_rusher",
		subtitles_enabled = false,
	},
	enemy_daemonhost_a = {
		full_name = "loc_npc_full_name_enemy_daemonhost_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_daemonhost_a",
		subtitles_enabled = false,
	},
	enemy_ritualist_a = {
		full_name = "loc_npc_full_name_enemy_ritualist_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_ritualist_a",
		subtitles_enabled = true,
	},
	prologue_traitor_a = {
		full_name = "loc_npc_full_name_prologue_traitor_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_prologue_traitor_a",
		subtitles_enabled = true,
	},
	enemy_chaos_newly_infected_male_e = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_f = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_g = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_h = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_i = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_ogryn_bulwark_a = {
		full_name = "loc_npc_full_name_enemy_chaos_ogryn_bulwark",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_ogryn_bulwark",
		subtitles_enabled = false,
	},
	enemy_chaos_ogryn_armoured_executor_a = {
		full_name = "loc_npc_full_name_enemy_chaos_ogryn_armoured_executor",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_ogryn_armoured_executor",
		subtitles_enabled = false,
	},
	enemy_chaos_ogryn_heavy_gunner_a = {
		full_name = "loc_npc_full_name_enemy_chaos_ogryn_heavy_gunner",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_ogryn_heavy_gunner",
		subtitles_enabled = false,
	},
	enemy_captain_sadist_a = {
		full_name = "loc_npc_full_name_enemy_captain_sadist_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_sadist_a",
		subtitles_enabled = true,
	},
	enemy_captain_spiritual_a = {
		full_name = "loc_npc_full_name_enemy_captain_spiritual_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_spiritual_a",
		subtitles_enabled = true,
	},
	enemy_captain_sadist_b = {
		full_name = "loc_npc_full_name_enemy_captain_sadist_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_sadist_a",
		subtitles_enabled = true,
	},
	enemy_captain_spiritual_b = {
		full_name = "loc_npc_full_name_enemy_captain_spiritual_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_spiritual_a",
		subtitles_enabled = true,
	},
	enemy_captain_officer_a = {
		full_name = "loc_npc_full_name_enemy_captain_officer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_officer_a",
		subtitles_enabled = true,
	},
	enemy_captain_maniac_a = {
		full_name = "loc_npc_full_name_enemy_captain_maniac_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_maniac_a",
		subtitles_enabled = true,
	},
	enemy_captain_brute_a = {
		full_name = "loc_npc_full_name_enemy_captain_brute_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_brute_a",
		subtitles_enabled = true,
	},
	crowd_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_crowd_a",
		subtitles_enabled = true,
	},
	servitor_grendyl_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_grendyl",
		subtitles_enabled = true,
	},
	servitor_male_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_servitor_male_a",
		subtitles_enabled = true,
	},
	medicae_servitor_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_medicae_servitor_a",
		subtitles_enabled = true,
	},
	medicae_servitor_b = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_medicae_servitor_a",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_a",
		subtitles_enabled = true,
	},
	mourningstar_soldier_female_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_female_a",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_b = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_b",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_c = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_c",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_d = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_d",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_e = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_e",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_f = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_f",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_g = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_g",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_h = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_h",
		subtitles_enabled = true,
	},
	mourningstar_initiate_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_initiate_a",
		subtitles_enabled = true,
	},
	mourningstar_initiate_b = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_initiate_b",
		subtitles_enabled = true,
	},
	mourningstar_officer_male_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_officer_male_a",
		subtitles_enabled = true,
	},
	mourningstar_officer_male_b = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_officer_male_b",
		subtitles_enabled = true,
	},
	barber_a = {
		full_name = "loc_npc_full_name_barber-chirurgeon_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/krall_a",
		player_voice = false,
		short_name = "loc_npc_short_name_barber-chirurgeon_a",
		subtitles_enabled = true,
	},
	enginseer_a = {
		full_name = "loc_npc_full_name_enginseer_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/enginseer_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/enginseer_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_enginseer_a",
		subtitles_enabled = true,
	},
	archive_servitor_a = {
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_servitor_male_a",
		subtitles_enabled = true,
	},
	captain_twin_female_a = {
		full_name = "loc_npc_full_name_captain_twin_female_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_captain_twin_female_a",
		subtitles_enabled = true,
	},
	captain_twin_male_a = {
		full_name = "loc_npc_full_name_captain_twin_male_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_captain_twin_male_a",
		subtitles_enabled = true,
	},
	reject_npc_a = {
		full_name = "loc_npc_full_name_reject_npc_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_reject_npc_a",
		subtitles_enabled = true,
	},
	reject_npc_servitor_a = {
		full_name = "loc_npc_full_name_reject_npc_servitor_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_reject_npc_servitor_a",
		subtitles_enabled = true,
	},
	imperial_rifleman_male_a = {
		full_name = "loc_npc_short_name_mourningstar_soldier_male_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_a",
		subtitles_enabled = true,
	},
	imperial_rifleman_male_b = {
		full_name = "loc_npc_short_name_mourningstar_soldier_male_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_b",
		subtitles_enabled = true,
	},
	imperial_rifleman_male_c = {
		full_name = "loc_npc_short_name_mourningstar_soldier_male_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_c",
		subtitles_enabled = true,
	},
	boon_vendor_a = {
		full_name = "loc_npc_full_name_boon_vendor_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/hestia_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/hestia_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_boon_vendor_a",
		subtitles_enabled = true,
	},
	tertium_noble_a = {
		full_name = "loc_npc_full_name_tertium_noble_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_tertium_noble_a",
		subtitles_enabled = true,
	},
	tertium_noble_b = {
		full_name = "loc_npc_full_name_tertium_noble_b",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_tertium_noble_b",
		subtitles_enabled = true,
	},
	warp_echo_moebian_a = {
		full_name = "loc_npc_short_name_warp_echo",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_warp_echo",
		subtitles_enabled = true,
	},
	warp_echo_moebian_b = {
		full_name = "loc_npc_short_name_warp_echo",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_warp_echo",
		subtitles_enabled = true,
	},
	cargo_pilot_a = {
		full_name = "loc_npc_full_name_cargo_pilot_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_cargo_pilot_a",
		subtitles_enabled = true,
	},
	travelling_salesman_a = {
		full_name = "loc_npc_full_name_travelling_salesman_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/swagger_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/swagger_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_travelling_salesman_a",
		subtitles_enabled = true,
	},
	travelling_salesman_b = {
		full_name = "loc_npc_full_name_travelling_salesman_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/swagger_a",
		player_voice = false,
		short_name = "loc_npc_short_name_travelling_salesman_a",
		subtitles_enabled = true,
	},
	travelling_salesman_c = {
		full_name = "loc_npc_full_name_travelling_salesman_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/swagger_a",
		player_voice = false,
		short_name = "loc_npc_short_name_travelling_salesman_a",
		subtitles_enabled = true,
	},
	dreg_lector_a = {
		full_name = "loc_npc_full_name_dreg_lector_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_dreg_lector_a",
		subtitles_enabled = true,
	},
	commissar_a = {
		full_name = "loc_npc_full_name_commissar_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/darinda_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/darinda_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_commissar_a",
		subtitles_enabled = true,
	},
	enemy_champion_preacher_a = {
		full_name = "loc_npc_full_name_enemy_champion_preacher_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_champion_preacher_a",
		subtitles_enabled = true,
	},
	enemy_champion_brute_a = {
		full_name = "loc_npc_full_name_enemy_champion_brute_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_champion_brute_a",
		subtitles_enabled = true,
	},
	enemy_champion_infested_a = {
		full_name = "loc_npc_full_name_enemy_champion_infested_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_champion_infested_a",
		subtitles_enabled = true,
	},
	enemy_chaos_armored_infected_male_a = {
		full_name = "loc_npc_full_name_enemy_chaos_armored_infected_male_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_armored_infected_male_a",
		subtitles_enabled = false,
	},
	enemy_chaos_armored_infected_male_b = {
		full_name = "loc_npc_full_name_enemy_chaos_armored_infected_male_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_armored_infected_male_b",
		subtitles_enabled = false,
	},
	enemy_chaos_armored_infected_male_c = {
		full_name = "loc_npc_full_name_enemy_chaos_armored_infected_male_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_armored_infected_male_c",
		subtitles_enabled = false,
	},
	mourningstar_hadron_servitor_a = {
		full_name = "loc_credits_view_hadron_servitor_title",
		icon = nil,
		player_voice = false,
		short_name = "loc_credits_view_hadron_servitor_title",
		subtitles_enabled = true,
	},
	steelhead_a = {
		full_name = "loc_npc_full_name_steelhead_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_steelhead_a",
		subtitles_enabled = true,
	},
	steelhead_b = {
		full_name = "loc_npc_full_name_steelhead_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_steelhead_b",
		subtitles_enabled = true,
	},
	steelhead_c = {
		full_name = "loc_npc_full_name_steelhead_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_steelhead_c",
		subtitles_enabled = true,
	},
	steelhead_d = {
		full_name = "loc_npc_full_name_steelhead_d",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_steelhead_d",
		subtitles_enabled = true,
	},
	steelhead_e = {
		full_name = "loc_npc_full_name_steelhead_e",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_steelhead_e",
		subtitles_enabled = true,
	},
	steelhead_f = {
		full_name = "loc_npc_full_name_steelhead_f",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_steelhead_f",
		subtitles_enabled = true,
	},
	past_adamant_officer_a = {
		full_name = "loc_npc_full_name_adamant_officer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_adamant_officer_a",
		subtitles_enabled = true,
	},
	past_alpha_a = {
		full_name = "loc_npc_full_name_past_alpha_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_alpha_a",
		subtitles_enabled = true,
	},
	past_armourer_a = {
		full_name = "loc_npc_full_name_past_armourer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_armourer_a",
		subtitles_enabled = true,
	},
	past_auric_female_a = {
		full_name = "loc_npc_full_name_past_auric_female_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_auric_female_a",
		subtitles_enabled = true,
	},
	past_auric_male_a = {
		full_name = "loc_npc_full_name_past_auric_male_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_auric_male_a",
		subtitles_enabled = true,
	},
	past_auspex_operator_a = {
		full_name = "loc_npc_full_name_past_auspex_operator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_auspex_operator_a",
		subtitles_enabled = true,
	},
	past_brother_a = {
		full_name = "loc_npc_full_name_past_brother_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_brother_a",
		subtitles_enabled = true,
	},
	past_captain_twin_female_a = {
		full_name = "loc_npc_full_name_past_captain_twin_female_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_captain_twin_female_a",
		subtitles_enabled = true,
	},
	past_cartel_tough_a = {
		full_name = "loc_npc_full_name_past_cartel_tough_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_cartel_tough_a",
		subtitles_enabled = true,
	},
	past_cartel_tough_c = {
		full_name = "loc_npc_full_name_past_cartel_tough_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_cartel_tough_c",
		subtitles_enabled = true,
	},
	past_commissar_a = {
		full_name = "loc_npc_full_name_past_commissar_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_commissar_a",
		subtitles_enabled = true,
	},
	past_comms_operator_c = {
		full_name = "loc_npc_full_name_past_comms_operator_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_comms_operator_c",
		subtitles_enabled = true,
	},
	past_enemy_nemesis_wolfer_a = {
		full_name = "loc_npc_full_name_past_enemy_nemesis_wolfer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_enemy_nemesis_wolfer_a",
		subtitles_enabled = true,
	},
	past_enginseer_a = {
		full_name = "loc_npc_full_name_past_enginseer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_enginseer_a",
		subtitles_enabled = true,
	},
	past_explicator_a = {
		full_name = "loc_npc_full_name_past_explicator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_explicator_a",
		subtitles_enabled = true,
	},
	past_explicator_b = {
		full_name = "loc_npc_full_name_past_explicator_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_explicator_b",
		subtitles_enabled = true,
	},
	past_interrogator_a = {
		full_name = "loc_npc_full_name_past_interrogator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_interrogator_a",
		subtitles_enabled = true,
	},
	past_interrogator_b = {
		full_name = "loc_npc_full_name_past_interrogator_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_interrogator_b",
		subtitles_enabled = true,
	},
	past_legion_captain_a = {
		full_name = "loc_npc_full_name_past_legion_captain_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_legion_captain_a",
		subtitles_enabled = true,
	},
	past_legion_commissar_a = {
		full_name = "loc_npc_full_name_past_legion_commissar_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_legion_commissar_a",
		subtitles_enabled = true,
	},
	past_legion_trooper_a = {
		full_name = "loc_npc_full_name_past_legion_trooper_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_legion_trooper_a",
		subtitles_enabled = true,
	},
	past_legion_trooper_b = {
		full_name = "loc_npc_full_name_past_legion_trooper_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_legion_trooper_b",
		subtitles_enabled = true,
	},
	past_legion_trooper_c = {
		full_name = "loc_npc_full_name_past_legion_trooper_c",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_legion_trooper_c",
		subtitles_enabled = true,
	},
	past_magos_biologis_a = {
		full_name = "loc_npc_full_name_past_magos_biologis_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_magos_biologis_a",
		subtitles_enabled = true,
	},
	past_matriarch_a = {
		full_name = "loc_npc_full_name_past_matriarch_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_matriarch_a",
		subtitles_enabled = true,
	},
	past_mourningstar_officer_a = {
		full_name = "loc_npc_full_name_past_mourningstar_officer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_mourningstar_officer_a",
		subtitles_enabled = true,
	},
	past_ragged_king_a = {
		full_name = "loc_npc_full_name_past_ragged_king_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_ragged_king_a",
		subtitles_enabled = true,
	},
	past_sergeant_a = {
		full_name = "loc_npc_full_name_past_sergeant_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_sergeant_a",
		subtitles_enabled = true,
	},
	past_shipmistress_a = {
		full_name = "loc_npc_full_name_past_shipmistress_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_shipmistress_a",
		subtitles_enabled = true,
	},
	past_tech_priest_a = {
		full_name = "loc_npc_full_name_past_tech_priest_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_tech_priest_a",
		subtitles_enabled = true,
	},
	past_tertium_enforcer_a = {
		full_name = "loc_npc_full_name_past_tertium_enforcer_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_tertium_enforcer_a",
		subtitles_enabled = true,
	},
	past_tertium_enforcer_b = {
		full_name = "loc_npc_full_name_past_tertium_enforcer_b",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_tertium_enforcer_b",
		subtitles_enabled = true,
	},
	past_world_eater_a = {
		full_name = "loc_npc_full_name_past_world_eater_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_world_eater_a",
		subtitles_enabled = true,
	},
	past_young_explicator_a = {
		full_name = "loc_npc_full_name_past_young_explicator_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_young_explicator_a",
		subtitles_enabled = true,
	},
	past_young_sergeant_a = {
		full_name = "loc_npc_full_name_past_young_sergeant_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_past_young_sergeant_a",
		subtitles_enabled = true,
	},
	fx = {
		full_name = "loc_npc_full_name_fx",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_fx",
		subtitles_enabled = true,
	},
	nox_commissar_a = {
		full_name = "loc_npc_short_name_nox_commissar_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_nox_commissar_a",
		subtitles_enabled = true,
	},
	nox_soldier_a = {
		full_name = "loc_npc_short_name_nox_soldier_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_nox_soldier_a",
		subtitles_enabled = true,
	},
	nox_stranger_a = {
		full_name = "loc_npc_short_name_nox_stranger_a",
		icon = nil,
		player_voice = false,
		short_name = "loc_npc_short_name_nox_stranger_a",
		subtitles_enabled = true,
	},
	cine_plasma_gunner_a = {
		full_name = "loc_breed_display_name_renegade_plasma_gunner",
		icon = nil,
		player_voice = false,
		short_name = "loc_breed_display_name_renegade_plasma_gunner",
		subtitles_enabled = true,
	},
}

return settings("DialogueSpeakerVoiceSettings", dialogue_speaker_voice_settings)
