-- chunkname: @scripts/settings/dialogue/dialogue_speaker_voice_settings.lua

local dialogue_speaker_voice_settings = {
	veteran_male_a = {
		full_name = "loc_character_class_veteran",
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_female_a = {
		full_name = "loc_character_class_veteran",
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_male_b = {
		full_name = "loc_character_class_veteran",
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_female_b = {
		full_name = "loc_character_class_veteran",
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_male_c = {
		full_name = "loc_character_class_veteran",
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	veteran_female_c = {
		full_name = "loc_character_class_veteran",
		player_voice = true,
		short_name = "loc_character_class_veteran",
		subtitles_enabled = true,
	},
	zealot_male_a = {
		full_name = "loc_character_class_zealot",
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_female_a = {
		full_name = "loc_character_class_zealot",
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_male_b = {
		full_name = "loc_character_class_zealot",
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_female_b = {
		full_name = "loc_character_class_zealot",
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_male_c = {
		full_name = "loc_character_class_zealot",
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	zealot_female_c = {
		full_name = "loc_character_class_zealot",
		player_voice = true,
		short_name = "loc_character_class_zealot",
		subtitles_enabled = true,
	},
	psyker_male_a = {
		full_name = "loc_character_class_psyker",
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_female_a = {
		full_name = "loc_character_class_psyker",
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_male_b = {
		full_name = "loc_character_class_psyker",
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_female_b = {
		full_name = "loc_character_class_psyker",
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_male_c = {
		full_name = "loc_character_class_psyker",
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	psyker_female_c = {
		full_name = "loc_character_class_psyker",
		player_voice = true,
		short_name = "loc_character_class_psyker",
		subtitles_enabled = true,
	},
	ogryn_a = {
		full_name = "loc_character_class_ogryn",
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	ogryn_b = {
		full_name = "loc_character_class_ogryn",
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	ogryn_c = {
		full_name = "loc_character_class_ogryn",
		player_voice = true,
		short_name = "loc_character_class_ogryn",
		subtitles_enabled = true,
	},
	sergeant_a = {
		full_name = "loc_npc_full_name_sergeant_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sergeant_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sergeant_a_small",
		player_voice = true,
		short_name = "loc_npc_short_name_sergeant_a",
		subtitles_enabled = true,
	},
	sergeant_b = {
		full_name = "loc_npc_full_name_sergeant_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sergeant_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sergeant_a_small",
		player_voice = true,
		short_name = "loc_npc_short_name_sergeant_a",
		subtitles_enabled = true,
	},
	pilot_a = {
		full_name = "loc_npc_full_name_pilot_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/pilot_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/pilot_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_pilot_a",
		subtitles_enabled = true,
	},
	purser_a = {
		full_name = "loc_npc_full_name_purser_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/alice_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/alice_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_purser_a",
		subtitles_enabled = true,
	},
	explicator_a = {
		full_name = "loc_npc_full_name_explicator_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/explicator_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/explicator_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_explicator_a",
		subtitles_enabled = true,
	},
	tech_priest_a = {
		full_name = "loc_npc_full_name_tech_priest_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/tech_priest_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/tech_priest_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_tech_priest_a",
		subtitles_enabled = true,
	},
	training_ground_psyker_a = {
		full_name = "loc_npc_full_name_training_ground_psyker_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/sefoni_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/sefoni_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_training_ground_psyker_a",
		subtitles_enabled = true,
	},
	interrogator_a = {
		full_name = "loc_npc_full_name_interrogator_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/rannick_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/rannick_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_interrogator_a",
		subtitles_enabled = true,
	},
	shipmistress_a = {
		full_name = "loc_npc_full_name_shipmistress_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/brahms_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/brahms_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_shipmistress_a",
		subtitles_enabled = true,
	},
	vocator_a = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	vocator_b = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_confessor_a = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_wing_commander_a = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_a = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_b = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_c = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	mourningstar_servitor_d = {
		full_name = "loc_npc_full_name_vocator_a",
		player_voice = false,
		short_name = "loc_npc_short_name_vocator_a",
		subtitles_enabled = true,
	},
	contract_vendor_a = {
		full_name = "loc_npc_full_name_contract_vendor_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/melk_a",
		material_small = "content/ui/materials/icons/npc_portraits/mission_givers/melk_a_small",
		player_voice = false,
		short_name = "loc_npc_short_name_contract_vendor_a",
		subtitles_enabled = true,
	},
	credit_store_servitor_a = {
		full_name = "loc_npc_full_name_credit_store_servitor_b",
		player_voice = false,
		short_name = "loc_npc_short_name_credit_store_servitor_b",
		subtitles_enabled = true,
	},
	credit_store_servitor_b = {
		full_name = "loc_npc_full_name_credit_store_servitor_a",
		player_voice = false,
		short_name = "loc_npc_short_name_credit_store_servitor_a",
		subtitles_enabled = true,
	},
	credit_store_servitor_c = {
		full_name = "loc_npc_full_name_credit_store_servitor_c",
		player_voice = false,
		short_name = "loc_npc_short_name_credit_store_servitor_c",
		subtitles_enabled = true,
	},
	enemy_cultist_herald_a = {
		full_name = "loc_npc_full_name_enemy_cultist_herald_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_herald_a",
		subtitles_enabled = false,
	},
	enemy_rogue_psyker_a = {
		full_name = "loc_npc_full_name_enemy_rogue_psyker_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_rogue_psyker_a",
		subtitles_enabled = false,
	},
	enemy_traitor_lieutenant_a = {
		full_name = "loc_npc_full_name_enemy_traitor_lieutenant_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_traitor_lieutenant_a",
		subtitles_enabled = false,
	},
	enemy_traitor_enforcer_executor_a = {
		full_name = "loc_npc_full_name_enemy_traitor_enforcer_executor_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_traitor_enforcer_executor_a",
		subtitles_enabled = false,
	},
	prison_guard_a = {
		full_name = "loc_npc_full_name_prison_guard_a",
		player_voice = false,
		short_name = "loc_npc_short_name_prison_guard_a",
		subtitles_enabled = true,
	},
	enemy_nemesis_wolfer_a = {
		full_name = "loc_npc_full_name_enemy_nemesis_wolfer_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/wolfer_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_nemesis_wolfer_a",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_a = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_01",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_a",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_b = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_b",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_02",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_b",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_c = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_a",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_01",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_a",
		subtitles_enabled = true,
	},
	enemy_wolfer_adjutant_d = {
		full_name = "loc_npc_full_name_enemy_wolfer_adjutant_b",
		icon = "content/ui/textures/icons/npc_portraits/enemies/officer_02",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_wolfer_adjutant_b",
		subtitles_enabled = true,
	},
	enemy_cultist_flamer_a = {
		full_name = "loc_npc_full_name_enemy_cultist_flamer",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_flamer",
		subtitles_enabled = false,
	},
	enemy_cultist_melee_fighter_a = {
		full_name = "loc_npc_full_name_enemy_cultist_melee_fighter",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_melee_fighter",
		subtitles_enabled = false,
	},
	enemy_cultist_melee_fighter_b = {
		full_name = "loc_npc_full_name_enemy_cultist_melee_fighter",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_melee_fighter",
		subtitles_enabled = false,
	},
	enemy_cultist_rusher_male_a = {
		full_name = "loc_npc_full_name_enemy_cultist_rusher",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_rusher",
		subtitles_enabled = false,
	},
	enemy_cultist_rusher_male_b = {
		full_name = "loc_npc_full_name_enemy_cultist_rusher",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_cultist_rusher",
		subtitles_enabled = false,
	},
	enemy_daemonhost_a = {
		full_name = "loc_npc_full_name_enemy_daemonhost_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_daemonhost_a",
		subtitles_enabled = false,
	},
	prologue_traitor_a = {
		full_name = "loc_npc_full_name_prologue_traitor_a",
		player_voice = false,
		short_name = "loc_npc_short_name_prologue_traitor_a",
		subtitles_enabled = true,
	},
	enemy_chaos_newly_infected_male_e = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_f = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_g = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_h = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_newly_infected_male_i = {
		full_name = "loc_npc_full_name_enemy_chaos_newly_infected",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_newly_infected",
		subtitles_enabled = false,
	},
	enemy_chaos_ogryn_bulwark_a = {
		full_name = "loc_npc_full_name_enemy_chaos_ogryn_bulwark",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_ogryn_bulwark",
		subtitles_enabled = false,
	},
	enemy_chaos_ogryn_armoured_executor_a = {
		full_name = "loc_npc_full_name_enemy_chaos_ogryn_armoured_executor",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_ogryn_armoured_executor",
		subtitles_enabled = false,
	},
	enemy_chaos_ogryn_heavy_gunner_a = {
		full_name = "loc_npc_full_name_enemy_chaos_ogryn_heavy_gunner",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_chaos_ogryn_heavy_gunner",
		subtitles_enabled = false,
	},
	enemy_captain_sadist_a = {
		full_name = "loc_npc_full_name_enemy_captain_sadist_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_sadist_a",
		subtitles_enabled = true,
	},
	enemy_captain_spiritual_a = {
		full_name = "loc_npc_full_name_enemy_captain_spiritual_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_spiritual_a",
		subtitles_enabled = true,
	},
	enemy_captain_sadist_b = {
		full_name = "loc_npc_full_name_enemy_captain_sadist_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_sadist_a",
		subtitles_enabled = true,
	},
	enemy_captain_spiritual_b = {
		full_name = "loc_npc_full_name_enemy_captain_spiritual_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_spiritual_a",
		subtitles_enabled = true,
	},
	enemy_captain_officer_a = {
		full_name = "loc_npc_full_name_enemy_captain_officer_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_officer_a",
		subtitles_enabled = true,
	},
	enemy_captain_maniac_a = {
		full_name = "loc_npc_full_name_enemy_captain_maniac_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_maniac_a",
		subtitles_enabled = true,
	},
	enemy_captain_brute_a = {
		full_name = "loc_npc_full_name_enemy_captain_brute_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enemy_captain_brute_a",
		subtitles_enabled = true,
	},
	crowd_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_crowd_a",
		subtitles_enabled = true,
	},
	servitor_female_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_servitor_female_a",
		subtitles_enabled = true,
	},
	servitor_male_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_servitor_male_a",
		subtitles_enabled = true,
	},
	medicae_servitor_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_medicae_servitor_a",
		subtitles_enabled = true,
	},
	medicae_servitor_b = {
		player_voice = false,
		short_name = "loc_npc_short_name_medicae_servitor_a",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_a",
		subtitles_enabled = true,
	},
	mourningstar_soldier_female_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_female_a",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_b = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_b",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_c = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_c",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_d = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_d",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_e = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_e",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_f = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_f",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_g = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_g",
		subtitles_enabled = true,
	},
	mourningstar_soldier_male_h = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_h",
		subtitles_enabled = true,
	},
	mourningstar_initiate_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_initiate_a",
		subtitles_enabled = true,
	},
	mourningstar_initiate_b = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_initiate_b",
		subtitles_enabled = true,
	},
	mourningstar_officer_male_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_officer_male_a",
		subtitles_enabled = true,
	},
	mourningstar_officer_male_b = {
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_officer_male_b",
		subtitles_enabled = true,
	},
	barber_a = {
		full_name = "loc_npc_full_name_barber-chirurgeon_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/krall_a",
		player_voice = false,
		short_name = "loc_npc_short_name_barber-chirurgeon_a",
		subtitles_enabled = true,
	},
	enginseer_a = {
		full_name = "loc_npc_full_name_enginseer_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/enginseer_a",
		player_voice = false,
		short_name = "loc_npc_short_name_enginseer_a",
		subtitles_enabled = true,
	},
	archive_servitor_a = {
		player_voice = false,
		short_name = "loc_npc_short_name_servitor_male_a",
		subtitles_enabled = true,
	},
	captain_twin_female_a = {
		full_name = "loc_npc_full_name_captain_twin_female_a",
		player_voice = false,
		short_name = "loc_npc_short_name_captain_twin_female_a",
		subtitles_enabled = true,
	},
	captain_twin_male_a = {
		full_name = "loc_npc_full_name_captain_twin_male_a",
		player_voice = false,
		short_name = "loc_npc_short_name_captain_twin_male_a",
		subtitles_enabled = true,
	},
	reject_npc_a = {
		full_name = "loc_npc_full_name_reject_npc_a",
		player_voice = false,
		short_name = "loc_npc_short_name_reject_npc_a",
		subtitles_enabled = true,
	},
	reject_npc_servitor_a = {
		full_name = "loc_npc_full_name_reject_npc_servitor_a",
		player_voice = false,
		short_name = "loc_npc_short_name_reject_npc_servitor_a",
		subtitles_enabled = true,
	},
	imperial_rifleman_male_a = {
		full_name = "loc_npc_short_name_mourningstar_soldier_male_a",
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_a",
		subtitles_enabled = true,
	},
	imperial_rifleman_male_b = {
		full_name = "loc_npc_short_name_mourningstar_soldier_male_b",
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_b",
		subtitles_enabled = true,
	},
	imperial_rifleman_male_c = {
		full_name = "loc_npc_short_name_mourningstar_soldier_male_c",
		player_voice = false,
		short_name = "loc_npc_short_name_mourningstar_soldier_male_c",
		subtitles_enabled = true,
	},
	boon_vendor_a = {
		full_name = "loc_npc_full_name_boon_vendor_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/hestia_a",
		player_voice = false,
		short_name = "loc_npc_short_name_boon_vendor_a",
		subtitles_enabled = true,
	},
	tertium_noble_a = {
		full_name = "loc_npc_full_name_tertium_noble_a",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_tertium_noble_a",
		subtitles_enabled = true,
	},
	tertium_noble_b = {
		full_name = "loc_npc_full_name_tertium_noble_b",
		icon = "content/ui/textures/icons/npc_portraits/mission_givers/default",
		player_voice = false,
		short_name = "loc_npc_short_name_tertium_noble_b",
		subtitles_enabled = true,
	},
	warp_echo_moebian_a = {
		full_name = "loc_npc_short_name_warp_echo",
		player_voice = false,
		short_name = "loc_npc_short_name_warp_echo",
		subtitles_enabled = true,
	},
	warp_echo_moebian_b = {
		full_name = "loc_npc_short_name_warp_echo",
		player_voice = false,
		short_name = "loc_npc_short_name_warp_echo",
		subtitles_enabled = true,
	},
}

return settings("DialogueSpeakerVoiceSettings", dialogue_speaker_voice_settings)
