-- chunkname: @scripts/settings/dialogue/vo_query_constants.lua

local vo_query_constants = {
	concepts = {
		interaction_vo = "interaction_vo",
		on_demand_com_wheel = "on_demand_com_wheel",
		on_demand_vo_tag_enemy = "on_demand_vo_tag_enemy",
		on_demand_vo_tag_item = "on_demand_vo_tag_item",
	},
	trigger_ids = {
		com_wheel_vo_enemy_over_here = "location_enemy_there",
		com_wheel_vo_follow_you = "answer_following",
		com_wheel_vo_for_the_emperor = "com_cheer",
		com_wheel_vo_lets_go_this_way = "location_this_way",
		com_wheel_vo_my_pleasure = "com_my_pleasure",
		com_wheel_vo_need_ammo = "com_need_ammo",
		com_wheel_vo_need_health = "com_need_health",
		com_wheel_vo_need_that = "answer_need",
		com_wheel_vo_no = "answer_no",
		com_wheel_vo_over_here = "location_over_here",
		com_wheel_vo_take_this = "com_take_this",
		com_wheel_vo_thank_you = "com_thank_you",
		com_wheel_vo_yes = "answer_yes",
		smart_tag_vo_pickup_ammo = "pup_ammo",
		smart_tag_vo_pickup_battery = "pup_battery",
		smart_tag_vo_pickup_container = "pup_container",
		smart_tag_vo_pickup_control_rod = "pup_control_rod",
		smart_tag_vo_pickup_deployed_ammo_crate = "pup_deployed_ammo_crate",
		smart_tag_vo_pickup_deployed_medical_crate = "pup_deployed_medical_crate",
		smart_tag_vo_pickup_forge_metal = "pup_forge_metal",
		smart_tag_vo_pickup_medical_crate = "pup_medical_crate",
		smart_tag_vo_pickup_platinum = "pup_platinum",
		smart_tag_vo_pickup_side_mission_consumable = "pup_side_mission_consumable",
		smart_tag_vo_pickup_side_mission_grimoire = "pup_side_mission_grimoire",
		smart_tag_vo_pickup_side_mission_tome = "pup_side_mission_tome",
		smart_tag_vo_pickup_stimm_concentration = "pup_stimm_concentration",
		smart_tag_vo_pickup_stimm_health = "pup_stimm_health",
		smart_tag_vo_pickup_stimm_power = "pup_stimm_power",
		smart_tag_vo_pickup_stimm_speed = "pup_stimm_speed",
		smart_tag_vo_small_grenade = "pup_small_grenade",
		smart_tag_vo_station_health = "station_health",
		smart_tag_vo_station_health_without_battery = "station_health_without_battery",
	},
}

return vo_query_constants
