-- chunkname: @content/levels/prologue/cs_03_bay/world_item_dep.lua

local item_dependencies = {
	minion_items = {},
	player_items = {
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 3,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_c"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_lowerbody_01"] = 2,
		["content/items/characters/player/human/gear_attachments/prisoner_male_belt_01"] = 1,
		["content/items/characters/player/human/hair/hair_short_c"] = 1,
		["content/items/characters/player/human/attachment_base/female_arms"] = 1,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_shoulderpad_01_b"] = 1,
		["content/items/characters/player/human/gear_arms/imperial_guard_upperbody_arms_01"] = 4,
		["content/items/characters/player/human/gear_arms/prisoner_male_upperbody_arms_01"] = 1,
		["content/items/characters/player/human/face_hair/facial_hair_c_eyebrows"] = 1,
		["content/items/characters/player/human/faces/male_african_face_01"] = 2,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_d"] = 1,
		["content/items/characters/player/human/faces/female_middle_eastern_face_02_cine_dummy"] = 1,
		["content/items/characters/player/human/cine_props/metal_stick_01"] = 3,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_b"] = 2,
		["content/items/characters/player/human/attachment_base/male_arms"] = 3,
		["content/items/characters/player/human/gear_torso/prisoner_male_upperbody_01"] = 1,
		["content/items/characters/player/human/face_hair/female_facial_hair_b"] = 1,
		["content/items/characters/player/ogryn/gear_torso/ogryn_prisoner_upperbody_a"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_face_caucasian"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_legs"] = 1,
		["content/items/characters/player/ogryn/face_scars/ogryn_scar_face_04"] = 1,
		["content/items/weapons/npc/ogryn_thumper_npc_01"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_c"] = 2,
		["content/items/characters/player/ogryn/attachment_base/male_torso"] = 1,
		["content/items/weapons/npc/lasgun_npc_05"] = 1,
		["content/items/weapons/npc/laspistol_npc_01"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_arms"] = 2,
		["content/items/characters/player/ogryn/gear_legs/ogryn_prisoner_lowerbody_a"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_f"] = 2,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_shoulderpad_01"] = 2,
		["content/items/characters/player/human/gear_attachments/zola_wound_01"] = 1,
		["content/items/characters/player/human/face_hair/facial_hair_a_eyebrows"] = 2,
		["content/items/characters/player/human/face_scars/scar_face_07"] = 1,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_03"] = 3,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_e"] = 1,
		["content/items/characters/player/human/face_hair/facial_hair_b_fullbeard"] = 1,
		["content/items/characters/player/human/gear_head/cadian_command_02_a"] = 2,
		["content/items/characters/player/human/hair/hair_medium_undercut_a"] = 1,
		["content/items/characters/player/human/faces/male_asian_face_01"] = 1,
		["content/items/characters/player/human/gear_feet/astra_shoes_e"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_01"] = 1,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_belt_01_a"] = 1,
		["content/items/characters/player/ogryn/hair/ogryn_hair_short_tripplemohawk_a"] = 1,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01_attachment"] = 1,
		["content/items/characters/player/human/gear_legs/prisoner_male_lowerbody_01"] = 1
	},
	weapon_items = {
		["content/items/weapons/player/ranged/laspistol_p1_m1"] = 1,
		["content/items/weapons/player/ranged/autogun_p1_m1"] = 1,
		["content/items/weapons/player/ranged/lasgun_p1_m1"] = 1
	}
}

return item_dependencies
