-- chunkname: @scripts/extension_systems/extension_system_configuration.lua

local function _system_require(dir, ...)
	local path = "scripts/extension_systems/" .. dir

	for i = 1, select("#", ...) do
		require(path .. "/" .. select(i, ...))
	end
end

_system_require("ability", "player_unit_ability_extension", "player_husk_ability_extension")
_system_require("action_input", "player_unit_action_input_extension")
_system_require("aim", "player_unit_aim_extension", "player_unit_hub_aim_extension", "player_husk_hub_aim_extension", "player_husk_aim_extension", "minion_ranged_aim_extension", "minion_ranged_husk_aim_extension")
_system_require("hologram", "player_unit_hologram_extension")
_system_require("animation", "animation_system")
_system_require("attack_intensity", "attack_intensity_system")
_system_require("behavior", "behavior_system")
_system_require("blackboard", "blackboard_system")
_system_require("boss", "boss_system")
_system_require("broadphase", "broadphase_system")
_system_require("buff", "minion_buff_extension", "player_unit_buff_extension", "player_husk_buff_extension", "projectile_unit_buff_extension")
_system_require("camera", "camera_system")
_system_require("character_state_machine", "character_state_machine_extension")
_system_require("chest", "chest_system")
_system_require("cinematic_scene", "cinematic_scene_system")
_system_require("coherency", "coherency_system")
_system_require("combat_vector", "combat_vector_system")
_system_require("companion_spawner", "companion_spawner_extension")
_system_require("component", "component_system")
_system_require("corruptor_arm", "corruptor_arm_system")
_system_require("corruptor", "corruptor_system")
_system_require("cover", "cover_system")
_system_require("cutscene_character", "cutscene_character_system")
_system_require("darkness", "darkness_system")
_system_require("decoder_device", "decoder_device_system")
_system_require("destructible", "destructible_system")
_system_require("dialogue", "dialogue_context_system")
_system_require("dialogue", "dialogue_system")
_system_require("dissolve", "minion_dissolve_extension")
_system_require("door", "door_system")
_system_require("door_control_panel", "door_control_panel_system")
_system_require("event_synchronizer", "event_synchronizer_system")
_system_require("fade", "fade_system")
_system_require("first_person", "player_unit_first_person_extension", "player_husk_first_person_extension")
_system_require("force_field", "force_field_system")
_system_require("fx", "fx_system")
_system_require("gadget", "gadget_system")
_system_require("group", "group_system")
_system_require("hazard_prop", "hazard_prop_system")
_system_require("health", "health_system")
_system_require("health_station", "health_station_system")
_system_require("input", "player_unit_input_extension")
_system_require("interaction", "interactee_system", "interactor_system")
_system_require("ledge_finder", "player_unit_ledge_finder_extension")
_system_require("legacy_v2_proximity", "legacy_v2_proximity_system")
_system_require("liquid_area", "liquid_area_system")
_system_require("light_controller", "light_controller_system")
_system_require("locomotion", "locomotion_system")
_system_require("luggable", "luggable_extension")
_system_require("luggable_socket", "luggable_socket_system")
_system_require("minigame", "minigame_system")
_system_require("minion_spawner", "minion_spawner_system")
_system_require("mission_objective", "mission_objective_system")
_system_require("mission_objective_target", "mission_objective_target_system")
_system_require("mission_objective_zone", "mission_objective_zone_system")
_system_require("mission_objective_zone_scannable", "mission_objective_zone_scannable_system")
_system_require("mood", "player_unit_mood_extension")
_system_require("moveable_platform", "moveable_platform_system")
_system_require("music_parameter", "player_unit_music_parameter_extension", "player_husk_music_parameter_extension")
_system_require("nav_block", "nav_block_extension")
_system_require("nav_graph", "nav_graph_system")
_system_require("navigation", "navigation_system")
_system_require("networked_timer", "networked_timer_system")
_system_require("outline", "outline_system")
_system_require("spline_follower", "spline_follower_system")
_system_require("perception", "perception_system")
_system_require("physics_unit_proximity", "physics_unit_proximity_system")
_system_require("pickup_animation", "pickup_animation_system")
_system_require("pickups", "pickup_system")
_system_require("player_spawner", "player_spawner_system")
_system_require("player_visibility", "player_visibility_extension")
_system_require("point_of_interest", "point_of_interest_system")
_system_require("projectile_damage", "projectile_damage_extension")
_system_require("proximity", "side_relation_proximity_extension")
_system_require("recoil", "player_unit_weapon_recoil_extension")
_system_require("respawn_beacon", "respawn_beacon_system")
_system_require("scanner_display", "scanner_display_extension")
_system_require("scanning_event", "scanning_event_system")
_system_require("servo_skull", "servo_skull_system")
_system_require("shading_environment", "shading_environment_system")
_system_require("shield", "minion_shield_extension", "minion_husk_shield_extension", "prop_shield_extension")
_system_require("side", "side_system")
_system_require("side_mission", "side_mission_pickup_extension")
_system_require("slot", "slot_system")
_system_require("smart_tag", "smart_tag_system")
_system_require("smart_targeting", "player_unit_smart_targeting_extension")
_system_require("smoke_fog", "smoke_fog_system", "smoke_fog_extension", "smoke_fog_husk_extension")
_system_require("spline_group", "spline_group_system")
_system_require("spread", "player_unit_weapon_spread_extension")
_system_require("suppression", "minion_suppression_extension", "minion_suppression_husk_extension", "player_suppression_extension")
_system_require("summoned_minions", "summoned_minions_extension")
_system_require("scripted_scenario", "scripted_scenario_system")
_system_require("talent", "talent_system")
_system_require("trigger", "trigger_system")
_system_require("token", "token_system")
_system_require("toughness", "player_unit_toughness_extension", "player_husk_toughness_extension", "player_hub_toughness_extension", "minion_toughness_extension", "minion_toughness_husk_extension")
_system_require("unit_data", "minion_unit_data_extension", "player_unit_data_extension", "player_husk_data_extension", "prop_unit_data_extension")
_system_require("visual_loadout", "visual_loadout_system")
_system_require("volume_event", "volume_event_system")
_system_require("weakspot", "weakspot_extension")
_system_require("weapon", "weapon_system")
_system_require("weather", "weather_system")
_system_require("wounds", "wounds_extension")

local enabled_in_runtime_loaded_levels = false
local systems = {
	{
		"side_system",
		"SideSystem",
		true,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SideExtension"
		}
	},
	{
		"companion_spawner_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CompanionSpawnerExtension"
		}
	},
	{
		"token_system",
		"TokenSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"TokenExtension"
		}
	},
	{
		"player_spawner_system",
		"PlayerSpawnerSystem",
		true,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerSpawnerExtension"
		}
	},
	{
		"group_system",
		"GroupSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionGroupExtension",
			"PlayerGroupExtension"
		}
	},
	{
		"perception_system",
		"PerceptionSystem",
		true,
		false,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"BotPerceptionExtension",
			"CompanionPerceptionExtension",
			"MinionPerceptionExtension"
		}
	},
	{
		"cover_system",
		"CoverSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CoverExtension",
			"CoverUserExtension"
		}
	},
	{
		"combat_vector_system",
		"CombatVectorSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CombatVectorUserExtension"
		}
	},
	{
		"behavior_system",
		"BehaviorSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"BotBehaviorExtension",
			"CombatRangeUserBehaviorExtension",
			"CompanionBehaviorExtension",
			"MinionBehaviorExtension"
		}
	},
	{
		"input_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitInputExtension"
		}
	},
	{
		"first_person_system",
		"ExtensionSystemBase",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitFirstPersonExtension",
			"PlayerHuskFirstPersonExtension"
		}
	},
	{
		"smart_targeting_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitSmartTargetingExtension"
		}
	},
	{
		"talent_system",
		"TalentSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitTalentExtension",
			"PlayerHuskTalentExtension"
		}
	},
	{
		"broadphase_system",
		"BroadphaseSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"BroadphaseExtension"
		}
	},
	{
		"buff_system",
		"ExtensionSystemBase",
		true,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitBuffExtension",
			"PlayerHuskBuffExtension",
			"MinionBuffExtension",
			"ProjectileUnitBuffExtension"
		}
	},
	{
		"action_input_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitActionInputExtension"
		}
	},
	{
		"interactee_system",
		"InteracteeSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"InteracteeExtension",
			"PlayerInteracteeExtension"
		}
	},
	{
		"interactor_system",
		"InteractorSystem",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"InteractorExtension"
		}
	},
	{
		"ledge_finder_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitLedgeFinderExtension"
		}
	},
	{
		"light_controller_system",
		"LightControllerSystem",
		false,
		false,
		false,
		true,
		true,
		{
			"LightControllerExtension"
		}
	},
	{
		"character_state_machine_system",
		"ExtensionSystemBase",
		true,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CharacterStateMachineExtension"
		}
	},
	{
		"shield_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionShieldExtension",
			"MinionHuskShieldExtension",
			"PropShieldExtension"
		}
	},
	{
		"summon_minions_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SummonedMinionsExtension"
		}
	},
	{
		"health_system",
		"HealthSystem",
		true,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"HealthExtension",
			"HuskHealthExtension",
			"PropHealthExtension",
			"PlayerUnitHealthExtension",
			"PlayerHuskHealthExtension",
			"PlayerHubHealthExtension",
			"ForceFieldHealthExtension",
			"ForceFieldHuskHealthExtension"
		}
	},
	{
		"weakspot_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"WeakspotExtension"
		}
	},
	{
		"toughness_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitToughnessExtension",
			"PlayerHuskToughnessExtension",
			"PlayerHubToughnessExtension",
			"MinionToughnessExtension",
			"MinionToughnessHuskExtension"
		}
	},
	{
		"visual_loadout_system",
		"VisualLoadoutSystem",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CompanionVisualLoadoutExtension",
			"MinionVisualLoadoutExtension",
			"PlayerUnitVisualLoadoutExtension",
			"PlayerHuskVisualLoadoutExtension"
		}
	},
	{
		"ability_system",
		"ExtensionSystemBase",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitAbilityExtension",
			"PlayerHuskAbilityExtension"
		}
	},
	{
		"weapon_system",
		"WeaponSystem",
		true,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitWeaponExtension",
			"ProjectileUnitWeaponExtension"
		}
	},
	{
		"weapon_spread_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitWeaponSpreadExtension"
		}
	},
	{
		"weapon_recoil_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitWeaponRecoilExtension"
		}
	},
	{
		"suppression_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerSuppressionExtension",
			"MinionSuppressionExtension",
			"MinionSuppressionHuskExtension"
		}
	},
	{
		"attack_intensity_system",
		"AttackIntensitySystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitAttackIntensityExtension",
			"MinionAttackIntensityExtension"
		}
	},
	{
		"music_parameter_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitMusicParameterExtension",
			"PlayerHuskMusicParameterExtension"
		}
	},
	{
		"gadget_system",
		"GadgetSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitGadgetExtension"
		}
	},
	{
		"navigation_system",
		"NavigationSystem",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"BotNavigationExtension",
			"MinionNavigationExtension"
		}
	},
	{
		"moveable_platform_system",
		"MoveablePlatformSystem",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MoveablePlatformExtension"
		}
	},
	{
		"networked_timer_system",
		"NetworkedTimerSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"NetworkedTimerExtension"
		}
	},
	{
		"decoder_device_system",
		"DecoderDeviceSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"DecoderDeviceExtension"
		}
	},
	{
		"luggable_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"LuggableExtension"
		}
	},
	{
		"luggable_socket_system",
		"LuggableSocketSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"LuggableSocketExtension"
		}
	},
	{
		"event_synchronizer_system",
		"EventSynchronizerSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"DecoderSynchronizerExtension",
			"DemolitionSynchronizerExtension",
			"LuggableSynchronizerExtension",
			"MissionObjectiveZoneSynchronizerExtension",
			"KillSynchronizerExtension",
			"SideMissionPickupSynchronizerExtension",
			"TimedSynchronizerExtension"
		}
	},
	{
		"spline_group_system",
		"SplineGroupSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SplineGroupExtension"
		}
	},
	{
		"spline_follower_system",
		"SplineFollowerSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SplineFollowerExtension"
		}
	},
	{
		"scanning_event_system",
		"ScanningEventSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ScanningDeviceExtension"
		}
	},
	{
		"servo_skull_system",
		"ServoSkullSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ServoSkullExtension",
			"ServoSkullActivatorExtension"
		}
	},
	{
		"mission_objective_target_system",
		"MissionObjectiveTargetSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MissionObjectiveTargetExtension"
		}
	},
	{
		"locomotion_system",
		"LocomotionSystem",
		true,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionLocomotionExtension",
			"MinionHuskLocomotionExtension",
			"ProjectileUnitLocomotionExtension",
			"ProjectileHuskLocomotionExtension",
			"PlayerUnitLocomotionExtension",
			"PlayerHuskLocomotionExtension",
			"DeployableUnitLocomotionExtension",
			"DeployableHuskLocomotionExtension"
		}
	},
	{
		"projectile_damage_system",
		"ExtensionSystemBase",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ProjectileDamageExtension"
		}
	},
	{
		"scanner_display_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ScannerDisplayExtension"
		}
	},
	{
		"force_field_system",
		"ForceFieldSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ForceFieldExtension"
		}
	},
	{
		"smoke_fog_system",
		"SmokeFogSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SmokeFogExtension",
			"SmokeFogHuskExtension"
		}
	},
	{
		"darkness_system",
		"DarknessSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels
	},
	{
		"component_system",
		"ComponentSystem",
		false,
		false,
		false,
		true,
		true,
		{
			"ComponentExtension"
		}
	},
	{
		"animation_system",
		"AnimationSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"AuthoritativePlayerUnitAnimationExtension",
			"MinionAnimationExtension",
			"PlayerUnitAnimationExtension",
			"PlayerHuskAnimationExtension",
			"PropAnimationExtension"
		}
	},
	{
		"aim_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitAimExtension",
			"PlayerHuskAimExtension",
			"PlayerUnitHubAimExtension",
			"PlayerHuskHubAimExtension",
			"MinionRangedAimExtension",
			"MinionRangedHuskAimExtension"
		}
	},
	{
		"hologram_system",
		"ExtensionSystemBase",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitHologramExtension"
		}
	},
	{
		"camera_system",
		"CameraSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitCameraExtension",
			"PlayerHuskCameraExtension"
		}
	},
	{
		"player_visibility_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerVisibilityExtension"
		}
	},
	{
		"nav_graph_system",
		"NavGraphSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"NavGraphExtension"
		}
	},
	{
		"volume_event_system",
		"VolumeEventSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerVolumeEventExtension",
			"MinionVolumeEventExtension",
			"TriggerVolumeEventExtension"
		}
	},
	{
		"nav_block_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"NavBlockExtension"
		}
	},
	{
		"door_system",
		"DoorSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"DoorExtension"
		}
	},
	{
		"door_control_panel_system",
		"DoorControlPanelSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"DoorControlPanelExtension"
		}
	},
	{
		"fx_system",
		"FxSystem",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionFxExtension",
			"PlayerUnitFxExtension",
			"ProjectileFxExtension"
		}
	},
	{
		"wounds_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"WoundsExtension"
		}
	},
	{
		"minion_spawner_system",
		"MinionSpawnerSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionSpawnerExtension"
		}
	},
	{
		"point_of_interest_system",
		"PointOfInterestSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PointOfInterestObserverExtension",
			"PointOfInterestTargetExtension"
		}
	},
	{
		"dialogue_system",
		"DialogueSystem",
		false,
		false,
		false,
		true,
		true,
		{
			"DialogueExtension"
		}
	},
	{
		"dialogue_context_system",
		"DialogueContextSystem",
		false,
		false,
		false,
		true,
		true
	},
	{
		"legacy_v2_proximity_system",
		"LegacyV2ProximitySystem",
		false,
		false,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionProximityExtension",
			"PlayerProximityExtension"
		}
	},
	{
		"proximity_system",
		"ExtensionSystemBase",
		false,
		false,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SideRelationProximityExtension"
		}
	},
	{
		"coherency_system",
		"CoherencySystem",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"UnitCoherencyExtension",
			"HuskCoherencyExtension",
			"MedicalCrateCoherencyExtension",
			"CompanionCoherencyExtension"
		}
	},
	{
		"pickup_system",
		"PickupSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PickupSpawnerExtension"
		}
	},
	{
		"pickup_animation_system",
		"PickupAnimationSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PickupAnimationExtension"
		}
	},
	{
		"side_mission_spawner_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SideMissionPickupExtension"
		}
	},
	{
		"chest_system",
		"ChestSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ChestExtension"
		}
	},
	{
		"mission_objective_zone_system",
		"MissionObjectiveZoneSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MissionObjectiveZoneBaseExtension",
			"MissionObjectiveZoneCaptureExtension",
			"MissionObjectiveZoneScanExtension"
		}
	},
	{
		"mission_objective_zone_scannable_system",
		"MissionObjectiveZoneScannableSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MissionObjectiveZoneScannableExtension"
		}
	},
	{
		"physics_unit_proximity_system",
		"PhysicsUnitProximitySystem",
		false,
		false,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PhysicsUnitProximityActorExtension",
			"PhysicsUnitProximityObserverExtension"
		}
	},
	{
		"fade_system",
		"FadeSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels
	},
	{
		"outline_system",
		"OutlineSystem",
		false,
		false,
		false,
		false,
		enabled_in_runtime_loaded_levels
	},
	{
		"dissolve_system",
		"ExtensionSystemBase",
		false,
		false,
		false,
		false,
		enabled_in_runtime_loaded_levels,
		{
			"MinionDissolveExtension"
		}
	},
	{
		"shading_environment_system",
		"ShadingEnvironmentSystem",
		false,
		false,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ShadingEnvironmentExtension"
		}
	},
	{
		"mood_system",
		"ExtensionSystemBase",
		false,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"PlayerUnitMoodExtension"
		}
	},
	{
		"respawn_beacon_system",
		"RespawnBeaconSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"RespawnBeaconExtension"
		}
	},
	{
		"mission_objective_system",
		"MissionObjectiveSystem",
		true,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels
	},
	{
		"minigame_system",
		"MinigameSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinigameExtension"
		}
	},
	{
		"trigger_system",
		"TriggerSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"TriggerExtension"
		}
	},
	{
		"health_station_system",
		"HealthStationSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"HealthStationExtension"
		}
	},
	{
		"destructible_system",
		"DestructibleSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"DestructibleExtension"
		}
	},
	{
		"hazard_prop_system",
		"HazardPropSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"HazardPropExtension"
		}
	},
	{
		"corruptor_system",
		"CorruptorSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CorruptorExtension"
		}
	},
	{
		"boss_system",
		"BossSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"BossExtension"
		}
	},
	{
		"cutscene_character_system",
		"CutsceneCharacterSystem",
		false,
		false,
		false,
		false,
		true,
		{
			"CutsceneCharacterExtension",
			"CutsceneCompanionExtension"
		}
	},
	{
		"cinematic_scene_system",
		"CinematicSceneSystem",
		false,
		false,
		false,
		true,
		true,
		{
			"CinematicSceneExtension"
		}
	},
	{
		"corruptor_arm_system",
		"CorruptorArmSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"CorruptorArmExtension"
		}
	},
	{
		"liquid_area_system",
		"LiquidAreaSystem",
		false,
		false,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"LiquidAreaExtension",
			"HuskLiquidAreaExtension"
		}
	},
	{
		"smart_tag_system",
		"SmartTagSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SmartTagExtension"
		}
	},
	{
		"scripted_scenario_system",
		"ScriptedScenarioSystem",
		false,
		true,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"ScriptableScenarioDirectionalUnitExtension"
		}
	},
	{
		"unit_data_system",
		"ExtensionSystemBase",
		true,
		true,
		true,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"MinionUnitDataExtension",
			"PlayerUnitDataExtension",
			"PlayerHuskDataExtension",
			"PropUnitDataExtension"
		}
	},
	{
		"weather_system",
		"WeatherSystem",
		false,
		false,
		false,
		false,
		enabled_in_runtime_loaded_levels,
		{
			"WeatherExtension"
		}
	},
	{
		"slot_system",
		"SlotSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"SlotExtension",
			"SlotUserExtension"
		}
	},
	{
		"blackboard_system",
		"BlackboardSystem",
		false,
		false,
		false,
		true,
		enabled_in_runtime_loaded_levels,
		{
			"BlackboardExtension"
		}
	}
}

return systems
