local item_dependencies = {
	player_items = {
		["content/items/characters/player/human/gear_legs/prisoner_male_lowerbody_01"] = 1,
		["content/items/characters/player/human/attachment_base/male_arms"] = 1,
		["content/items/characters/player/human/gear_head/rebreather_01_b"] = 1,
		["content/items/characters/player/ogryn/body_tattoo/body_tattoo_ogryn_02"] = 1,
		["content/items/characters/player/human/hair/hair_short_c"] = 1,
		["content/items/characters/player/human/attachment_base/female_arms"] = 1,
		["content/items/characters/player/human/gear_arms/prisoner_male_upperbody_arms_01"] = 1,
		["content/items/characters/player/human/gear_arms/imperial_guard_upperbody_arms_01"] = 1,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 1,
		["content/items/characters/player/human/faces/face_vin_morrow"] = 1,
		["content/items/characters/player/ogryn/face_tattoo/face_tattoo_ogryn_03"] = 1,
		["content/items/characters/player/human/faces/npc_hadron_seven_three_face"] = 1,
		["content/items/characters/player/human/gear_torso/npc_vin_morrow_upperbody"] = 1,
		["content/items/characters/player/ogryn/hair/ogryn_hair_short_tripplemohawk_a"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_b"] = 1,
		["content/items/characters/player/human/gear_legs/npc_vin_morrow_lowerbody"] = 1,
		["content/items/characters/player/ogryn/gear_torso/ogryn_prisoner_upperbody_a"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_face_caucasian"] = 1,
		["content/items/characters/player/human/gear_hands/npc_vin_morrow_gloves"] = 1,
		["content/items/characters/player/human/gear_torso/npc_hadron_seven_three_upperbody"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_c"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_torso"] = 1,
		["content/items/characters/player/ogryn/gear_legs/ogryn_prisoner_lowerbody_a"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_f"] = 1,
		["content/items/characters/player/human/hair/hair_short_e"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_legs"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_arms"] = 1,
		["content/items/characters/player/human/gear_legs/npc_hadron_seven_three_lowerbody"] = 1,
		["content/items/characters/player/human/gear_arms/npc_hadron_seven_three_arms"] = 1,
		["content/items/characters/player/human/gear_arms/npc_vin_morrow_arms"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_01"] = 1,
		["content/items/characters/player/human/gear_torso/prisoner_male_upperbody_01"] = 1,
		["content/items/characters/player/human/faces/female_middle_eastern_face_02"] = 1,
		["content/items/characters/player/ogryn/face_scars/ogryn_scar_face_04"] = 1
	},
	minion_items = {},
	weapon_items = {}
}

return item_dependencies
