-- chunkname: @scripts/settings/breed/breeds/chaos/chaos_beast_of_nurgle_sounds.lua

local sound_data = {
	events = {
		footstep = "wwise/events/minions/play_beast_of_nurge_footstep_walk",
		footstep_land = "wwise/events/minions/play_beast_of_nurgle_jump_land",
		footstep_stomp = "wwise/events/minions/play_beast_of_nurge_footstep",
		sfx_attack_movement_arm = "wwise/events/minions/play_beast_of_nurgle_attack_movement_arm",
		sfx_attack_movement_tail_slam = "wwise/events/minions/play_beast_of_nurgle_attack_movement_tail_slam",
		sfx_attack_movement_tail_whip = "wwise/events/minions/play_beast_of_nurgle_attack_movement_tail_whip",
		sfx_movement_long = "wwise/events/minions/play_beast_of_nurgle_movement_long",
		sfx_movement_short = "wwise/events/minions/play_beast_of_nurgle_movement_short",
		sfx_tongue_in = "wwise/events/minions/play_beast_of_nurgle_tongue_in",
		sfx_tongue_out = "wwise/events/minions/play_beast_of_nurgle_tongue_out",
		vce_attack = "wwise/events/minions/play_beast_of_nurgle_vce_attack",
		vce_chew = "wwise/events/minions/play_beast_of_nurgle_vce_chew",
		vce_death = "wwise/events/minions/play_beast_of_nurgle_vce_death",
		vce_eat = "wwise/events/minions/play_beast_of_nurgle_vce_eat",
		vce_excited = "wwise/events/minions/play_beast_of_nurgle_vce_excited",
		vce_grunt = "wwise/events/minions/play_beast_of_nurgle_vce_grunt",
		vce_happy_scream = "wwise/events/minions/play_beast_of_nurgle_vce_happy_scream",
		vce_hurt = "wwise/events/minions/play_beast_of_nurgle_vce_hurt",
		vce_huuh = "wwise/events/minions/play_beast_of_nurgle_vce_huuh",
		vce_pre_vomit = "wwise/events/minions/play_beast_of_nurgle_vce_pre_vomit",
		vce_run_breath = "wwise/events/minions/play_beast_of_nurgle_vce_run_breath",
		vce_spit = "wwise/events/minions/play_beast_of_nurgle_vce_spit",
		vce_spit_short = "wwise/events/minions/play_beast_of_nurgle_vce_spit_short",
		vce_swallow = "wwise/events/minions/play_beast_of_nurgle_vce_swallow",
	},
	use_proximity_culling = {
		footstep = false,
		footstep_land = false,
		footstep_stomp = false,
		sfx_attack_movement_arm = false,
		sfx_attack_movement_tail_slam = false,
		sfx_attack_movement_tail_whip = false,
		sfx_movement_long = false,
		sfx_movement_short = false,
		sfx_tongue_in = false,
		sfx_tongue_out = false,
		vce_attack = false,
		vce_chew = false,
		vce_death = false,
		vce_eat = false,
		vce_excited = false,
		vce_grunt = false,
		vce_happy_scream = false,
		vce_hurt = false,
		vce_huuh = false,
		vce_pre_vomit = false,
		vce_run_breath = false,
		vce_spit = false,
		vce_spit_short = false,
		vce_swallow = false,
	},
}

return sound_data
