local item_dependencies = {
	minion_items = {},
	player_items = {
		["content/items/characters/player/human/gear_head/cadian_command_02_b"] = 2,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_c"] = 5,
		["content/items/characters/player/human/attachment_base/female_arms"] = 5,
		["content/items/characters/player/human/gear_head/catchan_jungd_fighters_03"] = 3,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_01"] = 15,
		["content/items/characters/player/human/gear_head/rebreather_01_b"] = 11,
		["content/items/characters/player/human/gear_attachments/imperial_guard_attachment_shoulderpad_01_b"] = 9,
		["content/items/characters/player/human/gear_arms/imperial_guard_upperbody_arms_01"] = 18,
		["content/items/characters/player/human/faces/female_asian_face_01"] = 3,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_f"] = 2,
		["content/items/characters/player/human/faces/male_asian_face_01"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_d"] = 7,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_05"] = 2,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 18,
		["content/items/weapons/npc/flamer_npc_01"] = 1,
		["content/items/weapons/npc/lasgun_npc_01"] = 6,
		["content/items/weapons/npc/lasgun_npc_03"] = 1,
		["content/items/characters/player/human/faces/female_caucasian_face_02"] = 3,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_e"] = 6,
		["content/items/characters/player/human/gear_legs/imperial_guard_pants_c"] = 1,
		["content/items/weapons/npc/autogun_npc_01"] = 4,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_g"] = 1,
		["content/items/characters/player/human/gear_head/rebreather_01_a"] = 2,
		["content/items/characters/player/human/faces/male_african_face_01"] = 2,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_03"] = 1,
		["content/items/characters/player/human/gear_head/tactical_cap_01_b"] = 2,
		["content/items/characters/player/human/backpacks/backpack_cadian_a"] = 2,
		["content/items/characters/player/human/gear_head/catchan_jungd_fighters_01_a"] = 2,
		["content/items/characters/player/human/faces/female_caucasian_face_01"] = 2,
		["content/items/characters/player/human/faces/female_middle_eastern_face_01"] = 2,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_01"] = 2,
		["content/items/characters/player/human/gear_head/genestealer_cults_03_a"] = 3,
		["content/items/characters/player/human/gear_attachments/atoma_prime_decals_01"] = 9,
		["content/items/characters/player/human/faces/female_asian_face_02"] = 2,
		["content/items/characters/player/human/gear_head/tactical_cap_01_a"] = 3,
		["content/items/characters/player/human/faces/female_african_face_01"] = 3,
		["content/items/characters/player/human/gear_legs/imperial_guard_lowerbody_01"] = 17,
		["content/items/characters/player/human/backpacks/backpack_cadian_b"] = 2
	},
	weapon_items = {}
}

return item_dependencies
