-- chunkname: @scripts/settings/cinematic_video/templates/cs06.lua

local cinematic_video_template = {
	cs06 = {
		loop_video = false,
		music = "cinematic_pot",
		post_video_action = false,
		start_sound_name = "wwise/events/cinematics/play_cs06_surround_mix",
		stop_only_player_skip = true,
		stop_sound_name = "wwise/events/cinematics/stop_cs06_surround_mix",
		video_name = "content/videos/cs06",
		packages = {
			"packages/content/videos/cs06",
		},
		subtitles = {
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_01_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 8.6,
				subtitle_start = 32.3,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_02_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 4.2,
				subtitle_start = 41.8,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_03_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 0.9,
				subtitle_start = 46.6,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_04_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1.44,
				subtitle_start = 47.86,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_05_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 4.56,
				subtitle_start = 51.24,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_06_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 6.75,
				subtitle_start = 56.55,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_07_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 4.6,
				subtitle_start = 63.7,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_08_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 0.8,
				subtitle_start = 70,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_09_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1.4,
				subtitle_start = 71.3,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_10_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 6.9,
				subtitle_start = 74.3,
			},
			{
				currently_playing_subtitle = "loc_servitor_female_a__cs06_servitor_speech_12_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 5.2,
				subtitle_start = 81.8,
			},
			{
				currently_playing_subtitle = "loc_servitor_female_a__cs06_servitor_speech_13_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 1.1,
				subtitle_start = 87.4,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_14_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1.45,
				subtitle_start = 89.25,
			},
			{
				currently_playing_subtitle = "loc_servitor_female_a__cs06_servitor_speech_15_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 5.6,
				subtitle_start = 91.3,
			},
			{
				currently_playing_subtitle = "loc_servitor_female_a__cs06_servitor_speech_16_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 0.95,
				subtitle_start = 97.65,
			},
			{
				currently_playing_subtitle = "loc_servitor_female_a__cs06_servitor_speech_17_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1.6,
				subtitle_start = 99.1,
			},
			{
				currently_playing_subtitle = "loc_servitor_female_a__cs06_servitor_speech_18_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 8.65,
				subtitle_start = 102.4,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_20_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 3.5,
				subtitle_start = 111.5,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_21_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 0.85,
				subtitle_start = 116.5,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_22_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1.75,
				subtitle_start = 117.85,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_23_01",
				speaker_name = "servitor_grendyl_a",
				subtitle_duration = 1.4,
				subtitle_start = 127.2,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_24_01",
				speaker_name = "explicator_a",
				subtitle_duration = 0.65,
				subtitle_start = 143.6,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_25_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1,
				subtitle_start = 144.3,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_26_01",
				speaker_name = "explicator_a",
				subtitle_duration = 0.5,
				subtitle_start = 145.45,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_27_01",
				speaker_name = "crowd_a",
				subtitle_duration = 0.85,
				subtitle_start = 145.985,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_26_01",
				speaker_name = "explicator_a",
				subtitle_duration = 0.5,
				subtitle_start = 147,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_27_01",
				speaker_name = "crowd_a",
				subtitle_duration = 0.9,
				subtitle_start = 147.55,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_26_01",
				speaker_name = "explicator_a",
				subtitle_duration = 0.45,
				subtitle_start = 148.6,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_27_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1,
				subtitle_start = 149.1,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_26_01",
				speaker_name = "explicator_a",
				subtitle_duration = 0.45,
				subtitle_start = 150.15,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_27_01",
				speaker_name = "crowd_a",
				subtitle_duration = 1.05,
				subtitle_start = 150.65,
			},
			{
				currently_playing_subtitle = "loc_servitor_male_a__cs06_servitor_speech_26_01",
				speaker_name = "explicator_a",
				subtitle_duration = 0.45,
				subtitle_start = 151.75,
			},
			{
				currently_playing_subtitle = "loc_crowd_a__cs06_servitor_speech_28_01",
				speaker_name = "crowd_a",
				subtitle_duration = 3,
				subtitle_start = 152.25,
			},
		},
	},
}

return cinematic_video_template
