local AchievementClassGroups = {
	classes = {
		{
			name = "veteran_meta_numeric_achievement",
			local_variable = "loc_class_veteran_name",
			category = "veteran_progression",
			icon = "content/ui/textures/icons/achievements/class_achievements/class_veteran_achievement",
			achievements = {
				"rank_veteran_2_1",
				"rank_veteran_2_2",
				"rank_veteran_2_3",
				"rank_veteran_2_4",
				"rank_veteran_2_5",
				"rank_veteran_2_6",
				"missions_veteran_2_1",
				"missions_veteran_2_2",
				"missions_veteran_2_3",
				"missions_veteran_2_4",
				"missions_veteran_2_5",
				"missions_veteran_2_objective_1",
				"missions_veteran_2_objective_2",
				"missions_veteran_2_objective_3",
				"missions_veteran_2_easy_difficulty_1",
				"missions_veteran_2_easy_difficulty_2",
				"missions_veteran_2_easy_difficulty_3",
				"missions_veteran_2_easy_difficulty_4",
				"missions_veteran_2_easy_difficulty_5",
				"veteran_2_easy_1",
				"veteran_2_easy_2",
				"veteran_2_medium_1",
				"veteran_2_medium_2",
				"veteran_2_hard_1",
				"veteran_2_hard_2",
				"missions_veteran_2_medium_difficulty_1",
				"missions_veteran_2_medium_difficulty_2",
				"missions_veteran_2_medium_difficulty_3",
				"missions_veteran_2_medium_difficulty_4",
				"missions_veteran_2_medium_difficulty_5",
				"veteran_infiltrate_supress",
				"veteran_voice_of_command_toughness_given",
				"veteran_enemies_killed_with_max_focus_fire",
				"veteran_krak_grenade_kills",
				"veteran_smoke_grenade_engulfed",
				"veteran_kills_with_improved_tag",
				"veteran_weapon_switch_passive_keystone_kills",
				"veteran_team_damage_aura_amplified",
				"veteran_team_movement_aura_amplified",
				"veteran_2_weakspot_hits_during_volley_fire_alternate_fire",
				"veteran_2_unbounced_grenade_kills",
				"veteran_2_kills_with_last_round_in_mag",
				"veteran_2_no_melee_damage_taken",
				"veteran_2_elite_weakspot_kills_during_volley_fire_alternate_fire",
				"veteran_2_no_missed_shots_empty_ammo"
			}
		},
		{
			name = "zealot_meta_numeric_achievement",
			local_variable = "loc_class_zealot_name",
			category = "zealot_progression",
			icon = "content/ui/textures/icons/achievements/class_achievements/class_zealot_achievement",
			achievements = {
				"rank_zealot_2_1",
				"rank_zealot_2_2",
				"rank_zealot_2_3",
				"rank_zealot_2_4",
				"rank_zealot_2_5",
				"rank_zealot_2_6",
				"missions_zealot_2_1",
				"missions_zealot_2_2",
				"missions_zealot_2_3",
				"missions_zealot_2_4",
				"missions_zealot_2_5",
				"missions_zealot_2_objective_1",
				"missions_zealot_2_objective_2",
				"missions_zealot_2_objective_3",
				"missions_zealot_2_easy_difficulty_1",
				"missions_zealot_2_easy_difficulty_2",
				"missions_zealot_2_easy_difficulty_3",
				"missions_zealot_2_easy_difficulty_4",
				"missions_zealot_2_easy_difficulty_5",
				"zealot_2_easy_1",
				"zealot_2_easy_2",
				"zealot_2_medium_1",
				"zealot_2_medium_2",
				"zealot_2_hard_1",
				"zealot_2_hard_2",
				"missions_zealot_2_medium_difficulty_1",
				"missions_zealot_2_medium_difficulty_2",
				"missions_zealot_2_medium_difficulty_3",
				"missions_zealot_2_medium_difficulty_4",
				"missions_zealot_2_medium_difficulty_5",
				"zealot_elite_or_special_kills_with_shroudfield",
				"zealot_team_toughness_restored_with_chorus",
				"zealot_elite_or_special_kills_during_fanatic_rage",
				"zealot_kills_during_movement_keystone_activated",
				"zealot_elite_or_special_kills_with_blade_of_faith",
				"zealot_kills_with_fire_grenade",
				"zealot_aura_backstab_kills_while_alone",
				"zealot_aura_toughness_damage_reduced",
				"zealot_aura_corruption_healed",
				"zealot_2_stagger_sniper_with_grenade_distance",
				"zelot_2_kill_mutant_charger_with_melee_while_dashing",
				"zealot_2_kills_of_shocked_enemies_last_15",
				"zealot_2_not_use_ranged_attacks",
				"zealot_2_healed_up_after_resisting_death",
				"zealot_2_health_on_last_segment_enough_during_mission"
			}
		},
		{
			name = "psyker_meta_numeric_achievement",
			local_variable = "loc_class_psyker_title",
			category = "psyker_progression",
			icon = "content/ui/textures/icons/achievements/class_achievements/class_psyker_achievement",
			achievements = {
				"rank_psyker_2_1",
				"rank_psyker_2_2",
				"rank_psyker_2_3",
				"rank_psyker_2_4",
				"rank_psyker_2_5",
				"rank_psyker_2_6",
				"missions_psyker_2_1",
				"missions_psyker_2_2",
				"missions_psyker_2_3",
				"missions_psyker_2_4",
				"missions_psyker_2_5",
				"missions_psyker_2_objective_1",
				"missions_psyker_2_objective_2",
				"missions_psyker_2_objective_3",
				"missions_psyker_2_easy_difficulty_1",
				"missions_psyker_2_easy_difficulty_2",
				"missions_psyker_2_easy_difficulty_3",
				"missions_psyker_2_easy_difficulty_4",
				"missions_psyker_2_easy_difficulty_5",
				"psyker_2_easy_1",
				"psyker_2_easy_2",
				"psyker_2_medium_1",
				"psyker_2_medium_2",
				"psyker_2_hard_1",
				"psyker_2_hard_2",
				"missions_psyker_2_medium_difficulty_1",
				"missions_psyker_2_medium_difficulty_2",
				"missions_psyker_2_medium_difficulty_3",
				"missions_psyker_2_medium_difficulty_4",
				"missions_psyker_2_medium_difficulty_5",
				"psyker_2_smite_hound_mid_leap",
				"psyker_2_edge_kills_last_2_sec",
				"psyker_2_stay_at_max_souls_for_duration",
				"psyker_2_perils_of_the_warp_elite_kills",
				"psyker_2_elite_or_special_kills_with_smite_last_10_sec",
				"psyker_2_kill_boss_solo_with_smite",
				"psyker_elite_or_special_kills_with_assail",
				"psyker_kills_during_overcharge_stance",
				"psyker_kills_with_empowered_abilites",
				"psyker_time_at_max_unnatural",
				"psyker_damage_blocked_with_shield",
				"psyker_team_elite_aura_kills",
				"psyker_team_cooldown_reduced",
				"psyker_team_critical_hits",
				"psyker_threshold_kills_reached_with_grenade_chain"
			}
		},
		{
			name = "ogryn_meta_numeric_achievement",
			local_variable = "loc_class_ogryn_name",
			category = "ogryn_progression",
			icon = "content/ui/textures/icons/achievements/class_achievements/class_ogryn_achievement",
			achievements = {
				"rank_ogryn_2_1",
				"rank_ogryn_2_2",
				"rank_ogryn_2_3",
				"rank_ogryn_2_4",
				"rank_ogryn_2_5",
				"rank_ogryn_2_6",
				"missions_ogryn_2_1",
				"missions_ogryn_2_2",
				"missions_ogryn_2_3",
				"missions_ogryn_2_4",
				"missions_ogryn_2_5",
				"missions_ogryn_2_objective_1",
				"missions_ogryn_2_objective_2",
				"missions_ogryn_2_objective_3",
				"missions_ogryn_2_easy_difficulty_1",
				"missions_ogryn_2_easy_difficulty_2",
				"missions_ogryn_2_easy_difficulty_3",
				"missions_ogryn_2_easy_difficulty_4",
				"missions_ogryn_2_easy_difficulty_5",
				"ogryn_2_easy_1",
				"ogryn_2_easy_2",
				"ogryn_2_medium_1",
				"ogryn_2_medium_2",
				"ogryn_2_hard_1",
				"ogryn_2_hard_2",
				"missions_ogryn_2_medium_difficulty_1",
				"missions_ogryn_2_medium_difficulty_2",
				"missions_ogryn_2_medium_difficulty_3",
				"missions_ogryn_2_medium_difficulty_4",
				"missions_ogryn_2_medium_difficulty_5",
				"ogryn_2_bull_rushed_charging_ogryn",
				"ogryn_2_killed_corruptor_with_grenade_impact",
				"ogryn_2_win_with_coherency_all_alive_units",
				"ogryn_2_bull_rushed_100_enemies",
				"ogryn_2_bull_rushed_70_within_25_seconds",
				"ogryn_2_bull_rushed_4_ogryns",
				"ogryn_taunt_shout_hit",
				"ogryn_grenade_rock_elites_or_specialists",
				"ogryn_grenade_frag_group_of_enemies",
				"ogryn_kills_during_max_stacks_heavy_hitter",
				"ogryn_kills_during_barrage_threshold",
				"ogryn_feel_no_pain_kills_at_max",
				"ogryn_leadbelcher_free_shot",
				"ogryn_team_heavy_aura_kills",
				"ogryn_team_suppressed_aura_kills",
				"ogryn_team_toughness_restored_aura"
			}
		}
	}
}

return AchievementClassGroups
