local view_element_profile_presets_settings = {
	max_profile_presets = 5,
	optional_preset_icon_reference_keys = {
		"icon_01",
		"icon_02",
		"icon_03",
		"icon_04",
		"icon_05",
		"icon_06",
		"icon_07",
		"icon_08",
		"icon_09",
		"icon_10",
		"icon_11",
		"icon_12",
		"icon_13",
		"icon_14",
		"icon_15",
		"icon_16",
		"icon_17",
		"icon_18",
		"icon_19",
		"icon_20",
		"icon_21",
		"icon_22",
		"icon_23",
		"icon_24",
		"icon_25"
	},
	optional_preset_icons_lookup = {
		icon_25 = "content/ui/materials/icons/presets/preset_20",
		icon_10 = "content/ui/materials/icons/presets/preset_10",
		icon_24 = "content/ui/materials/icons/presets/preset_19",
		icon_04 = "content/ui/materials/icons/presets/preset_24",
		icon_16 = "content/ui/materials/icons/presets/preset_11",
		icon_01 = "content/ui/materials/icons/presets/preset_21",
		icon_13 = "content/ui/materials/icons/presets/preset_03",
		icon_21 = "content/ui/materials/icons/presets/preset_16",
		icon_07 = "content/ui/materials/icons/presets/preset_07",
		icon_19 = "content/ui/materials/icons/presets/preset_14",
		icon_12 = "content/ui/materials/icons/presets/preset_02",
		icon_20 = "content/ui/materials/icons/presets/preset_15",
		icon_06 = "content/ui/materials/icons/presets/preset_06",
		icon_18 = "content/ui/materials/icons/presets/preset_13",
		icon_03 = "content/ui/materials/icons/presets/preset_23",
		icon_15 = "content/ui/materials/icons/presets/preset_05",
		icon_23 = "content/ui/materials/icons/presets/preset_18",
		icon_09 = "content/ui/materials/icons/presets/preset_09",
		icon_02 = "content/ui/materials/icons/presets/preset_22",
		icon_14 = "content/ui/materials/icons/presets/preset_04",
		icon_22 = "content/ui/materials/icons/presets/preset_17",
		icon_11 = "content/ui/materials/icons/presets/preset_01",
		icon_08 = "content/ui/materials/icons/presets/preset_08",
		icon_05 = "content/ui/materials/icons/presets/preset_25",
		icon_17 = "content/ui/materials/icons/presets/preset_12"
	}
}

return settings("ViewElementProfilePresetsSettings", view_element_profile_presets_settings)
