-- chunkname: @scripts/settings/damage/disorientation_settings.lua

local disorientation_settings = {}

disorientation_settings.disorientation_templates = {
	toughness = {
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
	},
	toughness_melee = {
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "light_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		stun = {
			action_delay = 0.2,
			end_anim = "hit_stun_finished",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.15,
			interrupt_delay = 0.05,
			intoxication_level = 6,
			start_anim = "hit_react",
			start_anim_3p = "hit_stun",
			stun_duration = 0.3,
			stun_immunity_time_buff = "stun_immune_medium",
		},
	},
	ranged = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
	},
	burninating = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_fire",
		stun = {
			action_delay = 0,
			end_anim = "hit_stun_finished",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0,
			interrupt_delay = 0.05,
			intoxication_level = 10,
			start_anim = "hit_react",
			start_anim_3p = "hit_stun",
			stun_duration = 0.15,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	toughness_burning = {
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_fire_toughness",
		stun = {
			action_delay = 0,
			end_stun_early_time = 0,
			intoxication_level = 0,
			start_anim = "hit_react",
			start_anim_3p = "hit_react",
			stun_duration = 0,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ranged_sprinting = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
	},
	light = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "light_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0.3,
			end_anim = "hit_stun_finished",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.3,
			interrupt_delay = 0.05,
			intoxication_level = 6,
			start_anim = "hit_stun",
			start_anim_3p = "hit_stun",
			stun_duration = 0.5,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	medium = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "medium_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0.3,
			end_anim = "hit_stun_finished",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = 0.05,
			intoxication_level = 8,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 0.7,
			stun_immunity_time_buff = "stun_immune_medium",
		},
	},
	fumbled = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
	},
	ogryn_fumbled = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
	},
	heavy = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.85,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.65,
			interrupt_delay = 0.05,
			intoxication_level = 10,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_heavy",
			stun_duration = 1.25,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	shield_push = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.4,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.8,
			interrupt_delay = 0.05,
			intoxication_level = 30,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 1,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	ogryn_executor_heavy = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.6,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.8,
			interrupt_delay = 0.05,
			intoxication_level = 100,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_heavy",
			stun_duration = 1.25,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	chaos_ogryn_gunner_bullet = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.4,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = 0.05,
			intoxication_level = 25,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 0.75,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	grenadier = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "grenadier_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = 0,
			intoxication_level = 1,
			start_anim = "hit_stun",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 0.5,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	twin_grenade = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		ignore_fumbled = true,
		movement_speed_buff = "grenadier_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_corruption_2d",
		stun = {
			action_delay = 0,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = 0,
			intoxication_level = 10,
			start_anim = "hit_stun",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 1.5,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	fortitude_broken = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "fortitude_broken_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0.75,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.3,
			interrupt_delay = 0.05,
			intoxication_level = 4,
			start_anim = "hit_stun",
			start_anim_3p = "hit_stun",
			stun_duration = 0.75,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	block_broken = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "fortitude_broken_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0.75,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = false,
			intoxication_level = 25,
			start_anim = "hit_stun",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 1,
		},
	},
	block_broken_heavy = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "sniper_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 1,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 1,
			interrupt_delay = false,
			intoxication_level = 50,
			start_anim = "hit_stun",
			start_anim_3p = "hit_stun_heavy",
			stun_duration = 1.75,
		},
	},
	sniper = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "sniper_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 1,
			end_anim = "hit_stun_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 1,
			interrupt_delay = 0.05,
			intoxication_level = 50,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_heavy",
			stun_duration = 1.75,
			stun_immunity_time_buff = "stun_immune_long",
		},
	},
	falling_light = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "light_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0.2,
			end_anim = "fall_dmg_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = 0.05,
			intoxication_level = 2,
			start_anim = "fall_dmg_light",
			start_anim_3p = "fall_dmg_light",
			stun_duration = 0.6,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	falling_heavy = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "light_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.5,
			end_anim = "fall_dmg_recover",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.9,
			interrupt_delay = 0.05,
			intoxication_level = 4,
			start_anim = "fall_dmg_light",
			start_anim_3p = "fall_dmg_light",
			stun_duration = 1.2,
			stun_immunity_time_buff = "stun_immune_long",
		},
	},
	thunder_hammer_light = {
		hit_react_anim_1p = "shake_heavy",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.3,
			end_stun_early_time = 0.3,
			interrupt_delay = false,
			intoxication_level = 2,
			self_stun = true,
			stun_duration = 0.3,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	thunder_hammer_heavy = {
		hit_react_anim_1p = "shake_heavy",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.5,
			end_stun_early_time = 0.45,
			interrupt_delay = false,
			intoxication_level = 4,
			self_stun = true,
			stun_duration = 0.5,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	thunder_hammer_m2_light = {
		hit_react_anim_1p = "shake_heavy",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.25,
			end_stun_early_time = 0.25,
			interrupt_delay = false,
			intoxication_level = 2,
			self_stun = true,
			stun_duration = 0.25,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	thunder_hammer_m2_heavy = {
		hit_react_anim_1p = "shake_heavy",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.4,
			end_stun_early_time = 0.35,
			interrupt_delay = false,
			intoxication_level = 3,
			self_stun = true,
			stun_duration = 0.4,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ogryn_shovel = {
		hit_react_anim_1p = "shake_heavy",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.5,
			end_stun_early_time = 0.9,
			interrupt_delay = false,
			intoxication_level = 4,
			self_stun = true,
			stun_duration = 1.3,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	shocktrooper_frag = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "heavy_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 1,
			end_anim = "hit_stun_recover",
			end_stun_early_time = 1.2,
			interrupt_delay = 0.05,
			intoxication_level = 50,
			start_anim = "hit_stun_medium",
			stun_duration = 2,
			stun_immunity_time_buff = "stun_immune_very_long",
		},
	},
	corruption = {
		sound_event = "wwise/events/player/play_player_get_hit_corruption_2d",
	},
	corruption_tick = {
		sound_event = "wwise/events/player/play_player_get_hit_corruption_2d_tick",
	},
	toughness_corruption = {
		sound_event = "wwise/events/player/play_player_get_hit_2d_corruption_tick_toughness",
	},
	ogryn_toughness = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "ogryn_stun_movement_speed_up",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		stun = {
			action_delay = 0,
			intoxication_level = 0,
			stun_duration = 0,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ogryn_toughness_melee = {
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "ogryn_stun_movement_speed_up",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		stun = {
			action_delay = 0,
			intoxication_level = 0,
			stun_duration = 0,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ogryn_light = {
		hit_react_anim_1p = "shake_light",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "ogryn_stun_movement_speed_up",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0,
			intoxication_level = 0,
			stun_duration = 0,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ogryn_medium = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "ogryn_stun_movement_speed_up",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0,
			intoxication_level = 0,
			stun_duration = 0,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ogryn_heavy = {
		hit_react_anim_1p = "shake_heavy",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "ogryn_stun_movement_speed_up",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_heavy",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 0.2,
			end_stun_early_time = 0.4,
			interrupt_delay = 0.05,
			intoxication_level = 4,
			stun_duration = 0.5,
			stun_immunity_time_buff = "stun_immune_medium",
		},
	},
	ogryn_powermaul_disorientation = {
		hit_react_anim_1p = "shake_heavy",
		movement_speed_buff = "ogryn_powermaul_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_heavy_2d",
		stun = {
			action_delay = 1,
			end_stun_early_time = 1.2,
			interrupt_delay = 0.4,
			intoxication_level = 4,
			stun_duration = 2,
			stun_immunity_time_buff = "stun_immune_short",
		},
	},
	ranged_auto_light = {
		hit_react_anim_3p = "hit_react",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
	},
	berzerker_combo = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "medium_stun_movement_slow",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
		stun = {
			action_delay = 0,
			end_anim = "hit_stun_finished",
			end_anim_3p = "hit_stun_finished",
			end_stun_early_time = 0.5,
			interrupt_delay = 0,
			intoxication_level = 5,
			start_anim = "hit_stun_medium",
			start_anim_3p = "hit_stun_medium",
			stun_duration = 0.35,
			stun_immunity_time_buff = "stun_immune_medium",
		},
	},
	ogryn_berzerker_combo = {
		hit_react_anim_1p = "shake_medium",
		hit_react_anim_3p = "hit_react",
		movement_speed_buff = "ogryn_stun_movement_speed_up",
		screen_space_effect = "content/fx/particles/screenspace/screen_stunned_light",
		sound_event = "wwise/events/player/play_player_get_hit_light_2d",
	},
}
disorientation_settings.disorientation_types = table.enum(unpack(table.keys(disorientation_settings.disorientation_templates)))

return settings("DisorientationSettings", disorientation_settings)
