local item_dependencies = {
	minion_items = {
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_arm_left_01"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/lowerbody_a"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_torso_03"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_base/body_skin_03"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_base/body"] = 1,
		["content/items/characters/minions/chaos_hound/attachments_base/body"] = 1,
		["content/items/characters/minions/chaos_poxwalker/attachments_gear/horn_head_03"] = 1
	},
	player_items = {
		["content/items/characters/player/human/face_tattoo/dirt_tattoo_01_face"] = 2,
		["content/items/characters/player/ogryn/gear_torso/ogryn_imperial_guard_upperbody_a_01"] = 1,
		["content/items/characters/player/ogryn/gear_torso/ogryn_imperial_guard_upperbody_a"] = 1,
		["content/items/characters/player/human/gear_head/catchan_jungd_fighters_03"] = 1,
		["content/items/characters/player/human/hair/hair_short_c"] = 1,
		["content/items/characters/player/human/face_hair/facial_hair_b_fullbeard"] = 1,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_b"] = 1,
		["content/items/characters/player/human/gear_torso/enforcer_upperbody_a"] = 5,
		["content/items/characters/player/ogryn/face_hair/ogryn_facial_hair_b_goattee"] = 1,
		["content/items/characters/player/ogryn/gear_feet/ogryn_boots_c"] = 1,
		["content/items/characters/player/human/gear_feet/imperial_guard_shoes_01"] = 1,
		["content/items/characters/player/human/body_tattoo/dirt_tattoo_01_torso"] = 6,
		["content/items/characters/player/ogryn/attachment_base/male_face_asian_02"] = 1,
		["content/items/characters/player/hair_colors/hair_color_black_01"] = 2,
		["content/items/characters/player/human/gear_hands/imperial_guard_gloves_h"] = 4,
		["content/items/characters/player/human/attachment_base/male_arms"] = 1,
		["content/items/characters/player/human/gear_feet/enforcer_lowerbody_a_boots"] = 5,
		["content/items/characters/player/ogryn/hair/ogryn_hair_short_flattop_a"] = 1,
		["content/items/characters/player/ogryn/gear_legs/ogryn_pants_c"] = 1,
		["content/items/characters/player/skin_colors/skin_color_asian_02"] = 1,
		["content/items/characters/player/ogryn/attachment_base/male_torso"] = 1,
		["content/items/characters/player/human/attachment_base/male_legs"] = 1,
		["content/items/characters/player/human/gear_legs/enforcer_lowerbody_a_pants"] = 5,
		["content/items/characters/player/ogryn/attachment_base/male_arms"] = 1,
		["content/items/characters/player/human/gear_head/veteran_enforcer_helmet_a"] = 4,
		["content/items/characters/player/human/gear_arms/enforcer_upperbody_a_arms"] = 5,
		["content/items/characters/player/human/gear_head/imperial_guard_helmet_01"] = 1,
		["content/items/characters/player/human/attachment_base/male_torso"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_03"] = 1,
		["content/items/characters/player/human/faces/male_caucasian_face_01"] = 1,
		["content/items/characters/player/human/gear_legs/imperial_guard_lowerbody_01"] = 1,
		["content/items/characters/player/ogryn/gear_hands/ogryn_gloves_h"] = 1,
		["content/items/characters/player/human/gear_hands/hmn_gloves_l"] = 1,
		["content/items/characters/player/human/gear_torso/imperial_guard_upperbody_01"] = 1
	},
	weapon_items = {}
}

return item_dependencies
