-- chunkname: @scripts/extension_systems/behavior/utility_considerations/chaos_ogryn_houndmaster_utility_considerations.lua

local considerations = {
	houndmaster_melee_attack = {
		distance_to_slot = {
			blackboard_component = "slot",
			component_field = "slot_distance",
			max_value = 8,
			spline = {
				0,
				1,
				0.1,
				1,
				0.15,
				0.75,
				0.2,
				0.5,
				0.24,
				0,
				1,
				0,
			},
		},
		target_speed_away = {
			blackboard_component = "perception",
			component_field = "target_speed_away",
			max_value = 5,
			spline = {
				0,
				0.2,
				0.25,
				0.25,
				0.5,
				0.35,
				0.75,
				1,
				1,
				1,
			},
		},
		distance_to_target_z = {
			blackboard_component = "perception",
			component_field = "target_distance_z",
			max_value = 4.25,
			spline = {
				0,
				1,
				0.5,
				0,
				1,
				0,
			},
		},
		has_line_of_sight = {
			blackboard_component = "perception",
			component_field = "has_line_of_sight",
			is_condition = true,
		},
	},
	houndmaster_charge = {
		distance_to_slot = {
			blackboard_component = "slot",
			component_field = "slot_distance",
			max_value = 15,
			spline = {
				0,
				0,
				0.6,
				0,
				0.7,
				0.9,
				0.8,
				1,
				1,
				1,
			},
		},
		has_line_of_sight = {
			blackboard_component = "perception",
			component_field = "has_line_of_sight",
			is_condition = true,
		},
	},
	chaos_ogryn_houndmaster_moving_melee_attack = {
		distance_to_slot = {
			blackboard_component = "slot",
			component_field = "slot_distance",
			max_value = 8,
			spline = {
				0,
				0,
				0.5,
				0,
				0.55,
				1,
				0.85,
				1,
				1,
				0.5,
			},
		},
		distance_to_target_z = {
			blackboard_component = "perception",
			component_field = "target_distance_z",
			max_value = 3.75,
			spline = {
				0,
				1,
				0.5,
				0.5,
				1,
				0.25,
			},
		},
		target_speed_away = {
			blackboard_component = "perception",
			component_field = "target_speed_away",
			max_value = 5,
			spline = {
				0,
				0.15,
				0.25,
				0.2,
				0.5,
				0.35,
				0.75,
				1,
				1,
				1,
			},
		},
		has_line_of_sight = {
			blackboard_component = "perception",
			component_field = "has_line_of_sight",
			is_condition = true,
		},
		has_slot = {
			blackboard_component = "slot",
			component_field = "has_slot",
			is_condition = true,
		},
	},
	chaos_ogryn_houndmaster_moving_melee_attack_cleave = {
		distance_to_slot = {
			blackboard_component = "slot",
			component_field = "slot_distance",
			max_value = 8,
			spline = {
				0,
				0,
				0.2,
				0.5,
				0.25,
				1,
				0.5,
				1,
				0.55,
				0,
				1,
				0,
			},
		},
		distance_to_target_z = {
			blackboard_component = "perception",
			component_field = "target_distance_z",
			max_value = 3.75,
			spline = {
				0,
				1,
				0.5,
				0.5,
				1,
				0.25,
			},
		},
		target_speed_away = {
			blackboard_component = "perception",
			component_field = "target_speed_away",
			max_value = 5,
			spline = {
				0,
				0.2,
				0.25,
				0.25,
				0.5,
				0.35,
				0.75,
				1,
				1,
				1,
			},
		},
		has_line_of_sight = {
			blackboard_component = "perception",
			component_field = "has_line_of_sight",
			is_condition = true,
		},
		has_slot = {
			blackboard_component = "slot",
			component_field = "has_slot",
			is_condition = true,
		},
	},
	houndmaster_melee_follow = {
		distance_to_slot = {
			blackboard_component = "slot",
			component_field = "slot_distance",
			max_value = 5.5,
			spline = {
				0,
				0,
				0,
				0,
				0.8,
				0.75,
				1,
				1,
			},
		},
	},
	chaos_ogryn_houndmaster_melee_attack = {
		distance_to_slot = {
			blackboard_component = "slot",
			component_field = "slot_distance",
			max_value = 8,
			spline = {
				0,
				1,
				0.1,
				1,
				0.15,
				0.75,
				0.2,
				0.5,
				0.24,
				0,
				1,
				0,
			},
		},
		target_speed_away = {
			blackboard_component = "perception",
			component_field = "target_speed_away",
			max_value = 4,
			spline = {
				0,
				1,
				0.1,
				1,
				0.1001,
				0,
				1,
				0,
			},
		},
		distance_to_target_z = {
			blackboard_component = "perception",
			component_field = "target_distance_z",
			max_value = 6,
			spline = {
				0,
				1,
				0.5,
				0,
				1,
				0,
			},
		},
		has_line_of_sight = {
			blackboard_component = "perception",
			component_field = "has_line_of_sight",
			is_condition = true,
		},
	},
}

return considerations
